NW = "https://learn.nextwork.org/thoughtful_white_zany_vampire/uploads/"

LOCAL_LEGEND_INTRO = "the running cluster"

PAGES = [
# ======================================================================
dict(
    slug="helm-cicd-monitoring",
    card=dict(group="k8s", eyebrow="Kubernetes / Observability", color="c-app", status="Local cluster",
              title="Kubernetes CI/CD with Helm and monitoring",
              desc="A Jenkins pipeline that only passes when the rollout does, a reusable Helm chart, and an alert that waits two minutes before it fires."),
    title_tag="Kubernetes CI/CD with Helm & Monitoring",
    meta="Case study: a Flask app shipped to Kubernetes by a four-stage Jenkins pipeline, packaged as a Helm chart, and watched by Prometheus and Grafana. What was built, and what was actually verified.",
    eyebrow="Kubernetes / Observability",
    h1="Kubernetes CI/CD with Helm and full-stack monitoring",
    standfirst="I shipped a small Flask app, FitTrack, to Kubernetes through a four-stage Jenkins pipeline, packaged it as a reusable Helm chart, and put Prometheus and Grafana around it with an alert that only fires when 5xx errors stay above 5% for two full minutes.",
    chip="Local cluster",
    status="This ran on a Kubernetes cluster inside Rancher Desktop on my laptop, not in a cloud account, and nothing was ever exposed publicly. The chart, the <code>Jenkinsfile</code> and <code>monitoring-values.yaml</code> in the repo reproduce it on any cluster with Helm installed. Everything below describes that local run.",
    spec=[("Platform", "Kubernetes on Rancher Desktop"), ("Packaging", "Helm chart + values overrides"),
          ("CI/CD", "Jenkins, 4 stages"), ("Registry", "Docker Hub, build-number tags"),
          ("Monitoring", "kube-prometheus-stack"), ("Alert", "5xx &gt; 5% for 2 minutes")],
    summary="FitTrack is a multi-page Flask app that exposes a <code>/metrics</code> endpoint with request counts per route. A Jenkins pipeline checked out the code, built the image, pushed it to Docker Hub under both the build number and <code>latest</code>, then ran <code>kubectl set image</code> and waited on <code>rollout status</code>, so a rollout that never converged failed the build. kube-prometheus-stack, installed by Helm with my own values, found the app through a <code>ServiceMonitor</code>, drew it in Grafana, and evaluated a <code>PrometheusRule</code> on the 5xx rate. The app itself was then packaged as its own Helm chart with replicas, image tag and resources templated.",
    how=[
        ("Why a Helm chart instead of the raw manifests?", "Copy-pasted YAML has no version and no undo. A chart is a set of Go templates; the values fill in the placeholders (<code>{{ .Values }}</code>), and <code>--set</code> or a values file overrides them per environment. Each install is a numbered release, so going back is <code>helm rollback</code>, not working out which YAML was applied last."),
        ("Why does the pipeline wait on <code>rollout status</code>?", "<code>kubectl set image</code> returns as soon as the API server accepts the change, which says nothing about whether new pods ever became ready. Waiting on <code>rollout status</code> makes the Deploy stage fail when the rollout doesn't converge, so a green build means the new version is actually running."),
        ("Why does the <code>ServiceMonitor</code> need cross-namespace discovery?", "The Prometheus Operator only scrapes what a <code>ServiceMonitor</code> selects, and out of the box it only looks at monitors from its own release. I changed that in <code>monitoring-values.yaml</code> so Prometheus discovers monitors in other namespaces too. Without it FitTrack's monitor exists and nothing ever scrapes it."),
        ("Why wait two minutes before the alert fires?", "A single 5xx is a blip, not an incident. The rule fires only when more than 5% of requests return 5xx for two continuous minutes, so a one-off failure never pages anyone. The liveness and readiness probes handle the short-term damage in the meantime: liveness restarts a wedged container, readiness pulls an unready pod out of the Service without restarting it."),
    ],
    diagram=dict(
        h=600,
        aria="Architecture of the FitTrack pipeline: an engineer pushes to GitHub, Jenkins builds the image, pushes it to Docker Hub and runs kubectl set image against the FitTrack Deployment. Helm installs the chart and the monitoring stack. Inside the cluster a ServiceMonitor selects FitTrack, Prometheus scrapes its metrics endpoint, evaluates a PrometheusRule and feeds Grafana.",
        boxes=[dict(x=598, y=70, w=630, h=500, k="ctl", label="KUBERNETES CLUSTER — RANCHER DESKTOP · KUBE-PROMETHEUS-STACK VIA HELM")],
        nodes=[
            dict(id="eng", x=16, y=120, w=136, k="neu", icon="user", slot="engineer", t="Engineer", s="git push", tag="code change"),
            dict(id="gh", x=192, y=120, w=150, k="ctl", icon="git", slot="github", t="GitHub", s="app + Jenkinsfile", tag="source"),
            dict(id="jk", x=388, y=120, w=170, k="ctl", icon="gear", slot="jenkins", t="Jenkins", s="checkout → build → push", tag="4 stages"),
            dict(id="dh", x=388, y=300, w=170, k="neu", icon="box", slot="docker-hub", t="Docker Hub", s=":BUILD_NUMBER + :latest", tag="registry"),
            dict(id="helm", x=192, y=460, w=166, k="ctl", icon="doc", slot="helm", t="Helm", s="chart + values files", tag="releases"),
            dict(id="ft", x=626, y=120, w=180, k="app", icon="server", slot="flask", t="FitTrack app", s="Flask · /metrics", tag="probes + limits"),
            dict(id="sm", x=862, y=120, w=176, k="obs", icon="filter", slot="kubernetes", t="ServiceMonitor", s="selects FitTrack's Service", tag="cross-namespace"),
            dict(id="prom", x=862, y=300, w=160, k="obs", icon="trend", slot="prometheus", t="Prometheus", s="scrapes /metrics", tag="kube-prom-stack"),
            dict(id="rule", x=1062, y=300, w=154, k="obs", icon="bell", slot="alert", t="PrometheusRule", s="5xx > 5% for 2m", tag="alert"),
            dict(id="graf", x=862, y=460, w=176, k="obs", icon="bars", slot="grafana", t="Grafana", s="dashboards", tag="live metrics"),
        ],
        edges=[
            dict(**{"from": "eng", "to": "gh"}, k="ctl", mech="git push", what="A code change lands in the repository Jenkins watches."),
            dict(**{"from": "gh", "to": "jk"}, k="ctl", mech="triggers job", what="Starts the declarative pipeline: checkout, build, push, deploy."),
            dict(**{"from": "jk", "to": "dh"}, k="ctl", mech="docker push", what="Pushes the image twice: under the build number and under <code>latest</code>."),
            dict(**{"from": "jk", "to": "ft"}, k="req", mech="kubectl set image", what="Points the Deployment at the new tag, then waits on <code>rollout status</code>; a rollout that never converges fails the build."),
            dict(**{"from": "dh", "to": "ft"}, k="data", ss="r", ts="b", to_off=0, mech="image pull", what="The kubelet pulls the newly tagged image for the replacement pods."),
            dict(**{"from": "helm", "to": "ft"}, k="ctl", ss="r", ts="b", to_off=-55, mech="helm install / upgrade", what="Installs FitTrack from its own chart, and kube-prometheus-stack from <code>monitoring-values.yaml</code>."),
            dict(**{"from": "sm", "to": "ft"}, k="obs", dash=True, mech="label selector", what="Names the Service and the <code>/metrics</code> endpoint Prometheus should scrape."),
            dict(**{"from": "sm", "to": "prom"}, k="obs", dash=True, mech="target discovery", what="The operator turns the monitor into a scrape target, even though it lives outside the monitoring namespace."),
            dict(**{"from": "prom", "to": "ft"}, k="obs", dash=True, ss="l", ts="b", to_off=60, mech="HTTP scrape", what="Reads request counts per route from FitTrack's <code>/metrics</code>."),
            dict(**{"from": "prom", "to": "rule"}, k="obs", dash=True, mech="rule evaluation", what="Fires only when more than 5% of requests return 5xx for two continuous minutes."),
            dict(**{"from": "prom", "to": "graf"}, k="obs", dash=True, mech="PromQL", what="Feeds the custom FitTrack dashboard."),
        ],
    ),
    figcaption="The stack as it ran. Arrow 4 is the only way Jenkins touched the cluster, and the stage didn't pass until the rollout did. Everything dashed (7 through 11) is the monitoring side: discovered through a <code>ServiceMonitor</code>, not configured by hand per target.",
    legend=[("c-neu", "Actors &amp; registry", "engineer, Docker Hub"), ("c-ctl", "Source, CI &amp; packaging", "GitHub, Jenkins, Helm"),
            ("c-app", "Application workload", "FitTrack in the cluster"), ("c-obs", "Monitoring", "ServiceMonitor, Prometheus, rule, Grafana"),
            ("line:c-ctl", "Pipeline step", "push, build, install"), ("line:c-app", "Deploy", "kubectl set image"),
            ("line:dg-line", "Image pull", "registry to kubelet"), ("line:c-obs:dashed", "Metrics path", "discovered, not hard-coded")],
    reach=[("Public", "nothing; the cluster lived on my laptop and had no ingress."),
           ("Internal", "FitTrack, Prometheus, Grafana and Alertmanager, all inside the cluster."),
           ("Outside it", "GitHub and Docker Hub. Jenkins needed a working <code>kubectl</code> context to reach the cluster at all, which turned out to be the hard part.")],
    ledger_intro_obs="the running cluster",
    ledger=[
        ("observed", "Grafana showed live FitTrack metrics through the ServiceMonitor",
         "Once the cross-namespace discovery setting was in, Prometheus picked up FitTrack's <code>ServiceMonitor</code> and the custom dashboard showed request counts per route coming from the app's own <code>/metrics</code> endpoint &mdash; real application data, not just node metrics.",
         "Checked the scrape target in Prometheus and the panels on the FitTrack dashboard in Grafana."),
        ("observed", "The 5xx alert rule reached the firing state",
         "The <code>PrometheusRule</code> appeared in Prometheus and was captured firing on the error threshold. I'm recording that the rule fired, not a timed measurement of how long detection took &mdash; I didn't stopwatch the gap between the first errors and the alert.",
         "Read the rule's state in the alerting view (screenshot below)."),
        ("observed", "A push ended with the new image running, with no manual step",
         "After the <code>kubectl</code> problem below was fixed, a commit went through checkout, build, a push of both tags to Docker Hub, and <code>kubectl set image</code> with <code>rollout status</code>, all from the one pipeline run.",
         "Followed the stage view in Jenkins and the Deployment's image tag in the cluster afterwards."),
        ("design", "A rollout that never converges fails the build &mdash; untested",
         "The Deploy stage waits on <code>rollout status</code>, which exits non-zero if the rollout doesn't complete. I never pushed a deliberately broken image to watch the stage go red, so this is what the stage is built to do, not a failure I forced.",
         "Reviewed the Deploy stage in the <code>Jenkinsfile</code>. Not tested with a bad image."),
        ("design", "Rollback is one <code>helm rollback</code> &mdash; not exercised",
         "Every install of the chart is a numbered release, and the same chart takes per-environment values through <code>--set</code> or a values file. I didn't run a rollback against a bad release here, so I'm claiming the mechanism, not a recovery.",
         "Reviewed the chart's templated values and the release history. No rollback was performed."),
    ],
    proof_note="From the running cluster",
    shots=[
        dict(url=NW + "15afd2e5-d464-4cb6-89bc-947b6d20187f_q1bqjlia", alt="Grafana dashboard showing live FitTrack application metrics", cap="The FitTrack dashboard on live app metrics."),
        dict(url=NW + "15afd2e5-d464-4cb6-89bc-947b6d20187f_4erk6j8j", alt="Prometheus alert rule firing on the 5xx error threshold", cap="The <code>PrometheusRule</code> firing on its error threshold."),
    ],
    broke=[
        ("Jenkins couldn't find <code>kubectl</code>, then couldn't use it against the cluster",
         "Checkout, build and push all went green early. The Deploy stage didn't: Jenkins couldn't discover the <code>kubectl</code> binary, and when it could, it still couldn't execute commands against the cluster. Most of the roughly eight hours went here. It's the least glamorous lesson in the project &mdash; a CI server that deploys needs its own working toolchain and its own cluster access, and neither comes for free just because your laptop has them."),
    ],
    source="The Flask app with its Prometheus metrics, the Helm chart and its <code>ServiceMonitor</code>, and the <code>Jenkinsfile</code> live here: <a href=\"https://github.com/kingswanzy2020/fittrack\">kingswanzy2020/fittrack</a>.",
    clone="git clone https://github.com/kingswanzy2020/fittrack.git",
    stack="Kubernetes &middot; Helm charts &amp; templating &middot; kube-prometheus-stack &middot; Prometheus &middot; Grafana &middot; PrometheusRules &middot; ServiceMonitors &middot; Jenkins declarative pipeline &middot; Docker &middot; Docker Hub &middot; Flask instrumentation &middot; liveness / readiness probes &middot; resource limits",
),
# ======================================================================
dict(
    slug="jenkins-argocd-gitops",
    card=dict(group="k8s", eyebrow="Kubernetes / GitOps", color="c-ctl", status="Local cluster",
              title="Jenkins CI handing off to ArgoCD",
              desc="Two repos and one rule: CI commits an image tag to Git and never touches the cluster. ArgoCD is the only thing that deploys."),
    title_tag="Jenkins CI to ArgoCD GitOps",
    meta="Case study: a two-repo pipeline where Jenkins builds and tags an image, commits the tag to a manifests repo, and ArgoCD deploys it. What was built, and what was actually verified.",
    eyebrow="Kubernetes / GitOps",
    h1="A two-repo pipeline where Jenkins never touches the cluster",
    standfirst="I split CI and CD across two repositories: Jenkins builds the image, pushes a build-numbered tag to Docker Hub and commits that tag to a manifests repo, and ArgoCD is the only thing that ever applies anything to Kubernetes.",
    chip="Local cluster",
    status="This ran against a local cluster through my own kubeconfig; Terraform created the namespaces and PostgreSQL there before the pipeline's first run. Nothing was exposed publicly. The two repos reproduce it on any cluster with ArgoCD installed, and everything below describes that run.",
    spec=[("Platform", "Kubernetes, ArgoCD auto-sync"), ("CI", "Jenkins, Docker Hub"),
          ("Handoff", "Git commit to a manifests repo"), ("Image tags", ":BUILD_NUMBER, pinned"),
          ("Database", "PostgreSQL in its own namespace"), ("Baseline", "Terraform, kubernetes provider")],
    summary="A push to <code>devops-pipeline-app</code> triggered a Jenkins job that built the Flask API with a multi-stage Dockerfile and pushed it to Docker Hub as <code>:BUILD_NUMBER</code> and <code>:latest</code>. Jenkins then cloned <code>devops-pipeline-manifests</code>, rewrote the image line in <code>k8s/deployment.yaml</code> with <code>sed</code> and pushed the commit as <code>Jenkins CI</code>. ArgoCD auto-synced that repo and rolled the two-replica <code>devops-app</code> Deployment in <code>production</code> over to the new tag. The pods reached PostgreSQL in the <code>database</code> namespace, which Terraform had created along with the namespaces.",
    how=[
        ("Why a Git commit as the handoff instead of <code>kubectl apply</code> from CI?", "If CI ends with <code>kubectl apply</code>, the build server needs a kubeconfig that can write to production, and a compromised job is a compromised cluster. Here Jenkins holds Docker Hub and GitHub credentials and nothing else. Its last stage clones the manifests repo with a <code>github-creds</code> token, changes one line, and pushes. ArgoCD pulls that change in; Jenkins never learns the cluster's address."),
        ("Why pin the build number instead of <code>:latest</code>?", "When every deploy reuses one tag, nobody can say which build is running and a rollback has nothing to go back to. Every build pushes both tags, but the manifest always pins the numbered one, so the manifests repo's history reads as a deploy log &mdash; <code>Update image to build 2</code> &mdash; and rolling back is reverting one Jenkins commit while the older image is still on Docker Hub."),
        ("Why is the database in its own namespace?", "The app runs in <code>production</code> and PostgreSQL in <code>database</code>, reached at the fully qualified <code>postgres-service.database.svc.cluster.local</code> through <code>DB_HOST</code>. Splitting them means each can get its own access controls and quotas later without editing the app manifest."),
        ("Why does <code>/health</code> query the database?", "<code>/health</code> runs <code>SELECT 1</code> and returns <code>500</code> if it fails, so it reports whether the app can reach its data, not just whether the process is up. It's built as a readiness target. The image itself is a two-stage build: dependencies installed with <code>--prefix=/install</code> in a builder, only <code>/install</code> copied into a fresh <code>python:3.11-slim</code>, run as a non-root user under Gunicorn with two workers."),
    ],
    diagram=dict(
        h=560,
        aria="Pipeline: a developer pushes to the app repo, which triggers Jenkins. Jenkins pushes the image to Docker Hub and commits the new tag to the manifests repo. ArgoCD watches the manifests repo and rolls the devops-app Deployment in the production namespace, which pulls the image from Docker Hub and queries PostgreSQL in the database namespace. Terraform created the namespaces and PostgreSQL.",
        boxes=[dict(x=640, y=70, w=588, h=460, k="app", label="KUBERNETES — LOCAL KUBECONFIG · NAMESPACES BY TERRAFORM"),
               dict(x=660, y=250, w=548, h=118, k="app", dash="3 4", sw=1.1, fs=10, label="NAMESPACE production"),
               dict(x=660, y=410, w=548, h=106, k="app", dash="3 4", sw=1.1, fs=10, label="NAMESPACE database")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="git push", tag="app code"),
            dict(id="app", x=196, y=110, w=176, k="ctl", icon="git", slot="github", t="devops-pipeline-app", s="Flask · Dockerfile", tag="Jenkinsfile"),
            dict(id="jk", x=196, y=280, w=176, k="ctl", icon="gear", slot="jenkins", t="Jenkins", s="no kubeconfig", tag="build · push · commit"),
            dict(id="dh", x=196, y=440, w=176, k="neu", icon="box", slot="docker-hub", t="Docker Hub", s=":BUILD_NUMBER + :latest", tag="registry"),
            dict(id="man", x=408, y=280, w=190, k="ctl", icon="doc", slot="github", t="manifests repo", s="k8s/deployment.yaml", tag="deploy log"),
            dict(id="argo", x=680, y=110, w=170, k="app", icon="cycle", slot="argocd", t="ArgoCD", s="auto-sync", tag="only deployer"),
            dict(id="pods", x=680, y=268, w=200, k="app", icon="pod", slot="workload", t="devops-app × 2", s="Gunicorn · non-root", tag="maxSurge 1"),
            dict(id="pg", x=680, y=424, w=200, k="app", icon="db", slot="postgresql", t="PostgreSQL", s="postgres-service", tag="ClusterIP"),
            dict(id="tf", x=1020, y=424, w=170, k="aws", icon="code", slot="terraform", t="Terraform", s="kubernetes provider", tag="baseline"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "app"}, k="ctl", mech="git push", what="An app change lands in the source repo."),
            dict(**{"from": "app", "to": "jk"}, k="ctl", mech="triggers job", what="Starts the Jenkinsfile: build, push, update manifest."),
            dict(**{"from": "jk", "to": "dh"}, k="ctl", mech="docker push", what="Pushes <code>:BUILD_NUMBER</code> and <code>:latest</code>."),
            dict(**{"from": "jk", "to": "man"}, k="ctl", mech="sed + git push", what="Rewrites the image tag in <code>k8s/deployment.yaml</code> and commits it as <code>Jenkins CI</code>."),
            dict(**{"from": "man", "to": "argo"}, k="req", ss="t", ts="l", mech="watched repo", what="ArgoCD sees the new commit; this is the only path into the cluster."),
            dict(**{"from": "argo", "to": "pods"}, k="req", mech="rolling update", what="Two replicas, <code>maxUnavailable: 1</code>, <code>maxSurge: 1</code>."),
            dict(**{"from": "dh", "to": "pods"}, k="data", pts=[(372, 484), (624, 484), (624, 312), (676, 312)], dash=True, mech="image pull", what="The kubelet pulls the pinned build-number tag."),
            dict(**{"from": "pods", "to": "pg"}, k="data", so=60, to_off=60, mech="cluster DNS", what="<code>postgres-service.database.svc.cluster.local</code>, passed in as <code>DB_HOST</code>."),
            dict(**{"from": "tf", "to": "pg"}, k="aws", dash=True, mech="terraform apply", what="Created the namespaces and PostgreSQL before the pipeline's first run."),
        ],
    ),
    figcaption="The handoff as it ran. Arrow 4 is a Git commit, not a deploy &mdash; that's the whole design. Jenkins's arrows all stop at a registry or a repository, and only ArgoCD (5, 6) reaches into the cluster.",
    legend=[("c-neu", "Actors &amp; registry", "developer, Docker Hub"), ("c-ctl", "Git &amp; CI", "both repos, Jenkins"),
            ("c-app", "Cluster", "ArgoCD, the app, PostgreSQL"), ("c-aws", "Provisioning", "Terraform baseline"),
            ("line:c-ctl", "CI flow", "into Git and the registry"), ("line:c-app", "Sync / roll", "Git to cluster"),
            ("line:dg-line", "Data path", "image pull, queries")],
    reach=[("Public", "nothing; there was no ingress or load balancer."),
           ("Internal", "ArgoCD, the two <code>devops-app</code> pods and PostgreSQL, across two namespaces."),
           ("Held by CI", "Docker Hub and GitHub credentials. No kubeconfig, which is the point.")],
    ledger=[
        ("observed", "Build #2 went from <code>git push</code> to running pods with no manual step",
         "Jenkins build #2 built the image, pushed it and committed the new tag; ArgoCD picked the commit up and rolled the Deployment. Jenkins's commit landed at 19:04:02 and both new pods were running by 19:06:10 &mdash; about two minutes from manifest commit to running pods, read off the commit time and the pod ages, not a timed benchmark.",
         "Compared the manifests repo commit timestamp against <code>kubectl get pods -n production</code>: 2/2 pods <code>Running</code> 1/1, 0 restarts, 116 seconds old."),
        ("observed", "ArgoCD reported <code>Synced</code> and <code>Healthy</code> for both resources",
         "<code>argocd app get devops-app</code> showed the Deployment and the Service both <code>Synced</code> and <code>Healthy</code>, with the manifest pinning <code>devops-pipeline-app:2</code> rather than <code>:latest</code>.",
         "Ran <code>argocd app get devops-app</code> after the rollout."),
        ("observed", "The app reached PostgreSQL &mdash; under Compose",
         "<code>curl localhost:5000/health</code> returned <code>{\"database\":\"connected\",\"status\":\"healthy\"}</code> when I ran the stack under Docker Compose. In the cluster I saw Terraform's Postgres pod <code>Running</code> with 0 restarts, but the health response itself was captured under Compose, so that's where I'm claiming it.",
         "<code>curl</code> against <code>/health</code> under Docker Compose; <code>kubectl get pods -n database</code> in the cluster."),
        ("design", "CI holds no cluster credentials",
         "Jenkins's credential store has Docker Hub and GitHub entries and no kubeconfig, and the pipeline never calls <code>kubectl</code> or the ArgoCD API. A compromised build could push a bad tag to Git, which shows up in review history &mdash; it couldn't write to the cluster directly. I didn't try to break out of a job to prove it.",
         "Reviewed the <code>Jenkinsfile</code> and the Jenkins credentials. Not adversarially tested."),
        ("design", "<code>/health</code> fails when the database is gone &mdash; untested in the cluster",
         "<code>/health</code> runs <code>SELECT 1</code> and returns <code>500</code> on failure, which is what a readiness probe needs to pull a pod out of the Service. I didn't take PostgreSQL down in the cluster to watch the endpoints change.",
         "Read the handler. No outage was simulated."),
    ],
    proof_note="From the running cluster and the pipeline",
    shots=[
        dict(raw="kubernetes/devops-pipeline/Screenshots/Screenshot from 2026-09-10 17-09-37.png", alt="ArgoCD devops-app tree: Synced to 6c083e8, app health Progressing, both pods in ErrImagePull", cap="Synced, not healthy: the first manifest pointed at an image that didn't exist yet."),
        dict(raw="kubernetes/devops-pipeline/Screenshots/Screenshot from 2026-09-10 19-08-06.png", alt="kubectl get pods -n production: two devops-app pods Running 1/1 with 0 restarts, 116s old", cap="Build #2 rolled out by Jenkins and ArgoCD: 2/2 running, 0 restarts."),
        dict(raw="kubernetes/devops-pipeline/Screenshots/Screenshot from 2026-09-10 19-27-46.png", alt="argocd app get devops-app: Deployment and Service both Synced and Healthy", cap="ArgoCD: Deployment and Service both <code>Synced</code> and <code>Healthy</code>."),
        dict(raw="kubernetes/devops-pipeline/Screenshots/Screenshot from 2026-09-10 15-39-32.png", alt="curl localhost:5000/health returning database connected, status healthy", cap="The API reaching Postgres under Compose."),
    ],
    broke=[
        ("ArgoCD said <code>Synced</code> while every pod was failing",
         "The first manifest commit pointed at <code>ahmed3015/devops-pipeline-app:latest</code> before Jenkins had pushed any image. ArgoCD applied it without complaint and showed <strong>Synced</strong> to <code>6c083e8</code>, while app health sat at <strong>Progressing</strong> and both pods were stuck in <code>ErrImagePull</code>. Synced only means the cluster matches Git; Health is what tells you whether the workload runs. Re-syncing couldn't fix it &mdash; the pipeline had to deliver a real image first."),
        ("Build #1 failed on a template placeholder nobody replaced",
         "The Jenkinsfile was committed with <code>DOCKER_IMAGE = \"[[DOCKERHUB_USERNAME=\\\"ahmed3015\\\"]]/devops-pipeline-app\"</code>. Docker rejects brackets in an image name, so the build died before pushing anything. Once it read <code>ahmed3015/devops-pipeline-app</code>, build #2 went all the way through &mdash; which is why the first tag in the manifests repo is <code>:2</code>, not <code>:1</code>."),
    ],
    source="The pipeline is split across two repos, the same way the design is. <a href=\"https://github.com/kingswanzy2020/devops-pipeline-app\">kingswanzy2020/devops-pipeline-app</a> has the Flask + PostgreSQL API, the multi-stage <code>Dockerfile</code>, the <code>Jenkinsfile</code>, <code>docker-compose.yml</code> and <code>terraform/main.tf</code>. <a href=\"https://github.com/kingswanzy2020/devops-pipeline-manifests\">kingswanzy2020/devops-pipeline-manifests</a> has the Deployment and Service ArgoCD watches and Jenkins commits to.",
    clone="git clone https://github.com/kingswanzy2020/devops-pipeline-app.git\ngit clone https://github.com/kingswanzy2020/devops-pipeline-manifests.git",
    stack="Jenkins &middot; ArgoCD &middot; GitOps &middot; Kubernetes &middot; Terraform (kubernetes provider) &middot; Docker multi-stage builds &middot; Docker Hub &middot; Flask &middot; Gunicorn &middot; PostgreSQL &middot; rolling updates &middot; cross-namespace service discovery &middot; build-numbered image tags",
),
# ======================================================================
dict(
    slug="gitops-5g-core",
    card=dict(group="k8s", eyebrow="Kubernetes / GitOps", color="c-app", status="Local cluster",
              title="A GitOps-driven 5G core on Kubernetes",
              desc="Open5GS reconciled by an Operator from Git: a new network slice is a two-line commit, synced about two minutes later."),
    title_tag="GitOps-Driven 5G Core",
    meta="Case study: an Open5GS 5G standalone core run as network functions on Kubernetes, reconciled by an Operator from Git through ArgoCD, with Prometheus scraping the functions and the Operator.",
    eyebrow="Kubernetes / GitOps",
    h1="A GitOps-driven 5G core on Kubernetes",
    standfirst="I ran an Open5GS 5G standalone core as cloud-native network functions, where adding a network slice is a two-line Git commit: ArgoCD applies it, and the Open5GS Operator turns it into running config.",
    chip="Local cluster",
    status="This ran on the Kubernetes cluster built into Docker Desktop on my machine, with no radio side attached &mdash; no gNB or UE simulator, so no device ever registered. The repo's three ArgoCD Applications rebuild it on any cluster with ArgoCD installed. Everything below describes that local core.",
    spec=[("Platform", "Kubernetes on Docker Desktop"), ("Core", "Open5GS 5G SA, 11 NFs + MongoDB"),
          ("Reconciled by", "Open5GS Operator (chart 1.0.7)"), ("Delivered by", "ArgoCD, 3 Applications"),
          ("Layout", "Kustomize bases + overlays/local"), ("Observability", "ServiceMonitors on AMF, PCF, UPF")],
    summary="One Git repository, <code>telco-platform-gitops</code>, describes the whole core: kube-prometheus-stack, the Open5GS Operator, the <code>Open5GS</code> custom resource with its PLMN (<code>999/70</code>), TAC and slices, an <code>Open5GSUser</code> subscriber, and the wiring that lets Prometheus scrape the Operator itself. ArgoCD syncs three Applications from it. The Operator reconciles the one <code>Open5GS</code> resource into eleven network functions plus MongoDB, and rewrites only the config a change touches. Prometheus scrapes the AMF, PCF and UPF, and the Operator's own reconcile metrics, into Grafana.",
    how=[
        ("Why an Operator instead of raw manifests?", "The core is a single <code>Open5GS</code> custom resource: PLMN, TAC, and a list of slices. The Operator owns translating that into the individual Deployments and ConfigMaps for every network function. A slice change becomes a two-line diff to that resource instead of hand-editing NF config files, and the reconcile loop keeps the live functions matching it."),
        ("Why three ArgoCD Applications, synced in order?", "<code>observability</code> (kube-prometheus-stack), <code>open5gs-operator</code> (Gradiant's chart, <code>1.0.7</code>) and <code>open5gs-cr</code> (this repo's <code>overlays/local</code>) are separate Applications. Observability goes first because the Operator can only create <code>ServiceMonitor</code> objects once that CRD exists."),
        ("Why eleven network functions and not seven?", "The track focuses on the seven headline 5G SA functions &mdash; AMF, SMF, UPF, NRF, UDM, AUSF, PCF &mdash; which is where my first count of 7 + MongoDB came from. The Operator also enables NSSF, BSF, SCP and UDR by default. They were already running before the second slice existed: ArgoCD showed the BSF ConfigMap two hours old right after the slice sync."),
        ("Why scrape the Operator as well as the functions?", "\"Pods are running\" says little about whether a change was reconciled. A separate base adds a <code>ServiceMonitor</code> for the controller-manager plus a <code>ClusterRoleBinding</code> so Prometheus's ServiceAccount passes kube-rbac-proxy's <code>SubjectAccessReview</code>. With <code>controller_runtime_reconcile_total</code> available, reconciliation is read directly instead of guessed from restarts. On the functions, metrics are enabled only on the AMF, PCF and UPF &mdash; registration, policy and data-plane state."),
    ],
    diagram=dict(
        h=640,
        aria="An engineer commits slice or subscriber changes to the telco-platform-gitops repo. ArgoCD syncs three Applications: kube-prometheus-stack, the Open5GS Operator chart, and the overlays/local Kustomize overlay holding the Open5GS and Open5GSUser custom resources. The Operator reconciles the custom resource into eleven network functions plus MongoDB. Prometheus scrapes the AMF, PCF and UPF through ServiceMonitors and the Operator through kube-rbac-proxy, and Grafana shows both.",
        boxes=[dict(x=430, y=60, w=798, h=556, k="ctl", label="KUBERNETES — DOCKER DESKTOP · NAMESPACES argocd · open5gs · monitoring")],
        nodes=[
            dict(id="eng", x=16, y=120, w=136, k="neu", icon="user", slot="engineer", t="Engineer", s="slice / subscriber", tag="git commit"),
            dict(id="gh", x=196, y=120, w=196, k="ctl", icon="git", slot="github", t="telco-platform-gitops", s="apps/ · bases · overlays", tag="desired state"),
            dict(id="argo", x=460, y=120, w=176, k="ctl", icon="cycle", slot="argocd", t="ArgoCD", s="3 Applications", tag="Synced + Healthy"),
            dict(id="cr", x=700, y=120, w=196, k="app", icon="doc", slot="kubernetes", t="Open5GS CR", s="PLMN 999/70 · 2 slices", tag="+ Open5GSUser"),
            dict(id="op", x=960, y=120, w=230, k="ctl", icon="ctl", slot="operator", t="Open5GS Operator", s="chart 1.0.7 · reconciles", tag="kube-rbac-proxy"),
            dict(id="nf", x=620, y=300, w=270, k="app", icon="signal", slot="open5gs", t="5G core network functions", s="AMF SMF UPF PCF NRF AUSF UDM", tag="+ UDR NSSF BSF SCP · MongoDB"),
            dict(id="prom", x=960, y=380, w=200, k="obs", icon="trend", slot="prometheus", t="Prometheus", s="kube-prometheus-stack", tag="ServiceMonitors"),
            dict(id="graf", x=960, y=508, w=200, k="obs", icon="bars", slot="grafana", t="Grafana", s="NF resources + reconcile", tag="dashboard"),
        ],
        edges=[
            dict(**{"from": "eng", "to": "gh"}, k="ctl", mech="git commit", what="A slice or subscriber change, e.g. <code>5907f0e</code> adding <code>SST 2</code>."),
            dict(**{"from": "gh", "to": "argo"}, k="ctl", mech="watched repo", what="Three Applications: observability, the Operator chart, and <code>overlays/local</code>."),
            dict(**{"from": "argo", "to": "cr"}, k="req", mech="sync", what="Applies the <code>Open5GS</code> and <code>Open5GSUser</code> custom resources."),
            dict(**{"from": "op", "to": "cr"}, k="ctl", dash=True, ss="l", ts="r", mech="watch", what="The Operator watches the custom resource for changes."),
            dict(**{"from": "op", "to": "nf"}, k="ctl", ss="b", ts="r", so=-60, mech="reconcile", what="Writes Deployments and ConfigMaps; a new slice only touches the AMF's <code>s_nssai</code> and the NSSF's <code>nsi</code>."),
            dict(**{"from": "prom", "to": "nf"}, k="obs", dash=True, ss="l", ts="b", mech="ServiceMonitors", what="Scrapes the AMF, PCF and UPF; scrape duration about 1 ms each."),
            dict(**{"from": "prom", "to": "op"}, k="obs", dash=True, ss="t", ts="b", to_off=35, so=50, mech="kube-rbac-proxy", what="Reads <code>controller_runtime_reconcile_total</code>, allowed by a <code>ClusterRoleBinding</code>."),
            dict(**{"from": "prom", "to": "graf"}, k="obs", dash=True, mech="PromQL", what="Per-pod CPU and memory, AMF/UPF stats, restarts, reconcile rate."),
        ],
    ),
    figcaption="The core as it ran. Arrow 5 is where a two-line Git diff becomes network-function config &mdash; the Operator, not me, decides which ConfigMaps change. Arrows 6 and 7 watch both sides: the functions, and the controller doing the reconciling.",
    legend=[("c-neu", "Human actor", "the engineer committing"), ("c-ctl", "Git &amp; control plane", "repo, ArgoCD, the Operator"),
            ("c-app", "Desired &amp; running core", "the custom resource and the NFs"), ("c-obs", "Observability", "Prometheus and Grafana"),
            ("line:c-ctl", "Commit &amp; reconcile", "Git in, config out"), ("line:c-app", "ArgoCD sync", "applies the overlay"),
            ("line:c-obs:dashed", "Scrape", "functions and the Operator")],
    reach=[("Public", "nothing; the cluster ran inside Docker Desktop on my machine."),
           ("Internal", "ArgoCD, the Operator, eleven network functions, MongoDB, Prometheus and Grafana."),
           ("Not attached", "any radio side. No gNB or UE simulator, so the AMF and UPF session panels read 0.")],
    ledger=[
        ("measured", "A new slice went from commit to <code>Sync OK</code> in about two minutes",
         "Commit <code>5907f0e</code> added a URLLC-style slice (<code>SST 2</code>, <code>SD 0x222222</code>) next to the existing <code>SST 1 / SD 0x111111</code> at 02:20. ArgoCD reported <em>Sync OK</em> to that commit at 02:22:01. The slice added no pods &mdash; it landed as new config on two functions.",
         "Compared the commit time against the sync time on the <code>open5gs-cr</code> Application, and checked which ConfigMaps changed."),
        ("observed", "All three Applications were <code>Healthy</code> and <code>Synced</code>",
         "<code>observability</code>, <code>open5gs-cr</code> and <code>open5gs-operator</code> all showed Healthy and Synced, with eleven network functions plus MongoDB running from one <code>Open5GS</code> resource.",
         "Read the Application tiles in the ArgoCD UI."),
        ("observed", "Prometheus scraped the AMF, PCF and UPF, and the Operator's reconcile rate was visible",
         "All three ServiceMonitor targets showed <code>UP</code> with a scrape duration of 1 ms each. After the metrics commit landed, the reconcile rate for <code>controller=\"open5gs\"</code> appeared at about 0.1/s.",
         "Filtered Prometheus target health to <code>open5gs</code>; read the reconcile panel in Grafana."),
        ("design", "Every core change goes through Git &mdash; by practice, not enforcement",
         "In this build, every change to the core is a commit in the repo's history; I didn't run <code>kubectl apply</code> for core config. That's how I worked, not a lock: the Applications don't forbid a manual edit, so I'm stating the practice rather than claiming it couldn't happen.",
         "Reviewed the repo history against the changes made. No admission policy enforces it."),
        ("design", "The metric pipeline works; traffic was never tested",
         "The AMF and UPF session panels read 0 because no device registered. The dashboards prove metrics flow from the functions to Grafana, not that the core carries sessions.",
         "No gNB or UE simulator was attached."),
    ],
    proof_note="From the running cluster",
    shots=[
        dict(raw="kubernetes/gitops-5g-core/Screenshots/Screenshot from 2026-09-16 01-18-50.png", alt="ArgoCD application tiles: observability, open5gs-cr and open5gs-operator all Healthy and Synced", cap="All three Applications Healthy and Synced."),
        dict(raw="kubernetes/gitops-5g-core/Screenshots/Screenshot from 2026-09-16 02-36-57.png", alt="open5gs-cr Synced to HEAD 5907f0e, Add URLLC network slice (SST 2, SD 0x222222)", cap="The slice change synced to <code>5907f0e</code>."),
        dict(raw="kubernetes/gitops-5g-core/Screenshots/Screenshot from 2026-09-16 02-09-02.png", alt="Prometheus target health filtered to open5gs: AMF, PCF and UPF ServiceMonitor targets UP", cap="AMF, PCF and UPF targets UP."),
        dict(raw="kubernetes/gitops-5g-core/Screenshots/Screenshot from 2026-09-16 21-53-25.png", alt="Grafana dashboard with CPU and memory per pod, AMF and UPF stats, pod restarts, and operator reconcile activity", cap="NF resources next to Operator reconcile activity."),
    ],
    broke=[
        ("<code>ImagePullBackOff</code> on the Operator",
         "Chart <code>1.0.5</code> pulled <code>kube-rbac-proxy</code> from <code>gcr.io/kubebuilder</code>, a registry path that has been retired. The first fix overrode the image to <code>quay.io/brancz/kube-rbac-proxy:v0.18.1</code> in the Application's Helm values. Moving to chart <code>1.0.7</code> made the override unnecessary, so it came back out."),
        ("Permanently OutOfSync while every pod was healthy",
         "The custom resource set <code>serviceMonitor: true</code> at the top of <code>spec</code>. The CRD has no such field there &mdash; it's per network function &mdash; so the API server's structural-schema pruning silently dropped it on every apply. Git always had a field the live object never kept, and ArgoCD kept reporting drift. Moving the flag under <code>amf:</code>, <code>pcf:</code> and <code>upf:</code> fixed the drift and turned the scrape targets on. Most of the three hours went here."),
        ("The Application pointed at a placeholder repo",
         "The first <code>open5gs-cr</code> Application still said <code>YOURUSER/telco-gitops.git</code> and targeted <code>base/</code> directly, while <code>overlays/local</code> listed raw YAML files instead of Kustomize bases. The restructure (<code>3b06c11</code>) pointed it at the real repo and the overlay, and turned each base into a proper Kustomization."),
    ],
    source="The three ArgoCD <code>Application</code> manifests in <code>apps/</code>, the <code>Open5GS</code> custom resource with both slices, the <code>Open5GSUser</code> subscriber, the Operator-metrics <code>ServiceMonitor</code> and <code>ClusterRoleBinding</code>, and the <code>overlays/local</code> Kustomization live here: <a href=\"https://github.com/kingswanzy2020/telco-platform-gitops\">kingswanzy2020/telco-platform-gitops</a>.",
    clone="git clone https://github.com/kingswanzy2020/telco-platform-gitops.git",
    stack="GitOps &middot; ArgoCD &middot; Kubernetes Operators &middot; custom resources &middot; Open5GS &middot; 5G standalone core &middot; network slicing &middot; Kustomize &middot; Helm &middot; Prometheus &middot; ServiceMonitors &middot; kube-rbac-proxy &middot; Grafana &middot; CRD schema debugging",
),
]

def lab_status(rebuild):
    return ("I built this in my own AWS account as a guided NextWork lab. I'm not pointing you at a live endpoint &mdash; "
            "the screenshots below were captured during the build, and " + rebuild + " Everything below is in the past tense for that reason.")


PAGES += [
# ======================================================================
dict(
    slug="eks-cluster-launch",
    card=dict(group="k8s", eyebrow="Kubernetes / AWS", color="c-aws", status="Guided lab",
              title="Launching an EKS cluster with eksctl",
              desc="One command, two CloudFormation stacks, three nodes &mdash; then I terminated the nodes to watch them come back."),
    title_tag="Launch an EKS Cluster",
    meta="Case study: an Amazon EKS cluster created with eksctl through CloudFormation, an IAM access entry mapped into Kubernetes RBAC, and worker nodes deleted on purpose to watch them replaced.",
    eyebrow="Kubernetes / AWS",
    h1="Launching an Amazon EKS cluster with eksctl",
    standfirst="I created a managed Kubernetes cluster on Amazon EKS with one <code>eksctl</code> command, mapped my IAM user into Kubernetes RBAC with an access entry, then terminated the worker nodes on purpose to watch the node group put them back.",
    chip="Guided lab",
    status=lab_status("the one <code>eksctl create cluster</code> command shown below recreates the cluster and both CloudFormation stacks."),
    spec=[("Platform", "Amazon EKS, Kubernetes 1.33"), ("Provisioned by", "eksctl &rarr; 2 CloudFormation stacks"),
          ("Nodes", "3 &times; t3.micro, min 1 / max 3"), ("Region", "ap-northeast-1, 3 AZs"),
          ("Access", "IAM access entry &rarr; RBAC"), ("Run from", "an EC2 admin instance")],
    summary="From an EC2 instance I used as an admin box, I ran <code>eksctl create cluster</code> with the cluster name, a node group of three <code>t3.micro</code> nodes (minimum 1, maximum 3), Kubernetes <code>1.33</code> and the <code>ap-northeast-1</code> region. eksctl handed that to CloudFormation as two stacks: one for the control plane and its VPC networking, one for the node group. The EKS console wouldn't show me the nodes until I added an IAM access entry mapping my IAM user to <code>AmazonEKSClusterAdminPolicy</code>. Then I terminated node instances directly in EC2 and watched replacements launch.",
    how=[
        ("Why <code>eksctl</code> instead of building the pieces by hand?", "A working cluster needs a control plane, a VPC with the right subnets and routes, IAM roles, and worker nodes that know how to join. <code>eksctl</code> takes one declarative command and turns it into CloudFormation stacks, so every resource it made is traceable to a stack and deletable with it."),
        ("Why two stacks?", "The cluster stack holds the control plane and the networking the pods and nodes need to talk to each other. The node group stack holds the EC2 instances that actually run pods. Keeping them separate means the node group can be changed or replaced without touching the control plane."),
        ("Why did I need an access entry when I already had an AWS admin login?", "Kubernetes has its own permission model. Being allowed to call the EKS API doesn't make my IAM user a Kubernetes user. An access entry maps the IAM identity into the cluster's RBAC; with <code>AmazonEKSClusterAdminPolicy</code> attached, the console could finally list the nodes."),
        ("What actually replaced the nodes I deleted?", "The node group's desired size was three. When I terminated instances in EC2, the gap between desired and actual showed up and the node group's Auto Scaling group launched replacements, which joined the cluster on their own. That's the same desired-state idea Kubernetes uses for pods, applied one level down to the machines."),
    ],
    diagram=dict(
        h=480,
        aria="An engineer connects over SSH to an EC2 admin instance and runs eksctl, which creates two CloudFormation stacks. The cluster stack creates the EKS control plane and VPC; the node group stack creates three t3.micro nodes that join the control plane. An IAM access entry maps the engineer's IAM user into RBAC, and the node group's Auto Scaling group replaces terminated nodes.",
        boxes=[dict(x=390, y=60, w=838, h=390, k="aws", label="AWS ACCOUNT — ap-northeast-1 · CLOUDFORMATION · EKS · EC2 · IAM")],
        nodes=[
            dict(id="eng", x=16, y=200, w=136, k="neu", icon="user", slot="engineer", t="Engineer", s="IAM user", tag="SSH key"),
            dict(id="adm", x=192, y=200, w=170, k="aws", icon="terminal", slot="ec2", t="Admin EC2", s="runs eksctl", tag="needed an IAM role"),
            dict(id="cfa", x=414, y=110, w=200, k="aws", icon="doc", slot="cloudformation", t="Cluster stack", s="control plane + VPC", tag="CloudFormation"),
            dict(id="cfb", x=414, y=300, w=200, k="aws", icon="doc", slot="cloudformation", t="Node group stack", s="worker instances", tag="CREATE_COMPLETE"),
            dict(id="cp", x=674, y=110, w=200, k="ctl", icon="ctl", slot="eks", t="EKS control plane", s="Kubernetes 1.33", tag="managed by AWS"),
            dict(id="ae", x=944, y=110, w=246, k="aws", icon="key", slot="iam", t="IAM access entry", s="my IAM user → RBAC", tag="AmazonEKSClusterAdminPolicy"),
            dict(id="ng", x=674, y=300, w=200, k="app", icon="server", slot="ec2", t="Node group", s="3 × t3.micro · 3 AZs", tag="desired 3 · 1–3"),
            dict(id="asg", x=944, y=300, w=246, k="aws", icon="cycle", slot="ec2", t="Auto Scaling group", s="behind the node group", tag="replaces lost nodes"),
        ],
        edges=[
            dict(**{"from": "eng", "to": "adm"}, k="neu", mech="SSH", what="I ran everything from this instance rather than my laptop."),
            dict(**{"from": "adm", "to": "cfa"}, k="aws", ss="t", ts="l", mech="eksctl create cluster", what="Name, region, version and node group in one command; eksctl writes the stacks."),
            dict(**{"from": "adm", "to": "cfb"}, k="aws", ss="b", ts="l", mech="eksctl", what="The second stack, for the node group."),
            dict(**{"from": "cfa", "to": "cp"}, k="aws", mech="stack resources", what="The control plane and the VPC resources pods and nodes communicate over."),
            dict(**{"from": "cfb", "to": "ng"}, k="aws", mech="stack resources", what="Three <code>t3.micro</code> instances across three Availability Zones."),
            dict(**{"from": "ng", "to": "cp"}, k="ctl", mech="kubelet join", what="Each node registers with the control plane and shows <code>Ready</code>."),
            dict(**{"from": "ae", "to": "cp"}, k="ctl", mech="access entry", what="Maps my IAM user to cluster-admin in RBAC, which is what made the nodes visible in the console."),
            dict(**{"from": "asg", "to": "ng"}, k="app", mech="desired capacity", what="Terminated instances are replaced to get back to three."),
        ],
    ),
    figcaption="The cluster as eksctl built it. Arrows 2 through 5 are one command turned into two CloudFormation stacks; arrow 8 is the part I tested by breaking it &mdash; I terminated nodes and the Auto Scaling group put the count back.",
    legend=[("c-neu", "Human actor", "me, over SSH"), ("c-aws", "AWS-managed", "EC2, CloudFormation, IAM, Auto Scaling"),
            ("c-ctl", "Kubernetes control plane", "managed by EKS"), ("c-app", "Workers", "the node group"),
            ("line:c-aws", "Provisioning", "eksctl through CloudFormation"), ("line:c-ctl", "Cluster membership", "join and RBAC"),
            ("line:c-app", "Self-healing", "desired vs actual nodes")],
    reach=[("Public", "the EKS API endpoint, behind IAM authentication. No workloads were exposed."),
           ("Internal", "the three worker nodes, inside the VPC the cluster stack created."),
           ("Access", "my IAM user only, through the access entry; nothing shared.")],
    ledger=[
        ("measured", "Terminated nodes were replaced without me doing anything",
         "I terminated node-group instances directly in the EC2 console. The instance list then showed the terminated ones next to new instances already <code>Running</code> with their status checks passed, back at three &mdash; the node group's desired size.",
         "Terminated instances in EC2, then watched the instance list until the replacements were <code>Running</code>."),
        ("observed", "One command produced both stacks and a three-node cluster",
         "The node group stack reached <code>CREATE_COMPLETE</code>, and the EKS console showed <code>nextwork-eks-cluster</code> on Kubernetes 1.33 with three nodes, all <code>Ready</code>. It took about an hour including setup and reading, which is mostly waiting on CloudFormation.",
         "Read the CloudFormation stack status and the cluster's Compute tab."),
        ("observed", "The console couldn't see the nodes until the access entry existed",
         "Before the access entry, the EKS console wouldn't show node details even though I was signed in as an AWS admin. After mapping my IAM user to <code>AmazonEKSClusterAdminPolicy</code>, the nodes appeared.",
         "Checked the Compute tab before and after creating the access entry."),
        ("design", "Every resource is traceable to a stack",
         "Because eksctl went through CloudFormation, the VPC, the roles and the instances all belong to one of two stacks and go away with them. I'm stating that from how the stacks are built; I didn't audit every resource against the stack lists.",
         "Reviewed the two stacks' resource lists at a high level."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(raw="kubernetes/launch-kubernetes-cluster/Screenshots/Screenshot from 2026-01-08 06-50-29.png", alt="Terminal on the admin EC2 instance: eksctl create cluster command failing with eksctl: command not found", cap="The first attempt: <code>eksctl: command not found</code>."),
        dict(raw="kubernetes/launch-kubernetes-cluster/Screenshots/Screenshot from 2026-01-08 07-54-22.png", alt="CloudFormation stacks list showing the eksctl node group stack in CREATE_COMPLETE", cap="The node group stack at <code>CREATE_COMPLETE</code>."),
        dict(raw="kubernetes/launch-kubernetes-cluster/Screenshots/Screenshot from 2026-01-08 08-28-14.png", alt="EKS console: nextwork-eks-cluster active on Kubernetes 1.33 with three nodes Ready and the access entry created", cap="The cluster on 1.33, three nodes <code>Ready</code>, access entry created."),
        dict(raw="kubernetes/launch-kubernetes-cluster/Screenshots/Screenshot from 2026-01-08 08-59-31.png", alt="EC2 instances list with terminated node instances alongside replacement instances running", cap="Terminated nodes next to their running replacements."),
    ],
    broke=[
        ("<code>eksctl: command not found</code>, then no permission to use it",
         "The first <code>eksctl create cluster</code> failed because the tool simply wasn't installed on the admin instance. Once it was, the next run failed because the instance had no credentials allowed to create an EKS cluster. Two failures, neither of them Kubernetes &mdash; the tool and the identity running it have to exist before any of the interesting parts can."),
    ],
    source="This was a guided lab, so there's no standalone repo; the write-up and the NextWork documentation with every step live in my portfolio repo: <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/kubernetes/launch-kubernetes-cluster\">Projects/kubernetes/launch-kubernetes-cluster</a>.",
    clone="eksctl create cluster --name nextwork-eks-cluster \\\n  --nodegroup-name nextwork-nodegroup --node-type t3.micro \\\n  --nodes 3 --nodes-min 1 --nodes-max 3 \\\n  --version 1.33 --region ap-northeast-1",
    stack="Amazon EKS &middot; eksctl &middot; CloudFormation &middot; managed node groups &middot; EC2 Auto Scaling &middot; IAM access entries &middot; Kubernetes RBAC &middot; EC2",
),
# ======================================================================
dict(
    slug="eks-backend-image",
    card=dict(group="k8s", eyebrow="Kubernetes / AWS", color="c-aws", status="Guided lab",
              title="Packaging a backend for EKS with ECR",
              desc="A Flask API cloned, built and pushed to a private ECR repository &mdash; and the Docker permission fix done properly instead of with sudo."),
    title_tag="Backend Image for EKS",
    meta="Case study: a Flask backend that proxies the Hacker News API, built into a Docker image on EC2 and pushed to a private Amazon ECR repository for an EKS cluster.",
    eyebrow="Kubernetes / AWS",
    h1="Packaging a backend for Amazon EKS with a private ECR registry",
    standfirst="I rebuilt the EKS cluster with <code>eksctl</code>, cloned a Flask backend that proxies the Hacker News API, built it into a Docker image on EC2, and pushed it to a private Amazon ECR repository the cluster could pull from.",
    chip="Guided lab",
    status=lab_status("<code>eksctl</code>, the backend's <code>Dockerfile</code> and three ECR push commands rebuild it from an empty account."),
    spec=[("Cluster", "Amazon EKS via eksctl"), ("App", "Flask API over Hacker News"),
          ("Build host", "EC2, Amazon Linux"), ("Base image", "python:3.9-alpine"),
          ("Registry", "private Amazon ECR"), ("End to end", "about 1.5 hours")],
    summary="This was part two of the EKS series. I created the cluster again with <code>eksctl</code>, then cloned <code>nextwork-flask-backend</code> onto the EC2 instance. The backend takes a search query, calls the Hacker News API, formats the result as JSON and returns it. I built it with the project's <code>Dockerfile</code>, created a private ECR repository, authenticated Docker to it and pushed the image as <code>latest</code>, so the cluster had a trusted, private source to pull from instead of a public registry.",
    how=[
        ("Why ECR instead of Docker Hub?", "ECR is private by default, access is controlled with the same IAM the cluster already uses, and it keeps multiple tags of the same image. For a cluster on EKS that means the nodes pull from a registry in the same account, with no public image dependency in the path."),
        ("Why add <code>ec2-user</code> to the <code>docker</code> group instead of using <code>sudo</code>?", "The Docker daemon runs as root, so <code>ec2-user</code> got a permission error on the first build. Prefixing every command with <code>sudo</code> works, but it means running the whole Docker CLI as root forever. <code>sudo usermod -aG docker ec2-user</code> gives the user permanent access through the group the daemon's socket already trusts."),
        ("What's actually in the backend?", "Three files matter: <code>requirements.txt</code> lists the dependencies, the <code>Dockerfile</code> uses <code>FROM</code>, <code>WORKDIR</code>, <code>COPY</code>, <code>RUN</code> and <code>CMD</code> to build on <code>python:3.9-alpine</code>, and <code>app.py</code> is the API that calls Hacker News and returns JSON."),
    ],
    diagram=dict(
        h=440,
        aria="An engineer connects to an EC2 build host, which clones the backend from GitHub, builds a Docker image and pushes it to a private ECR repository. The host also runs eksctl, which creates the EKS cluster through CloudFormation. The cluster is set up to pull the image from ECR.",
        boxes=[dict(x=380, y=60, w=848, h=350, k="aws", label="AWS ACCOUNT — EC2 · ECR · CLOUDFORMATION · EKS")],
        nodes=[
            dict(id="eng", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Engineer", s="SSH", tag="build host"),
            dict(id="gh", x=192, y=280, w=170, k="ctl", icon="git", slot="github", t="GitHub", s="nextwork-flask-backend", tag="source"),
            dict(id="ec2", x=404, y=110, w=200, k="aws", icon="terminal", slot="ec2", t="EC2 build host", s="git · docker · eksctl", tag="ec2-user in docker group"),
            dict(id="img", x=404, y=280, w=200, k="app", icon="box", slot="docker", t="Backend image", s="python:3.9-alpine", tag="Flask API"),
            dict(id="ecr", x=680, y=280, w=200, k="aws", icon="box", slot="ecr", t="Amazon ECR", s="nextwork-flask-backend", tag="private · :latest"),
            dict(id="cfn", x=680, y=110, w=200, k="aws", icon="doc", slot="cloudformation", t="CloudFormation", s="cluster + node group", tag="from eksctl"),
            dict(id="eks", x=960, y=110, w=230, k="ctl", icon="ctl", slot="eks", t="EKS cluster", s="node group", tag="pulls from ECR"),
        ],
        edges=[
            dict(**{"from": "eng", "to": "ec2"}, k="neu", mech="SSH", what="Everything ran on the build host."),
            dict(**{"from": "gh", "to": "ec2"}, k="ctl", ss="t", ts="l", to_off=18, mech="git clone", what="The backend repo, cloned onto the instance."),
            dict(**{"from": "ec2", "to": "img"}, k="app", mech="docker build", what="Built from the project's <code>Dockerfile</code> once <code>ec2-user</code> could reach the daemon."),
            dict(**{"from": "img", "to": "ecr"}, k="app", mech="docker push", what="After <code>aws ecr get-login-password</code> piped into <code>docker login</code>."),
            dict(**{"from": "ec2", "to": "cfn"}, k="aws", mech="eksctl create cluster", what="The same one-command cluster as part one, faster the second time."),
            dict(**{"from": "cfn", "to": "eks"}, k="aws", mech="stack resources", what="Control plane, VPC and node group."),
            dict(**{"from": "ecr", "to": "eks"}, k="data", ss="r", ts="b", dash=True, mech="image pull", what="The registry the cluster pulls from &mdash; set up here; the Kubernetes deployment itself wasn't captured in this part."),
        ],
    ),
    figcaption="Part two as it ran. Arrows 3 and 4 are the supply chain: build on a host I control, push to a registry only my account can read. Arrow 7 is dashed because this part stopped at the push &mdash; the pull is what the registry is for, not something I recorded here.",
    legend=[("c-neu", "Human actor", "me, over SSH"), ("c-ctl", "Source &amp; cluster", "GitHub, EKS"),
            ("c-aws", "AWS-managed", "EC2, ECR, CloudFormation"), ("c-app", "The artifact", "the backend image"),
            ("line:c-app", "Build &amp; push", "image supply chain"), ("line:c-aws", "Provisioning", "eksctl"),
            ("line:dg-line:dashed", "Intended pull", "not recorded in this part")],
    reach=[("Public", "nothing from the app; the image never left a private registry."),
           ("Private", "the ECR repository, readable through IAM in my account."),
           ("Internal", "the EKS nodes, in the VPC eksctl created.")],
    ledger=[
        ("observed", "The image built and landed in a private ECR repository",
         "<code>docker build -t nextwork-flask-backend .</code> finished all five steps on <code>python:3.9-alpine</code>, and the ECR console showed the repository with one image tagged <code>latest</code>, about 40&nbsp;MB.",
         "Read the build output and the ECR repository's Images tab."),
        ("observed", "The Docker permission error was fixed at the group, not with <code>sudo</code>",
         "The first build failed because <code>ec2-user</code> couldn't talk to the Docker daemon. After <code>sudo usermod -aG docker ec2-user</code>, Docker commands ran as the normal user.",
         "Re-ran the build as <code>ec2-user</code> after the group change."),
        ("design", "The cluster pulls the image from ECR &mdash; not captured here",
         "The registry exists to be the cluster's image source, and ECR integrates with EKS through IAM. This part of the series ended at the push, so I'm not claiming a pod ran this image.",
         "No Kubernetes Deployment was recorded in this part."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(pdf="legendary-aws-compute-eks2/i-004.png", name="git-clone.jpg", alt="git clone of nextwork-flask-backend onto the EC2 instance", cap="Cloning the backend onto the build host."),
        dict(pdf="legendary-aws-compute-eks2/i-001.png", name="docker-build.jpg", alt="docker build output for nextwork-flask-backend finishing all five steps on python:3.9-alpine", cap="The image built from the project's <code>Dockerfile</code>."),
        dict(pdf="legendary-aws-compute-eks2/i-009.png", name="ecr-image.jpg", alt="Amazon ECR private repository nextwork-flask-backend with one image tagged latest", cap="The private ECR repository holding the <code>latest</code> image."),
    ],
    broke=[
        ("<code>docker build</code> refused to run as <code>ec2-user</code>",
         "The Docker daemon needs root-level access, and the default <code>ec2-user</code> doesn't have it, so the first build hit a permission error. <code>sudo</code> on every command would have worked and stayed wrong. Adding the user to the <code>docker</code> group fixed it permanently."),
    ],
    source="This was a guided lab using NextWork's sample backend, so there's no standalone repo; the write-up and documentation live in my portfolio repo: <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/kubernetes/kubernetes-deployment\">Projects/kubernetes/kubernetes-deployment</a>.",
    clone="aws ecr get-login-password --region &lt;region&gt; | docker login --username AWS --password-stdin &lt;account&gt;.dkr.ecr.&lt;region&gt;.amazonaws.com\ndocker build -t nextwork-flask-backend .\ndocker push &lt;account&gt;.dkr.ecr.&lt;region&gt;.amazonaws.com/nextwork-flask-backend:latest",
    stack="Amazon EKS &middot; eksctl &middot; Docker &middot; Amazon ECR &middot; EC2 &middot; Linux groups &amp; permissions &middot; Flask",
),
]
