NW = "https://learn.nextwork.org/thoughtful_white_zany_vampire/uploads/"
CH = "ci-cd/aws-devops-cicd-challenge/"


def lab_status(rebuild):
    return ("I built this in my own AWS account as a guided NextWork lab. I'm not pointing you at a live endpoint &mdash; "
            "the screenshots below were captured during the build, and " + rebuild + " Everything below is in the past tense for that reason.")


PAGES = [
# ======================================================================
dict(
    slug="jenkins-sonarqube",
    card=dict(group="cicd", eyebrow="CI/CD", color="c-ctl", status="Guided lab",
              title="Jenkins pipeline gated on SonarQube",
              desc="Build, test, analyse, then containerise only if the quality gate passes &mdash; with Slack told either way."),
    title_tag="Jenkins + SonarQube Pipeline",
    meta="Case study: a five-stage declarative Jenkins pipeline that builds, tests and analyses a Java app, blocks on a SonarQube quality gate, and only then builds and pushes a Docker image.",
    eyebrow="CI/CD",
    h1="A Jenkins pipeline that won't containerise code SonarQube rejects",
    standfirst="I built a five-stage declarative Jenkins pipeline that builds a Java app with Maven, runs its JUnit tests, sends it to SonarQube, and only builds and pushes a Docker image if the quality gate passes &mdash; telling Slack the result either way.",
    chip="Guided lab",
    status="I built this as a NextWork lab and then extended it. I'm not pointing you at a live Jenkins &mdash; the screenshots below are from the build, and the <code>Jenkinsfile</code> in the repo rebuilds the pipeline on any Jenkins wired to a SonarQube server, Docker Hub and Slack.",
    spec=[("CI server", "Jenkins, declarative pipeline"), ("Trigger", "GitHub webhook, no polling"),
          ("Build &amp; test", "Maven + JUnit"), ("Quality gate", "SonarQube, abortPipeline: true"),
          ("Artifact", "Docker image &rarr; Docker Hub"), ("Notify", "Slack, every run")],
    summary="A push to <a href=\"https://github.com/kingswanzy2020/cicd-pipeline-app\">cicd-pipeline-app</a> fires a GitHub webhook straight into Jenkins. The <code>Jenkinsfile</code> next to the code checks it out, builds it with Maven, runs the JUnit tests, and sends the code to SonarQube for static analysis. Jenkins then waits for SonarQube's verdict on the quality gate. Only a pass lets the next stage build the Docker image and push it to Docker Hub; a fail aborts the pipeline. JUnit results are published and Slack is notified whatever happened.",
    how=[
        ("Why does the pipeline live in a <code>Jenkinsfile</code>?", "Because then a change to the pipeline is a commit next to the code it builds, reviewed the same way. Nothing about how this project gets built lives only in the Jenkins UI."),
        ("Why make the quality gate abort the pipeline?", "A gate that only reports is a suggestion. Jenkins waits for SonarQube's webhook with the gate result, and with <code>abortPipeline: true</code> a failed gate stops the run before the Docker stage. Code that fails analysis never becomes an image, so it can't reach the registry by accident."),
        ("Why publish test results in <code>post { always }</code>?", "If JUnit publishing sits inside the test stage, a failing test can end the stage before its report is saved &mdash; and the run where tests failed is exactly the one whose report you need. In the <code>post { always }</code> block the reports are published on every run, pass or fail. Slack goes in the same place for the same reason."),
        ("Why did SonarQube need kernel settings?", "SonarQube embeds Elasticsearch, which needs more memory maps and file handles than a default Linux host allows. I set <code>vm.max_map_count=262144</code> and <code>fs.file-max=131072</code> before starting it. The SonarQube token and Docker Hub credentials live in Jenkins's credential store, not in the repo."),
    ],
    diagram=dict(
        h=600,
        aria="A developer pushes to GitHub, which sends a webhook to Jenkins. Inside the declarative pipeline, Maven builds, JUnit tests run, and the code is analysed by the SonarQube server, which returns a quality-gate verdict by webhook. On pass, the Docker stage builds and pushes to Docker Hub; on fail, the pipeline aborts. Slack is notified after every run.",
        boxes=[dict(x=384, y=60, w=626, h=362, k="ctl", label="JENKINS — DECLARATIVE PIPELINE FROM THE JENKINSFILE")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="git push", tag="code change"),
            dict(id="gh", x=192, y=110, w=160, k="ctl", icon="git", slot="github", t="GitHub", s="cicd-pipeline-app", tag="webhook"),
            dict(id="mvn", x=408, y=110, w=176, k="ctl", icon="gear", slot="maven", t="Maven build", s="checkout + build", tag="pom.xml"),
            dict(id="test", x=618, y=110, w=164, k="ctl", icon="gate", slot="junit", t="JUnit tests", s="unit tests", tag="reports always"),
            dict(id="scan", x=818, y=110, w=170, k="obs", icon="filter", slot="sonarqube", t="Sonar analysis", s="static analysis", tag="token in Jenkins"),
            dict(id="sq", x=1044, y=110, w=176, k="obs", icon="shield", slot="sonarqube", t="SonarQube", s="vm.max_map_count", tag="quality gate"),
            dict(id="gate", x=818, y=290, w=170, k="obs", icon="gate", slot="gate", t="Quality gate", s="waitForQualityGate", tag="abortPipeline"),
            dict(id="abort", x=818, y=480, w=170, k="neu", icon="x", slot="gate", t="Pipeline aborted", s="no image built", tag="on fail"),
            dict(id="dock", x=618, y=290, w=164, k="app", icon="box", slot="docker", t="Docker build", s="build + push", tag="on pass only"),
            dict(id="hub", x=618, y=480, w=164, k="neu", icon="box", slot="docker-hub", t="Docker Hub", s="creds in Jenkins", tag="registry"),
            dict(id="slack", x=408, y=480, w=176, k="neu", icon="chat", slot="slack", t="Slack", s="success and failure", tag="every run"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "gh"}, k="ctl", mech="git push", what="A change lands on the repository."),
            dict(**{"from": "gh", "to": "mvn"}, k="ctl", ft="GitHub &rarr; Jenkins", mech="webhook", what="Starts the pipeline immediately; nothing polls."),
            dict(**{"from": "mvn", "to": "test"}, k="ctl", mech="stage", what="Compiles and packages, then runs the unit tests."),
            dict(**{"from": "test", "to": "scan"}, k="ctl", mech="stage", what="Test reports are published in <code>post { always }</code>, pass or fail."),
            dict(**{"from": "scan", "to": "sq"}, k="obs", mech="analysis upload", what="Sends the code to SonarQube with a token from Jenkins's credential store."),
            dict(**{"from": "sq", "to": "gate"}, k="obs", dash=True, ss="b", ts="r", mech="webhook verdict", what="SonarQube calls back with the gate result; Jenkins waits for it."),
            dict(**{"from": "gate", "to": "dock"}, k="app", mech="pass", what="Only a passing gate lets the Docker stage run."),
            dict(**{"from": "gate", "to": "abort"}, k="neu", mech="fail", what="<code>abortPipeline: true</code> stops the run; nothing reaches the registry."),
            dict(**{"from": "dock", "to": "hub"}, k="app", mech="docker push", what="Pushes with Docker Hub credentials held by Jenkins."),
            dict(**{"from": "dock", "to": "slack"}, k="neu", dash=True, ss="l", ts="t", ft="Pipeline &rarr; Slack", mech="post block", what="A message on every run, success and failure alike."),
        ],
    ),
    figcaption="The pipeline as it ran. Arrows 6 through 8 are the point of it: SonarQube's verdict decides whether a Docker image ever gets built. Arrow 10 fires on every run, which is how I found out it worked &mdash; by breaking a test.",
    legend=[("c-neu", "People &amp; outside services", "developer, Docker Hub, Slack"), ("c-ctl", "Source &amp; build stages", "GitHub, Maven, JUnit"),
            ("c-obs", "Analysis &amp; gate", "SonarQube"), ("c-app", "Artifact", "the Docker stage"),
            ("line:c-ctl", "Pipeline flow", "stage to stage"), ("line:c-obs", "Analysis", "and its verdict"),
            ("line:c-app", "On pass", "build and push"), ("line:c-neu:dashed", "Notification", "every run")],
    reach_title="What it touched",
    reach=[("Inbound", "one GitHub webhook into Jenkins."),
           ("Outbound", "SonarQube for analysis, Docker Hub for the image, Slack for the result."),
           ("Secrets", "the SonarQube token and Docker Hub credentials, in Jenkins's credential store only.")],
    ledger_intro_obs="the pipeline runs",
    ledger=[
        ("measured", "A test I broke on purpose reached Slack as a failure",
         "I broke a unit test deliberately and pushed. The pipeline failed, the JUnit report for the failed run was still published, and the failure alert arrived in Slack. That's the end-to-end check for the notification path, not just the configuration.",
         "Pushed a deliberately failing test, then read the Jenkins run, its test report and the Slack channel."),
        ("observed", "All five stages went green, and the analysis showed up in SonarQube",
         "On a clean commit the stage view showed checkout, build, test, analysis and the Docker stage all passing, and the project appeared in SonarQube with its quality gate result.",
         "Read the stage view in Jenkins and the project page in SonarQube (screenshots below)."),
        ("design", "A failed quality gate stops the image from being built &mdash; not forced",
         "The gate step waits for SonarQube's webhook and runs with <code>abortPipeline: true</code>, which ends the pipeline before the Docker stage. I didn't commit code designed to fail the gate, so this is what the step guarantees rather than a block I watched happen.",
         "Reviewed the gate stage in the <code>Jenkinsfile</code>. Not tested with failing code."),
        ("design", "No credential lives in the repository",
         "The SonarQube token and Docker Hub login are referenced by ID from Jenkins's credential store. I didn't audit the history of every file, so this is a property of how the pipeline was written.",
         "Reviewed the <code>Jenkinsfile</code>'s credential references."),
    ],
    proof_note="From the pipeline run",
    shots=[
        dict(url=NW + "f485c924-e7b8-4fed-ae38-23e5b876e063_yz6yqauk", alt="Jenkins stage view with all five pipeline stages green", cap="All five stages green."),
        dict(url=NW + "f485c924-e7b8-4fed-ae38-23e5b876e063_97awyixy", alt="SonarQube project page showing the quality gate and analysis results", cap="The quality gate and analysis in SonarQube."),
    ],
    broke=[
        ("A test I broke on purpose, to find out who would hear about it",
         "The only way to know a failure notification works is to cause a failure. I broke a unit test and pushed it: the build went red, the test report was still published because it lives in <code>post { always }</code>, and Slack got the alert. Then I fixed the test."),
    ],
    source="The Java/Maven application and the <code>Jenkinsfile</code> whose quality gate runs with <code>abortPipeline: true</code> live here: <a href=\"https://github.com/kingswanzy2020/cicd-pipeline-app\">kingswanzy2020/cicd-pipeline-app</a>.",
    clone="git clone https://github.com/kingswanzy2020/cicd-pipeline-app.git",
    stack="Jenkins &middot; declarative pipelines &middot; SonarQube &middot; quality gates &middot; Maven &middot; JUnit &middot; Docker &middot; Docker Hub &middot; GitHub webhooks &middot; Slack notifications &middot; Linux kernel tuning",
),
# ======================================================================
dict(
    slug="aws-cicd-pipeline",
    card=dict(group="cicd", eyebrow="CI/CD / AWS", color="c-aws", status="Guided lab",
              title="A 7-day AWS-native CI/CD pipeline",
              desc="CodeArtifact, CodeBuild, CodeDeploy and CloudFormation, one per day, joined into CodePipeline &mdash; including a rollback I broke on purpose."),
    title_tag="7-Day AWS CI/CD Pipeline",
    meta="Case study: a Java web app delivered by an AWS-native pipeline built over seven days: CodePipeline, CodeBuild with CodeArtifact dependencies, S3 artifacts, CodeDeploy to EC2, and CloudFormation.",
    eyebrow="CI/CD / AWS",
    h1="A seven-day, AWS-native CI/CD pipeline for a Java web app",
    standfirst="Over seven consecutive days I built a delivery pipeline one AWS service at a time &mdash; CodeArtifact, CodeBuild, CodeDeploy, CloudFormation &mdash; and then joined them in CodePipeline, so a push to <code>main</code> ends with the change live on an EC2 web server.",
    chip="Guided lab",
    status=lab_status("the CloudFormation template, <code>buildspec.yml</code>, <code>appspec.yml</code> and the deployment scripts in the repo rebuild the pipeline and its web server."),
    spec=[("Orchestrator", "AWS CodePipeline, 3 stages"), ("Build", "CodeBuild, Maven, Corretto 8"),
          ("Dependencies", "CodeArtifact, cached from Maven Central"), ("Artifacts", "S3, WAR file"),
          ("Deploy", "CodeDeploy to EC2 (Tomcat + Apache)"), ("Infrastructure", "CloudFormation, 16 resources")],
    summary="The app is a Java web app I generated with Maven on an EC2 development instance and pushed to GitHub. CodePipeline listens for pushes to <code>main</code> through a CodeConnections webhook and runs three stages. Source zips the commit. Build hands it to CodeBuild, which runs <code>buildspec.yml</code>, pulls every dependency through a private CodeArtifact repository, and writes the WAR file to S3. Deploy hands that artifact to CodeDeploy, which runs <code>appspec.yml</code>'s lifecycle scripts on an EC2 web server in its own VPC. By day six the whole stack &mdash; CodeArtifact, CodeBuild, CodeDeploy, roles and connection &mdash; was a CloudFormation template.",
    how=[
        ("Why route dependencies through CodeArtifact?", "Maven reads <code>pom.xml</code>, and with <code>-s settings.xml</code> it asks CodeArtifact first. CodeArtifact serves what it has and fetches anything new from Maven Central once, then caches it. The build itself only ever talks to a private repository in my account, which needs an authorization token &mdash; and getting that token is where day three's first error came from."),
        ("Why a separate web server, built from a template?", "The development instance is where I change code; the web server is what users hit. Keeping them apart means editing one can't break the other. I created the web server's VPC, subnet, route table, internet gateway, security group and instance from CloudFormation, so it can be rebuilt or deleted as one stack."),
        ("Why lifecycle scripts?", "CodeDeploy doesn't know how to run a Java web app; <code>appspec.yml</code> tells it which scripts to run and when. <code>install_dependencies.sh</code> sets up Tomcat and Apache, <code>start_server.sh</code> starts both and enables them on boot, and <code>stop_server.sh</code> stops them cleanly. The CodeDeploy agent on the instance runs them in order."),
        ("Why does a rollback only touch the Deploy stage?", "When I rolled back from CodePipeline, Source and Build kept the newest commit and only Deploy went back to the previous one. The artifact for the old version is still in S3, so going back is a redeploy of a known build, not a rebuild."),
    ],
    diagram=dict(
        h=600,
        aria="A developer pushes to GitHub, which triggers CodePipeline through a webhook. The Build stage runs CodeBuild, which pulls dependencies through CodeArtifact (cached from Maven Central) and writes a WAR file to S3. The Deploy stage runs CodeDeploy, which takes the artifact from S3 and runs lifecycle scripts on the EC2 web server. CloudFormation provisions the pipeline resources and the web server's network.",
        boxes=[dict(x=384, y=60, w=844, h=520, k="aws", label="AWS ACCOUNT — CODEPIPELINE · CODEBUILD · CODEARTIFACT · CODEDEPLOY · S3 · EC2")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="dev EC2 + VS Code", tag="git push"),
            dict(id="gh", x=192, y=110, w=160, k="ctl", icon="git", slot="github", t="GitHub", s="nextwork-web-project", tag="main"),
            dict(id="cp", x=408, y=110, w=190, k="ctl", icon="cycle", slot="codepipeline", t="CodePipeline", s="Source → Build → Deploy", tag="superseded mode"),
            dict(id="cfn", x=1030, y=110, w=176, k="aws", icon="doc", slot="cloudformation", t="CloudFormation", s="pipeline + web server", tag="16 resources"),
            dict(id="cb", x=408, y=290, w=190, k="aws", icon="gear", slot="codebuild", t="CodeBuild", s="buildspec.yml · Maven", tag="logs to CloudWatch"),
            dict(id="s3", x=640, y=290, w=160, k="aws", icon="disk", slot="s3", t="S3 artifacts", s="WAR file", tag="versioned"),
            dict(id="cd", x=840, y=290, w=160, k="aws", icon="box", slot="codedeploy", t="CodeDeploy", s="appspec.yml hooks", tag="AllAtOnce"),
            dict(id="ec2", x=1030, y=290, w=176, k="app", icon="server", slot="ec2", t="EC2 web server", s="Tomcat + Apache", tag="role: webserver"),
            dict(id="ca", x=408, y=470, w=190, k="aws", icon="lock", slot="codeartifact", t="CodeArtifact", s="private repository", tag="12-hour token"),
            dict(id="mc", x=640, y=470, w=160, k="neu", icon="globe", slot="maven", t="Maven Central", s="upstream", tag="fetched once"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "gh"}, k="ctl", mech="git push", what="A code change to <code>main</code>; GitHub auth used a personal access token."),
            dict(**{"from": "gh", "to": "cp"}, k="ctl", mech="webhook", what="CodeConnections starts a pipeline execution on every push."),
            dict(**{"from": "cp", "to": "cb"}, k="ctl", mech="Build stage", what="Hands the zipped source to CodeBuild."),
            dict(**{"from": "cb", "to": "ca"}, k="aws", mech="mvn -s settings.xml", what="Every dependency comes through CodeArtifact, with a token CodeBuild's role is allowed to request."),
            dict(**{"from": "ca", "to": "mc"}, k="aws", dash=True, mech="upstream", what="Fetches anything new from Maven Central once, then serves it from cache."),
            dict(**{"from": "cb", "to": "s3"}, k="aws", mech="artifacts", what="Writes the WAR file plus the scripts and <code>appspec.yml</code> CodeDeploy needs."),
            dict(**{"from": "cp", "to": "cd"}, k="ctl", ss="r", ts="t", mech="Deploy stage", what="Starts a deployment with the build artifact; rollback on stage failure is enabled."),
            dict(**{"from": "s3", "to": "cd"}, k="aws", mech="revision", what="CodeDeploy fetches the artifact from its S3 revision location."),
            dict(**{"from": "cd", "to": "ec2"}, k="app", mech="agent + hooks", what="The agent runs install, start and stop scripts on instances tagged <code>role: webserver</code>."),
            dict(**{"from": "cfn", "to": "ec2"}, k="aws", dash=True, mech="stack", what="VPC, subnet, routes, internet gateway, security group and the instance itself."),
        ],
    ),
    figcaption="The pipeline at the end of day seven. Arrows 3 to 9 are what CodePipeline replaced: on days four and five I ran CodeBuild and CodeDeploy by hand. Arrow 4 is why no build step talks to a public registry directly &mdash; arrow 5 is the only place Maven Central appears.",
    legend=[("c-neu", "Outside AWS", "developer, Maven Central"), ("c-ctl", "Source &amp; orchestration", "GitHub, CodePipeline"),
            ("c-aws", "AWS-managed", "build, artifacts, deploy, IaC"), ("c-app", "Running app", "the web server"),
            ("line:c-ctl", "Pipeline stage", "source to deploy"), ("line:c-aws", "Service call", "build, fetch, store"),
            ("line:c-app", "Deployment", "scripts on the instance"), ("line:c-aws:dashed", "Provision / upstream", "not on the request path")],
    reach=[("Public", "the EC2 web server's DNS name, serving the Java app over HTTP."),
           ("Private", "CodeArtifact, the S3 artifact bucket, and the pipeline's roles."),
           ("Inbound", "GitHub's webhook into CodePipeline.")],
    ledger_intro_obs="the pipeline and the AWS console",
    ledger=[
        ("measured", "A push went from GitHub to the live page with no manual step",
         "I changed the app's source and pushed to <code>main</code>. The webhook started a new execution, Source, Build and Deploy all went green, each stage showing the same commit message, and the new line was on the live page when I reloaded it.",
         "Pushed a visible change, watched the execution in CodePipeline, then loaded the web server's public DNS name."),
        ("measured", "Rolling back the Deploy stage restored the previous page and left Source and Build alone",
         "I started a rollback on the Deploy stage. Afterwards Source and Build still showed the latest commit while Deploy showed the previous one, and the live app was back to its earlier text.",
         "Compared each stage's commit message after the rollback, then reloaded the live page."),
        ("measured", "A deliberately broken stop script took the automatic rollback down with it",
         "On day five I put <code>systemctll</code> in <code>stop_server.sh</code> with rollbacks enabled. The deployment failed with <code>systemctll: command not found</code> &mdash; and so did the automatic rollback, because rolling back starts by running the same broken stop script. Recovery meant fixing the script and deploying a new revision myself.",
         "Deployed the broken script and read the deployment history: the failed deployment and the failed rollback."),
        ("observed", "The whole stack came up from one CloudFormation template",
         "After two failed attempts (below), the <code>nextwork-devops-stack</code> stack showed all 16 resources &mdash; CodeArtifact domain and repositories, CodeBuild project, CodeDeploy application and deployment group, the GitHub connection, roles and policies &mdash; at <code>CREATE_COMPLETE</code>.",
         "Read the stack's Resources tab."),
        ("design", "Builds never fetch directly from a public registry",
         "<code>settings.xml</code> points Maven at CodeArtifact, and CodeArtifact is the one that reaches Maven Central. I didn't block outbound traffic from CodeBuild to prove nothing else is contacted.",
         "Reviewed <code>settings.xml</code> and the CodeArtifact upstream configuration."),
    ],
    proof_note="From the pipeline and the AWS console",
    shots=[
        dict(raw=CH + "Day 4- Continuous Integration with CodeBuild/Screenshots/Screenshot from 2025-12-03 10-22-26.png", alt="CodeBuild phase details with BUILD and POST_BUILD failed on COMMAND_EXECUTION_ERROR for mvn -s settings.xml", cap="Day four: <code>COMMAND_EXECUTION_ERROR</code> &mdash; CodeBuild couldn't reach CodeArtifact."),
        dict(raw=CH + "Day 6-Infrastructure as Code with CloudFormation/Screenshots/Screenshot from 2025-12-31 05-42-39.png", alt="CloudFormation template upload error: Circular dependency between IAM managed policies and roles", cap="Day six: the circular dependency between roles and policies."),
        dict(raw=CH + "Day 6-Infrastructure as Code with CloudFormation/Screenshots/Screenshot from 2025-12-31 09-51-23.png", alt="CloudFormation nextwork-devops-stack resources all CREATE_COMPLETE", cap="The stack's resources at <code>CREATE_COMPLETE</code>."),
        dict(raw=CH + "Day 5-Deploy a Web App with CodeDeploy/Screenshots/Screenshot from 2025-12-16 21-33-05.png", alt="CodeDeploy deployment history with failed and succeeded in-place deployments", cap="Day five's deployment history, including the broken-script failures."),
        dict(raw="ci-cd/aws-devops-cicd-challenge/Day 7- Build a CI_CD Pipeline with AWS/Screenshots/Screenshot from 2026-01-03 05-28-33.png", alt="CodePipeline execution with Source, Build and Deploy all succeeded", cap="Day seven: Source, Build and Deploy all green."),
        dict(raw="ci-cd/aws-devops-cicd-challenge/Day 7- Build a CI_CD Pipeline with AWS/Screenshots/Screenshot from 2026-01-03 07-57-15.png", alt="CodePipeline Deploy stage marked Rollback with all actions succeeded", cap="The Deploy stage after a rollback."),
    ],
    broke=[
        ("Two failed builds before CodeBuild produced anything",
         "The first build failed because there was no <code>buildspec.yml</code> &mdash; CodeBuild had no instructions at all. The second failed with <code>COMMAND_EXECUTION_ERROR</code>: CodeBuild had the <code>settings.xml</code> pointing at CodeArtifact but no permission to use it, so Maven couldn't resolve a single dependency. Adding an IAM policy for CodeArtifact to CodeBuild's role turned the third build green. Day three had the same shape: the EC2 instance couldn't get a CodeArtifact token until I gave it a role that could."),
        ("CloudFormation failed on ordering, then on a circular dependency",
         "My first stack failed because roles and their policies were being created at the same time; a policy needs its role first. I added <code>DependsOn</code>. The second attempt failed with <code>Circular dependency between resources</code>: the roles listed the policies in <code>ManagedPolicyArns</code> while the policies depended on the roles. Removing those references from the roles let CloudFormation create each role, then attach its policies."),
        ("A rollback can't save you from the script it has to run",
         "With the typo in <code>stop_server.sh</code>, the deployment failed and the automatic rollback failed for the same reason &mdash; it begins by stopping the server with the broken script. The lesson I took from it: rollback protects you from a bad application build, not from broken deployment plumbing."),
    ],
    broke_note="Three failures worth keeping",
    source="The Java web app, <code>buildspec.yml</code>, <code>appspec.yml</code>, the CodeDeploy lifecycle scripts and the CloudFormation templates live here: <a href=\"https://github.com/kingswanzy2020/nextwork-web-project\">kingswanzy2020/nextwork-web-project</a>. The day-by-day log is in <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/ci-cd/aws-devops-cicd-challenge\">Projects/ci-cd/aws-devops-cicd-challenge</a>.",
    clone="git clone https://github.com/kingswanzy2020/nextwork-web-project.git",
    stack="AWS CodePipeline &middot; CodeBuild &middot; CodeArtifact &middot; CodeDeploy &middot; CloudFormation &middot; CodeConnections &middot; S3 &middot; EC2 &middot; IAM roles &amp; policies &middot; CloudWatch Logs &middot; Java / Maven &middot; Tomcat &middot; Apache",
),
# ======================================================================
dict(
    slug="rag-semantic-ci",
    card=dict(group="cicd", eyebrow="CI/CD / AI", color="c-ctl", status="CI workflow",
              title="Semantic tests for a RAG API in GitHub Actions",
              desc="CI that fails when the knowledge base degrades, not just when the code does &mdash; made deterministic with a mock LLM mode."),
    title_tag="Semantic CI for a RAG API",
    meta="Case study: a GitHub Actions workflow that re-embeds a RAG API's knowledge base and runs deterministic semantic tests against its retrieval layer on every relevant push.",
    eyebrow="CI/CD / AI",
    h1="Catching knowledge-base regressions in CI for a RAG API",
    standfirst="I wrote a GitHub Actions workflow that rebuilds a RAG API's embeddings and runs semantic tests against what it retrieves, so a push that quietly degrades the knowledge base fails the build &mdash; and made those tests deterministic by taking the LLM out of them.",
    chip="CI workflow",
    status="This isn't a hosted service. It's a workflow file in the repo that runs on GitHub's own runners whenever the knowledge base, <code>app.py</code> or the embedding script changes. Everything below describes the runs I triggered while building it.",
    spec=[("CI", "GitHub Actions, ubuntu runner"), ("Trigger", "push touching docs/, app.py, embed"),
          ("App", "FastAPI RAG over Chroma"), ("LLM in CI", "none &mdash; mock mode"),
          ("Tests", "keywords in retrieved context"), ("Locally", "Ollama, tinyllama")],
    summary="The RAG API retrieves context from a Chroma vector store and asks a local model to answer with it. Ordinary unit tests can't protect that: the code can stay correct while the answers get worse because someone edited a document. The workflow re-embeds every document in <code>docs/</code>, starts the API in mock LLM mode &mdash; which returns the raw retrieved context instead of a generated answer &mdash; and asserts that known queries still retrieve their expected keywords. A missing keyword fails the build.",
    how=[
        ("Why take the LLM out of the tests?", "Because it made the tests lie. I removed the word \"orchestration\" from the knowledge base and kept seeing it in generated answers anyway &mdash; the model already knows what Kubernetes is. A test that checks generated text can pass on a broken knowledge base. Mock mode (<code>USE_MOCK_LLM</code>) returns exactly what was retrieved, so the same query gives the same result every run and a missing keyword really means it wasn't retrieved."),
        ("Why test retrieval rather than code?", "In a RAG system the data is part of the product. Semantic tests check that a known question still pulls back the context it should, which is a data-quality check, not a logic check."),
        ("Why re-embed in CI instead of committing the vectors?", "The test has to run against what the documents say now. The workflow runs the embedding script on every run, so an edited document changes the vectors the tests query. When the knowledge base grew to several files, I moved them into <code>docs/</code> and switched to <code>embed_docs.py</code>, which embeds the whole folder."),
        ("Why a path filter?", "The workflow only has something to say when the knowledge base, <code>app.py</code> or the embedding code changes, so those paths are what trigger it."),
    ],
    diagram=dict(
        h=500,
        aria="A developer pushes a change to the knowledge base to GitHub. The GitHub Actions workflow installs dependencies, rebuilds the embeddings into Chroma, starts the FastAPI app in mock LLM mode, and runs semantic tests against the retrieved context. A pass marks the build green; a missing keyword fails it. Locally, the same API uses Ollama with tinyllama.",
        boxes=[dict(x=384, y=60, w=844, h=290, k="ctl", label="GITHUB ACTIONS — test-and-build · ubuntu-latest")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="edits docs/", tag="git push"),
            dict(id="gh", x=192, y=110, w=160, k="ctl", icon="git", slot="github", t="GitHub", s="nextwork-rag-api", tag="path filter"),
            dict(id="emb", x=408, y=110, w=190, k="ctl", icon="cycle", slot="python", t="Rebuild embeddings", s="embed_docs.py", tag="every run"),
            dict(id="chroma", x=408, y=250, w=190, k="app", icon="db", slot="chroma", t="Chroma", s="vectors from docs/", tag="fresh each run"),
            dict(id="api", x=640, y=110, w=176, k="app", icon="code", slot="fastapi", t="RAG API", s="USE_MOCK_LLM", tag="returns raw context"),
            dict(id="test", x=860, y=110, w=176, k="obs", icon="gate", slot="assert", t="Semantic tests", s="semantic_test.py", tag="expected keywords"),
            dict(id="pass", x=1062, y=110, w=154, k="app", icon="gate", slot="gate", t="Build green", s="retrieval verified", tag="pass"),
            dict(id="fail", x=1062, y=250, w=154, k="neu", icon="x", slot="gate", t="Build failed", s="AssertionError", tag="missing keyword"),
            dict(id="ollama", x=640, y=400, w=176, k="neu", icon="ai", slot="ollama", t="Ollama · tinyllama", s="local runs only", tag="not in CI"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "gh"}, k="ctl", mech="git push", what="A change to the knowledge base, <code>app.py</code> or the embedding script."),
            dict(**{"from": "gh", "to": "emb"}, k="ctl", ft="GitHub &rarr; workflow", mech="on: push (paths)", what="Checkout, set up Python, install dependencies, then the steps below."),
            dict(**{"from": "emb", "to": "chroma"}, k="app", mech="write vectors", what="Re-embeds every file in <code>docs/</code>."),
            dict(**{"from": "api", "to": "chroma"}, k="data", ss="b", ts="r", so=-40, mech="similarity search", what="The API retrieves context for each test query."),
            dict(**{"from": "emb", "to": "api"}, k="ctl", mech="start API", what="Started in mock mode, so no model runs in CI."),
            dict(**{"from": "api", "to": "test"}, k="obs", mech="POST /query", what="Returns the raw retrieved context, the same every run."),
            dict(**{"from": "test", "to": "pass"}, k="app", mech="all keywords found", what="Retrieval quality verified for every query."),
            dict(**{"from": "test", "to": "fail"}, k="neu", ss="b", ts="l", mech="keyword missing", what="Fails the job, e.g. <code>Missing 'orchestration' keyword</code>."),
            dict(**{"from": "api", "to": "ollama"}, k="neu", dash=True, so=30, to_off=30, mech="local only", what="Generates real answers on my machine; skipped in CI because it isn't deterministic."),
        ],
    ),
    figcaption="The workflow as it ran. Arrow 9 is dashed on purpose: the model is the part I took out of CI, because a test that reads generated text passed even after I'd removed the fact it was checking for.",
    legend=[("c-neu", "Outside the test path", "developer, Ollama, the failure"), ("c-ctl", "Source &amp; workflow steps", "GitHub, embedding, startup"),
            ("c-app", "System under test", "Chroma and the RAG API"), ("c-obs", "The tests", "semantic assertions"),
            ("line:c-ctl", "Workflow flow", "step to step"), ("line:c-obs", "Test query", "against retrieval"),
            ("line:dg-line", "Retrieval", "vector search"), ("line:c-neu:dashed", "Local only", "never in CI")],
    reach_title="What it touches",
    reach=[("Runs on", "GitHub-hosted <code>ubuntu-latest</code> runners, started by a push."),
           ("Network", "none to an LLM &mdash; mock mode keeps the model out of the job."),
           ("Writes", "nothing outside the runner; the vectors are rebuilt and thrown away each run.")],
    ledger_intro_obs="the workflow runs",
    ledger=[
        ("measured", "Removing a keyword from the knowledge base failed the build",
         "I removed \"orchestration\" from the Kubernetes document and pushed. The workflow got through checkout, setup, install, rebuilding embeddings and starting the API, then failed at <code>Run semantic tests</code> with <code>AssertionError: Missing 'orchestration' keyword</code>. The degraded document didn't get a green build.",
         "Pushed the edited document and read the failing step's log."),
        ("measured", "Generated answers hid the regression; retrieved context didn't",
         "With the keyword removed, I queried the API several times in normal mode and still saw \"orchestration\" in the answers &mdash; the model filled it in. In mock mode the retrieved context reflected the edit immediately. That difference is why the tests run against retrieval.",
         "Queried <code>/query</code> repeatedly with and without mock mode after editing the document."),
        ("observed", "Adding a second document surfaced a failing test straight away",
         "The first run after restructuring into <code>docs/</code> with a second document passed the Kubernetes query and failed the new one on <code>Missing 'maximus' keyword</code>. That's the run I kept a screenshot of; I'm not claiming a green multi-document run here.",
         "Read the job log for the multi-document commit."),
        ("design", "Same query, same result",
         "In mock mode the API returns the retrieved text with no sampling involved, so the tests have nothing random in them. I didn't run the suite hundreds of times to measure flakiness; the determinism comes from removing the model, not from a statistic.",
         "Reviewed the mock-mode path in <code>app.py</code>."),
    ],
    proof_note="From the workflow runs",
    shots=[
        dict(raw="ci-cd/github-actions-automated-testing/Screenshots/Screenshot from 2026-01-15 22-30-16.png", alt="curl POST to the local /query endpoint returning an answer about Kubernetes", cap="The API answering locally before any automation."),
        dict(raw="ci-cd/github-actions-automated-testing/Screenshots/Screenshot from 2026-01-31 21-27-06.png", alt="GitHub Actions test-and-build job failing at Run semantic tests with AssertionError Missing orchestration keyword", cap="The degraded document failing at <code>Run semantic tests</code>."),
        dict(raw="ci-cd/github-actions-automated-testing/Screenshots/Screenshot from 2026-01-31 22-24-52.png", alt="Workflow run for adding a second document: Kubernetes query test passed, NextWork query test failed on missing maximus keyword", cap="The multi-document run: one query passing, the new one failing."),
        dict(raw="ci-cd/github-actions-automated-testing/Screenshots/Screenshot from 2026-01-30 00-02-46.png", alt="nextwork-rag-api repository with app.py, embed.py, Dockerfile, k8s.txt and Kubernetes manifests", cap="The repository the workflow runs against."),
    ],
    broke=[
        ("The model kept saying a word I'd deleted",
         "The first version of the test checked generated answers. I removed \"orchestration\" from the knowledge base to prove the test would catch it &mdash; and the answers still contained it, because tinyllama already knows what Kubernetes is. A test that passes on a broken input is worse than no test. That's where mock mode came from."),
        ("The second document failed its first run",
         "When I restructured into <code>docs/</code> and added a NextWork document with its own test, the Kubernetes query still passed and the new query failed on <code>maximus</code>. That's the suite doing its job on new content: the expected keyword and what the document actually retrieved didn't agree."),
    ],
    source="The FastAPI service, the embedding scripts, <code>semantic_test.py</code> and <code>.github/workflows/ci.yml</code>, including the <code>USE_MOCK_LLM</code> path, live here: <a href=\"https://github.com/kingswanzy2020/nextwork-rag-api\">kingswanzy2020/nextwork-rag-api</a>. The same repo is the subject of the <a href=\"../rag-api/\">RAG API case study</a>.",
    clone="git clone https://github.com/kingswanzy2020/nextwork-rag-api.git",
    stack="GitHub Actions &middot; CI for AI systems &middot; semantic testing &middot; mock LLM mode &middot; FastAPI &middot; Chroma &middot; RAG &middot; Ollama &middot; path-filtered triggers",
),
# ======================================================================
dict(
    slug="ai-pr-review",
    card=dict(group="cicd", eyebrow="CI/CD / AI", color="c-ctl", status="CI workflow",
              title="AI pull-request review with Gemini",
              desc="Every PR gets a security review comment and a Critical / Warning / Good label before a human opens it."),
    title_tag="AI PR Review with Gemini",
    meta="Case study: a GitHub Actions workflow that sends each pull request's diff to Gemini, posts the review as a comment, and labels the PR by severity.",
    eyebrow="CI/CD / AI",
    h1="AI pull-request review with Gemini in GitHub Actions",
    standfirst="I built a workflow that sends every pull request's diff to Gemini with a structured reviewer prompt, posts the review as a PR comment, and labels the PR Critical, Warning or Good from a machine-readable severity line.",
    chip="CI workflow",
    status="This is a workflow in a repository, not a hosted bot. It runs on GitHub's runners whenever a pull request against <code>main</code> is opened or updated. Everything below describes the PRs I opened to test it.",
    spec=[("Trigger", "pull_request &rarr; main"), ("Model", "Gemini 2.5 via google-genai"),
          ("Output", "PR comment via github-script"), ("Triage", "Critical / Warning / Good labels"),
          ("Secret", "API key in GitHub Secrets"), ("Permissions", "contents: read, PRs: write")],
    summary="<code>ai_review.py</code> takes a diff and asks Gemini to review it as a code reviewer, returning a summary, security issues, bugs, performance notes, a score and a fix for each finding. I tested it locally against a sample diff first. The workflow checks out the PR with full history, generates the diff, runs the script with the key from GitHub Secrets, and posts the result with <code>github-script</code>. As an extension, the prompt also asks for a single <code>SEVERITY_SUMMARY</code> line that the workflow parses to apply one of three labels.",
    how=[
        ("Why test the script locally before automating it?", "If the prompt or the parsing is wrong, a workflow just makes the wrong answer arrive faster. I ran <code>ai_review.py</code> against <code>sample_diff.txt</code> first and checked it found the SQL injection the sample was built around before wiring it to pull requests."),
        ("Why a <code>SEVERITY_SUMMARY</code> line?", "Free-text reviews are for people; a workflow needs one thing it can parse. Asking the model for a single machine-readable line means the label step doesn't have to interpret prose, and a reviewer can sort open PRs by label without opening them."),
        ("Why GitHub Secrets for the key?", "The key authenticates every request against my quota. In a public repository it would be both a cost and an access risk, so it lives in Secrets and reaches the script as an environment variable."),
        ("Why does the job only get <code>pull-requests: write</code>?", "It needs to read code and write a comment and a label, and nothing else. The workflow's <code>permissions</code> block says exactly that."),
    ],
    diagram=dict(
        h=470,
        aria="Opening or updating a pull request triggers a GitHub Actions workflow, which checks out the code, generates the diff and runs ai_review.py. The script sends the prompt and diff to the Gemini API using a key from GitHub Secrets. The review is posted back as a PR comment, and the parsed severity line applies a Critical, Warning or Good label.",
        boxes=[dict(x=384, y=60, w=644, h=380, k="ctl", label="GITHUB ACTIONS — pr-review.yml · ubuntu-latest")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="opens / updates", tag="pull request"),
            dict(id="pr", x=192, y=110, w=160, k="ctl", icon="git", slot="github", t="Pull request", s="into main", tag="on: pull_request"),
            dict(id="diff", x=408, y=110, w=170, k="ctl", icon="doc", slot="github-actions", t="Get PR diff", s="fetch-depth: 0", tag="git diff"),
            dict(id="script", x=620, y=110, w=176, k="app", icon="code", slot="python", t="ai_review.py", s="structured prompt", tag="google-genai"),
            dict(id="sec", x=660, y=290, w=176, k="aws", icon="key", slot="secrets", t="GitHub Secrets", s="GEMINI_API_KEY", tag="env var"),
            dict(id="gem", x=1044, y=110, w=176, k="neu", icon="ai", slot="ai", t="Gemini 2.5", s="Gemini API", tag="review"),
            dict(id="cmt", x=866, y=290, w=150, k="obs", icon="chat", slot="github", t="PR comment", s="github-script", tag="AI Code Review"),
            dict(id="lbl", x=408, y=290, w=170, k="obs", icon="filter", slot="github", t="Severity label", s="SEVERITY_SUMMARY", tag="Critical/Warning/Good"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "pr"}, k="ctl", mech="opened / synchronize", what="Any PR against <code>main</code> starts the workflow."),
            dict(**{"from": "pr", "to": "diff"}, k="ctl", mech="checkout", what="Full history so the diff against the base is complete."),
            dict(**{"from": "diff", "to": "script"}, k="ctl", mech="diff text", what="Passed to <code>review_code(diff_text)</code>."),
            dict(**{"from": "sec", "to": "script"}, k="aws", ss="t", ts="b", to_off=40, mech="env var", what="The API key, never in the YAML or the repo."),
            dict(**{"from": "script", "to": "gem"}, k="app", mech="HTTPS API", what="Prompt plus diff; asks for summary, security, bugs, performance, score and fixes."),
            dict(**{"from": "gem", "to": "cmt"}, k="obs", ss="b", ts="r", mech="review text", what="Posted to the PR as an <em>AI Code Review</em> comment."),
            dict(**{"from": "script", "to": "lbl"}, k="obs", ss="b", ts="r", so=-60, mech="parse line", what="High &rarr; Critical, Medium &rarr; Warning, clean &rarr; Good."),
        ],
    ),
    figcaption="The workflow as it ran. Arrow 5 is the only call that leaves GitHub. Arrows 6 and 7 are the two outputs: one for a person to read, one for a person to sort by.",
    legend=[("c-neu", "Outside the workflow", "developer, Gemini"), ("c-ctl", "Trigger &amp; steps", "the PR, checkout, diff"),
            ("c-app", "The script", "ai_review.py"), ("c-aws", "Secret", "the API key"), ("c-obs", "Outputs", "comment and label"),
            ("line:c-ctl", "Workflow flow", "PR to script"), ("line:c-app", "Model call", "the only external request"),
            ("line:c-obs", "Results", "written back to the PR")],
    reach_title="What it touches",
    reach=[("Reads", "the pull request's diff."),
           ("Calls", "the Gemini API, with a key from GitHub Secrets."),
           ("Writes", "one comment and one label on the PR, under <code>pull-requests: write</code>.")],
    ledger_intro_obs="the pull requests",
    ledger=[
        ("measured", "The script found the SQL injection in the sample diff before any automation",
         "Run locally against <code>sample_diff.txt</code>, the review flagged the <code>get_user</code> function for building its SQL query with an f-string from the username &mdash; a SQL injection &mdash; and also called out the database connection never being closed.",
         "Ran <code>python scripts/ai_review.py scripts/sample_diff.txt</code> and read the output."),
        ("measured", "A PR with <code>shell=True</code> on user input was flagged High and labelled Critical",
         "I opened a PR adding <code>dangerous.py</code>, which passes user input to <code>subprocess.call(..., shell=True)</code>. The workflow's comment led with a shell injection finding at severity HIGH, and the PR got the Critical label.",
         "Opened the test PR and read the bot's comment and the applied label."),
        ("observed", "It flagged my own script too",
         "The reviewer pointed at a shell-injection path and a hardcoded-key risk in my own code. I fixed both &mdash; the shell interpreter off, the key moved to an environment variable &mdash; and the re-review no longer raised them.",
         "Read the review on the PR before and after the fix."),
        ("design", "The key never appears in the repository",
         "It's read from GitHub Secrets as an environment variable in the job. I didn't audit every log line for masking failures; GitHub masks registered secrets in logs.",
         "Reviewed <code>pr-review.yml</code>'s <code>env</code> block."),
    ],
    proof_note="From the pull requests",
    shots=[
        dict(pdf="legendary-ai-cicd-codereview/i-011.png", name="local-review.jpg", crop=(0, 50, 793, 999), alt="Terminal output of ai_review.py flagging a SQL injection in get_user and a database connection resource leak", cap="The local run on the sample diff: SQL injection and a connection leak."),
        dict(pdf="legendary-ai-cicd-codereview/i-014.png", name="workflow.jpg", alt="pr-review.yml workflow: on pull_request to main, permissions contents read and pull-requests write, checkout with fetch-depth 0", cap="<code>pr-review.yml</code>: trigger and permissions."),
        dict(pdf="legendary-ai-cicd-codereview/i-019.png", name="critical-pr.jpg", alt="github-actions bot comment AI Code Review: Shell Injection Vulnerability in dangerous.py, severity HIGH", cap="The bot's review: shell injection, severity HIGH."),
        dict(pdf="legendary-ai-cicd-codereview/i-017.png", name="review-comment.jpg", alt="AI Code Review comment on a test pull request with security, bugs, performance, a score of 30/100 and fixes", cap="A full review: findings, a score and a fix for each."),
    ],
    broke=[
        ("Building the workflow was harder than the script",
         "The script worked locally on the first real run. Wiring it into a pull-request workflow &mdash; checkout depth, getting the diff into the script, posting through <code>github-script</code> &mdash; took most of the four hours. The model was the easy part."),
    ],
    source="The workflow and <code>ai_review.py</code> live in the same repository as my <a href=\"../github-actions-ci/\">first GitHub Actions workflow</a>, along with the deliberately vulnerable sample used to prove the pipeline catches it: <a href=\"https://github.com/kingswanzy2020/ai-cicd-github\">kingswanzy2020/ai-cicd-github</a>.",
    clone="git clone https://github.com/kingswanzy2020/ai-cicd-github.git",
    stack="GitHub Actions &middot; Gemini API (google-genai) &middot; prompt design for structured output &middot; github-script &middot; GitHub Secrets &middot; workflow permissions &middot; security review automation &middot; Python",
),
# ======================================================================
dict(
    slug="github-actions-ci",
    card=dict(group="cicd", eyebrow="CI/CD", color="c-ctl", status="CI workflow",
              title="CI fundamentals with GitHub Actions",
              desc="A pytest suite on every push and PR, a bug introduced on purpose to prove it bites, and an installable package as the artifact."),
    title_tag="GitHub Actions CI Fundamentals",
    meta="Case study: a GitHub Actions workflow that runs a pytest suite on every push and pull request to main, and packages the code as a downloadable wheel and source distribution.",
    eyebrow="CI/CD",
    h1="CI fundamentals with GitHub Actions and pytest",
    standfirst="I wrote a CI workflow from scratch that runs a pytest suite on every push and pull request to <code>main</code>, broke a test on purpose to prove it catches failures, and added a build step that turns each green run into an installable Python package.",
    chip="CI workflow",
    status="This is a workflow in a repository, not a running service. It runs on GitHub's runners on every push and pull request to <code>main</code>. Everything below describes the runs from the build.",
    spec=[("CI", "GitHub Actions, ubuntu-latest"), ("Trigger", "push + pull_request &rarr; main"),
          ("Runtime", "Python 3.11"), ("Tests", "pytest, 6 tests"),
          ("Artifact", ".whl + .tar.gz, python-package"), ("Run time", "about 21 seconds")],
    summary="The project is a small Python module with typed functions. I added a <code>multiply</code> function and tests for it, grouped in pytest classes, and confirmed all six tests passed locally in a virtualenv. Then I wrote <code>.github/workflows/ci.yml</code>: checkout, set up Python 3.11, install requirements, run <code>pytest -v</code>. After that worked, I added <code>python -m build</code> and <code>actions/upload-artifact</code>, so every green run leaves a <code>python-package</code> artifact anyone can <code>pip install</code>.",
    how=[
        ("Why run tests in CI when they pass locally?", "\"Passes on my laptop\" depends on my laptop. CI runs the same commands on a clean runner for every push and pull request, so a broken change is caught before anyone pulls it, not after."),
        ("Why break a test on purpose?", "A pipeline that has only ever been green hasn't proved anything. I changed an assertion so it was false and pushed: the run went red. Fixing it and watching it go green again is the evidence the workflow is actually checking something."),
        ("Why upload an artifact?", "Tests answer \"does it work?\"; the artifact answers \"what do I ship?\". <code>python -m build</code> produces a wheel and a source tarball, and uploading them as one artifact means each green commit has a package attached to it."),
    ],
    diagram=dict(
        h=420,
        aria="A push or pull request to main triggers a GitHub Actions job that checks out the code, sets up Python 3.11, installs dependencies and runs pytest. A failing test turns the run red; a passing run builds the package and uploads it as the python-package artifact.",
        boxes=[dict(x=384, y=60, w=844, h=330, k="ctl", label="GITHUB ACTIONS — ci.yml · job build · ubuntu-latest")],
        nodes=[
            dict(id="dev", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="push or PR", tag="main"),
            dict(id="gh", x=192, y=110, w=160, k="ctl", icon="git", slot="github", t="GitHub", s="ai-cicd-github", tag="ci.yml"),
            dict(id="setup", x=408, y=110, w=176, k="ctl", icon="gear", slot="python", t="Set up", s="checkout · Python 3.11", tag="pip install"),
            dict(id="test", x=630, y=110, w=176, k="obs", icon="gate", slot="pytest", t="pytest -v", s="6 tests", tag="the gate"),
            dict(id="build", x=852, y=110, w=176, k="app", icon="box", slot="python", t="python -m build", s=".whl + .tar.gz", tag="on green"),
            dict(id="art", x=852, y=270, w=176, k="app", icon="disk", slot="github", t="Artifact", s="python-package", tag="5.27 KB"),
            dict(id="red", x=630, y=270, w=176, k="neu", icon="x", slot="gate", t="Run fails", s="assertion error", tag="change blocked"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "gh"}, k="ctl", mech="push / PR", what="Anything targeting <code>main</code>."),
            dict(**{"from": "gh", "to": "setup"}, k="ctl", ft="GitHub &rarr; job", mech="on: push, pull_request", what="Checkout, <code>setup-python</code> 3.11, install requirements."),
            dict(**{"from": "setup", "to": "test"}, k="ctl", mech="run step", what="<code>pytest -v</code> across the six tests."),
            dict(**{"from": "test", "to": "red"}, k="neu", mech="any failure", what="The job fails and the commit shows red."),
            dict(**{"from": "test", "to": "build"}, k="app", mech="all pass", what="Packages the module with <code>python -m build</code>."),
            dict(**{"from": "build", "to": "art"}, k="app", mech="upload-artifact", what="Uploads <code>dist/</code> as <code>python-package</code>."),
        ],
    ),
    figcaption="The job as it ran. Arrow 4 is the one I triggered on purpose; arrows 5 and 6 only happen when it doesn't fire.",
    legend=[("c-neu", "Actor &amp; failure", "developer, a red run"), ("c-ctl", "Source &amp; setup", "GitHub, checkout, Python"),
            ("c-obs", "The gate", "pytest"), ("c-app", "Output", "package and artifact"),
            ("line:c-ctl", "Workflow flow", "step to step"), ("line:c-app", "On green", "build and upload")],
    reach_title="What it touches",
    reach=[("Runs on", "GitHub-hosted runners."),
           ("Writes", "one artifact per green run, downloadable from the run page."),
           ("Secrets", "none needed.")],
    ledger_intro_obs="the workflow runs",
    ledger=[
        ("measured", "A false assertion turned the run red; fixing it turned it green",
         "I introduced a failing assertion in the test file and pushed; CI failed. I corrected the assertion and pushed again: the run named <em>Fix the test</em> (#3) passed every step.",
         "Pushed the broken test, then the fix, and read both runs in the Actions tab."),
        ("observed", "Six tests passed locally before CI existed",
         "<code>pytest -v</code> collected six tests across three test classes, including the two for <code>multiply</code>, and passed all of them in 0.01 seconds.",
         "Ran <code>pytest -v</code> in the virtualenv."),
        ("observed", "Every green run produced an installable package",
         "Run #4, <em>Add build and artifact upload to CI</em>, succeeded in 21 seconds and attached one artifact, <code>python-package</code>, at 5.27&nbsp;KB. I downloaded it from the run page.",
         "Read the run summary and downloaded the artifact."),
    ],
    proof_note="From the workflow runs",
    shots=[
        dict(raw="ci-cd/github-actions-ai-workflow/Screenshots/Screenshot from 2026-02-01 22-56-34.png", alt="pytest -v output: 6 tests collected and passed", cap="Six tests passing locally."),
        dict(raw="ci-cd/github-actions-ai-workflow/Screenshots/Screenshot from 2026-02-01 23-11-41.png", alt="ci.yml: on push and pull_request to main, checkout, setup-python 3.11, install dependencies, pytest -v", cap="<code>ci.yml</code>."),
        dict(raw="ci-cd/github-actions-ai-workflow/Screenshots/Screenshot from 2026-02-01 23-33-38.png", alt="GitHub Actions run Fix the test #3 with every step of the build job succeeded", cap="<em>Fix the test</em> (#3): green after the deliberate failure."),
        dict(raw="ci-cd/github-actions-ai-workflow/Screenshots/Screenshot from 2026-02-02 00-03-27.png", alt="Run #4 succeeded in 21s with one artifact, python-package, 5.27 KB", cap="Run #4: 21 seconds, one 5.27&nbsp;KB artifact."),
    ],
    broke=[
        ("A test I broke so CI would have something to catch",
         "The first failure in this project was deliberate: a false assertion pushed to <code>main</code>. The run went red, which was the point. The less deliberate difficulty was writing the test and workflow files themselves &mdash; the YAML took longer than the Python."),
    ],
    source="The workflow, the tested module and its pytest suite live here: <a href=\"https://github.com/kingswanzy2020/ai-cicd-github\">kingswanzy2020/ai-cicd-github</a>. The same repository later grew the <a href=\"../ai-pr-review/\">AI pull-request reviewer</a>.",
    clone="git clone https://github.com/kingswanzy2020/ai-cicd-github.git\ncd ai-cicd-github && python -m venv venv && source venv/bin/activate\npip install -r requirements.txt && pytest -v",
    stack="GitHub Actions &middot; pytest &middot; Python 3.11 &middot; type hints &middot; Python packaging (build) &middot; CI artifacts &middot; virtual environments",
),
]
