def lab_status(rebuild):
    return ("I built this in my own AWS account as a guided NextWork lab. I'm not pointing you at a live endpoint &mdash; "
            "the screenshots below were captured during the build, and " + rebuild + " Everything below is in the past tense for that reason.")


ECR = "aws/cross-account-ecr-deployment/Screenshots/"
EB = "aws/docker-elastic-beanstalk/Screenshots/"
IAM = "aws/iam-cloud-security/Screenshots/"
BP = "aws/iam-boundary-proof/Screenshots/"

PAGES = [
# ======================================================================
dict(
    slug="cross-account-ecr",
    card=dict(group="aws", eyebrow="AWS / Containers", color="c-aws", status="Guided lab",
              title="Sharing container images across AWS accounts",
              desc="Two accounts swap private ECR images and deploy each other's app on Elastic Beanstalk &mdash; through two layers of 403s."),
    title_tag="Cross-Account ECR Deployment",
    meta="Case study: two AWS accounts each push a Docker image to a private ECR repository and grant the other account just enough access to pull and deploy it on Elastic Beanstalk.",
    eyebrow="AWS / Containers",
    h1="Sharing container images across AWS accounts without sharing an account",
    standfirst="With a project buddy on a second AWS account, I pushed a Docker image to my private ECR repository and granted their account just enough access to pull and deploy it on Elastic Beanstalk &mdash; and they did the same for me.",
    chip="Guided lab",
    status="This was a two-person NextWork lab across two AWS accounts. I'm not pointing you at a live endpoint &mdash; the screenshots below were captured during the build, and the <code>Dockerfile</code>, page and <code>Dockerrun.aws.json</code> in the repo plus two repository policies rebuild it. Everything below is in the past tense for that reason.",
    spec=[("Registry", "Amazon ECR, private, ap-northeast-1"), ("Image", "nginx base + custom index.html"),
          ("CLI identity", "IAM user, ECR full access"), ("Sharing", "ECR repository policies"),
          ("Deploy", "Elastic Beanstalk, Dockerrun.aws.json"), ("Accounts", "2, no shared credentials")],
    summary="Each of us built an nginx image with our own <code>index.html</code>, created a private ECR repository, authenticated Docker with <code>aws ecr get-login-password</code>, and pushed. Then each of us deployed the <em>other</em> person's image on Elastic Beanstalk, using a <code>Dockerrun.aws.json</code> that names the image in the other account and exposes port 80. Nothing was shared but ARNs: every grant is a statement in a repository policy naming exactly who may pull.",
    how=[
        ("Why repository policies instead of sharing credentials or a public repo?", "Sharing credentials collapses the boundary between accounts; making the repository public hands the image to everyone. A repository policy grants pull access to specific principals in another account and nobody else, and it's written down where it can be reviewed."),
        ("Why did the policy need two kinds of principal?", "Two different things pull the image. I pull it from my terminal as an IAM user, so my user's ARN has to be allowed. Elastic Beanstalk's EC2 instance pulls it during deployment under its instance role &mdash; a different principal that needs its own grant. The first fix covered only the first."),
        ("What does <code>Dockerrun.aws.json</code> do?", "It tells Elastic Beanstalk to run a pre-built image instead of building one: version 1, a single container, the image's full ECR URI in the other account, and container port 80."),
        ("Why does CPU architecture matter here?", "Images are built for one architecture &mdash; x86-64 on most laptops and servers, ARM64 on Apple silicon and Graviton. If the person building and the host running differ, the image won't run. <code>docker buildx</code> with <code>--platform linux/amd64,linux/arm64</code> builds one image for both."),
    ],
    diagram=dict(
        h=560,
        aria="Two AWS accounts. In my account, my laptop pushes an image to my private ECR repository, and my Elastic Beanstalk environment runs my buddy's image. In my buddy's account, their ECR repository holds their image and their Elastic Beanstalk environment runs mine. Each repository policy names the other account's IAM user and instance role.",
        boxes=[dict(x=176, y=60, w=500, h=470, k="aws", label="MY ACCOUNT — ap-northeast-1"),
               dict(x=728, y=60, w=500, h=470, k="ctl", label="MY BUDDY'S ACCOUNT")],
        nodes=[
            dict(id="me", x=16, y=110, w=136, k="neu", icon="terminal", slot="docker", t="My machine", s="docker build", tag="IAM user + CLI"),
            dict(id="ecrA", x=210, y=110, w=210, k="aws", icon="box", slot="ecr", t="My ECR repo", s="nextwork/cross-account-…", tag="policy: buddy's ARNs"),
            dict(id="pol", x=210, y=280, w=210, k="aws", icon="doc", slot="iam", t="Repository policy", s="IAM user + instance role", tag="added after 2 failures"),
            dict(id="ebA", x=440, y=430, w=210, k="app", icon="server", slot="elastic-beanstalk", t="My EB environment", s="Dockerrun.aws.json", tag="runs buddy's image"),
            dict(id="ecrB", x=990, y=110, w=210, k="ctl", icon="box", slot="ecr", t="Buddy's ECR repo", s="their custom nginx image", tag="policy: my ARNs"),
            dict(id="ebB", x=760, y=430, w=210, k="app", icon="server", slot="elastic-beanstalk", t="Buddy's EB env", s="Dockerrun.aws.json", tag="runs my image"),
        ],
        edges=[
            dict(**{"from": "me", "to": "ecrA"}, k="aws", mech="docker push", what="After <code>get-login-password | docker login</code>; tagged <code>latest</code>."),
            dict(**{"from": "pol", "to": "ecrA"}, k="aws", dash=True, mech="attached", what="Names my buddy's IAM user and their Beanstalk instance role &mdash; nobody else."),
            dict(**{"from": "ecrA", "to": "ebB"}, k="app", pts=[(420, 154), (700, 154), (700, 474), (756, 474)], mech="cross-account pull", what="Their environment pulls my image under its instance role."),
            dict(**{"from": "ecrB", "to": "ebA"}, k="app", pts=[(1095, 198), (1095, 380), (545, 380), (545, 426)], mech="cross-account pull", what="My environment pulls theirs; only worked once my instance role was in their policy."),
            dict(**{"from": "me", "to": "ecrB"}, k="neu", dash=True, pts=[(84, 110), (84, 40), (1095, 40), (1095, 106)], mech="docker pull", what="First attempt: <code>403 Forbidden</code>. Worked after my IAM user's ARN was added to their policy."),
        ],
    ),
    figcaption="The exchange as it ran. Arrows 3 and 4 cross the account boundary, and each one only worked after the repository policy on the far side named the principal doing the pulling &mdash; which turned out not to be the same principal as arrow 5.",
    legend=[("c-neu", "My machine", "build, push and test pulls"), ("c-aws", "My account", "my repo and its policy"),
            ("c-ctl", "My buddy's account", "their repo"), ("c-app", "Running apps", "each other's image"),
            ("line:c-aws", "Push", "into my own repo"), ("line:c-app", "Cross-account pull", "allowed by a named ARN"),
            ("line:c-neu:dashed", "Manual pull", "the first 403")],
    reach=[("Public", "each Elastic Beanstalk environment's URL, serving the other person's page."),
           ("Private", "both ECR repositories; readable only by the principals each policy names."),
           ("Shared", "ARNs. No access keys, no passwords, no public repository.")],
    ledger_intro_obs="the consoles",
    ledger=[
        ("measured", "Pulling across accounts failed with 403 until the policy named me",
         "My first <code>docker pull</code> of my buddy's image returned <code>403 Forbidden</code>, because their repository is private. After we each added the other's IAM user ARN to our repository policies, the pull worked.",
         "Ran <code>docker pull</code> against the other account's repository before and after the policy change."),
        ("measured", "Beanstalk couldn't reach the image until its role was named too",
         "With the user ARNs in place, my environment still showed <em>This site can't be reached</em>: the instance pulling the image wasn't my IAM user. We added the Beanstalk and EC2 instance role ARNs to both policies, rebuilt the environments, and both sites came up running the other person's page.",
         "Opened the environment URL, changed the policies, rebuilt, and opened it again."),
        ("observed", "The image landed in a private repository",
         "After the push, my repository listed the image, tagged <code>latest</code>.",
         "Read the repository's Images tab."),
        ("design", "Each grant is explicit and auditable",
         "Every cross-account permission is a statement in a repository policy naming specific ARNs, so the policy is the complete list of who can pull. I'm stating that from the policies; I didn't try pulling from a third account.",
         "Reviewed both repository policies. Not tested from an unlisted account."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(raw=ECR + "Screenshot from 2026-01-06 12-02-56.png", alt="Amazon ECR repository nextwork/cross-account-docker-app listing the pushed images", cap="My private repository after the push."),
        dict(raw=ECR + "Screenshot from 2026-01-06 12-23-33.png", alt="docker pull of the other account's image failing with 403 Forbidden", cap="The first cross-account pull: <code>403 Forbidden</code>."),
        dict(raw=ECR + "Screenshot from 2026-01-06 13-10-05.png", alt="Dockerrun.aws.json with version 1, the image name in the other account's ECR and container port 80", cap="<code>Dockerrun.aws.json</code>: someone else's image, port 80."),
        dict(raw=ECR + "Site_error.png", alt="Browser showing This site can't be reached for the Elastic Beanstalk environment", cap="The second failure: the instance role couldn't pull."),
    ],
    broke=[
        ("<code>403 Forbidden</code> on the first pull",
         "Private means private: without a repository policy naming my IAM user, my buddy's ECR refused me, and mine refused them. Adding each other's user ARN fixed the manual pull."),
        ("The site couldn't be reached &mdash; the permission was on the wrong principal",
         "The environment launched and the URL didn't load. The repository policies only allowed our IAM users, but it's the Beanstalk instance that pulls the image, under its own role. Adding the instance and Beanstalk role ARNs and rebuilding fixed it. Two different 403s for one image, because two different things were pulling it."),
    ],
    source="The <code>Dockerfile</code>, the page and the <code>Dockerrun.aws.json</code> that points Elastic Beanstalk at a pre-built ECR image live here: <a href=\"https://github.com/kingswanzy2020/cross-account-ecr-app\">kingswanzy2020/cross-account-ecr-app</a>.",
    clone="git clone https://github.com/kingswanzy2020/cross-account-ecr-app.git",
    stack="Amazon ECR &middot; repository policies &middot; cross-account IAM &middot; Docker &middot; Elastic Beanstalk &middot; Dockerrun.aws.json &middot; instance roles &middot; multi-architecture images (buildx)",
),
# ======================================================================
dict(
    slug="elastic-beanstalk-docker",
    card=dict(group="aws", eyebrow="AWS / Containers", color="c-aws", status="Guided lab",
              title="A Docker app on Elastic Beanstalk",
              desc="A three-line Dockerfile tested locally, live on a managed environment in about ten minutes, updated with one upload."),
    title_tag="Docker on Elastic Beanstalk",
    meta="Case study: a custom nginx image built from a three-instruction Dockerfile, tested locally, and deployed and updated on AWS Elastic Beanstalk.",
    eyebrow="AWS / Containers",
    h1="A containerised web app on Elastic Beanstalk",
    standfirst="I built a custom nginx image from a three-line Dockerfile, proved it locally, then zipped it up for Elastic Beanstalk and had a live environment in about ten minutes &mdash; and shipped an update with one upload.",
    chip="Guided lab",
    status=lab_status("the <code>Dockerfile</code> and page in the repo, zipped and uploaded, recreate the environment."),
    spec=[("Image", "nginx:latest + index.html"), ("Dockerfile", "3 instructions"),
          ("Local test", "docker run -d -p 80:80"), ("Platform", "Elastic Beanstalk, Docker"),
          ("Region", "us-east-1"), ("First deploy", "about 10 minutes")],
    summary="I started with a stock nginx container in detached mode with a port mapping, then wrote a Dockerfile that takes <code>nginx:latest</code>, copies my own <code>index.html</code> over the default page, and exposes port 80. After building and running it locally, I zipped the Dockerfile and page and uploaded them to Elastic Beanstalk, which built the image and ran it on an EC2 instance it manages, behind a public environment URL. To update, I changed the page, re-zipped, and used <em>Upload and deploy</em>.",
    how=[
        ("Why test locally first?", "If the image doesn't serve the right page on my machine, it won't in the cloud either, and the cloud is the slower place to find out. A container that runs identically everywhere is the whole point; the local run is the cheap proof."),
        ("What does Beanstalk take off my hands?", "The EC2 instances, the health checks, and scaling. I hand it the application; it handles the environment. That's also why an app update doesn't need a new environment &mdash; the change is in the code, not the infrastructure."),
        ("What are the three Dockerfile lines doing?", "<code>FROM nginx:latest</code> picks the base, <code>COPY index.html /usr/share/nginx/html/</code> replaces the default page, and <code>EXPOSE 80</code> documents the port the container listens on."),
    ],
    diagram=dict(
        h=500,
        aria="On my laptop, a Dockerfile builds a custom nginx image that runs locally on port 80. The Dockerfile and page are zipped and uploaded to Elastic Beanstalk, which builds and runs the image on a managed EC2 instance behind a public environment URL. A visitor loads the page from that URL.",
        boxes=[dict(x=16, y=60, w=560, h=410, k="neu", label="MY MACHINE — DOCKER DESKTOP"),
               dict(x=620, y=60, w=608, h=410, k="aws", label="AWS — ELASTIC BEANSTALK · us-east-1")],
        nodes=[
            dict(id="df", x=40, y=110, w=200, k="ctl", icon="code", slot="docker", t="Dockerfile", s="FROM · COPY · EXPOSE", tag="3 lines"),
            dict(id="img", x=330, y=110, w=210, k="app", icon="box", slot="docker", t="my-web-app image", s="docker build -t", tag="nginx + my page"),
            dict(id="run", x=330, y=300, w=210, k="app", icon="pod", slot="docker", t="Local container", s="docker run -d -p 80:80", tag="tested first"),
            dict(id="zip", x=40, y=300, w=200, k="neu", icon="doc", slot="zip", t="Source bundle", s="Dockerfile + index.html", tag=".zip"),
            dict(id="eb", x=660, y=110, w=230, k="aws", icon="cloud", slot="elastic-beanstalk", t="Elastic Beanstalk", s="application + environment", tag="Upload and deploy"),
            dict(id="ec2", x=660, y=300, w=230, k="app", icon="server", slot="ec2", t="Managed EC2", s="builds + runs the image", tag="health checks"),
            dict(id="vis", x=980, y=300, w=200, k="neu", icon="browser", slot="browser", t="Visitor", s="environment URL", tag="HTTP"),
        ],
        edges=[
            dict(**{"from": "df", "to": "img"}, k="ctl", mech="docker build", what="Builds the custom image from the current directory."),
            dict(**{"from": "img", "to": "run"}, k="app", mech="docker run", what="Detached, port 80 mapped to the host; the first run collided with an old container."),
            dict(**{"from": "df", "to": "zip"}, k="neu", mech="zip", what="The Dockerfile and page are all Beanstalk needs."),
            dict(**{"from": "zip", "to": "eb"}, k="aws", pts=[(140, 388), (140, 440), (598, 440), (598, 154), (656, 154)], mech="upload", what="Creates the environment the first time; <em>Upload and deploy</em> after that."),
            dict(**{"from": "eb", "to": "ec2"}, k="aws", mech="provision + deploy", what="Launches and manages the instance, builds the image, runs it."),
            dict(**{"from": "vis", "to": "ec2"}, k="req", mech="HTTP", what="The page with my text, then with the update."),
        ],
    ),
    figcaption="The deployment as it ran. Arrows 1 and 2 are the local proof; arrows 4 and 5 are the same image built by AWS instead of me. Updating the app was arrow 4 again, nothing else.",
    legend=[("c-neu", "Local &amp; people", "my machine, the bundle, a visitor"), ("c-ctl", "Source", "the Dockerfile"),
            ("c-app", "Running image", "locally and in AWS"), ("c-aws", "AWS-managed", "Elastic Beanstalk"),
            ("line:c-ctl", "Build", "image from Dockerfile"), ("line:c-aws", "Deploy", "upload and provision"),
            ("line:c-app", "Request", "visitor to app")],
    reach=[("Public", "the environment URL on <code>elasticbeanstalk.com</code>, plain HTTP."),
           ("Managed", "the EC2 instance and health checks, owned by the environment."),
           ("Local", "the test container, on my machine only.")],
    ledger_intro_obs="the running containers",
    ledger=[
        ("measured", "An update shipped with one upload and no environment change",
         "I added an image to <code>index.html</code>, checked it locally, re-zipped, and used <em>Upload and deploy</em>. The live page showed the new content without me touching the environment's configuration.",
         "Loaded the environment URL before and after the upload."),
        ("observed", "The custom image served my page locally before it went anywhere",
         "The container answered on the host with \"Hello from King's custom Docker image!\" instead of the nginx welcome page.",
         "Opened the mapped port in a browser."),
        ("observed", "Upload to live took about ten minutes",
         "Creating the environment, including launch time, took roughly ten minutes before the page served from the Beanstalk URL. That's my reading of the clock during setup, not a timed measurement.",
         "Watched the environment until it was healthy, then loaded the URL."),
        ("design", "Health checks and scaling are Beanstalk's job",
         "The environment manages its instance, health checks and scaling. I didn't kill the instance or load the app to watch either happen.",
         "Reviewed the environment configuration. Not tested."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(raw=EB + "Screenshot from 2026-01-04 06-42-38.png", alt="Dockerfile in nano: FROM nginx:latest, COPY index.html /usr/share/nginx/html/, EXPOSE 80", cap="The whole Dockerfile."),
        dict(raw=EB + "Screenshot from 2026-01-04 07-32-59.png", alt="Browser showing Hello from King's custom Docker image! served by the local container", cap="The custom image, running locally."),
        dict(raw=EB + "Screenshot from 2026-01-04 15-41-56.png", alt="The same page served from the Elastic Beanstalk environment URL", cap="The same image on Elastic Beanstalk."),
        dict(raw=EB + "Screenshot from 2026-01-04 16-42-21.png", alt="The updated page with an added image served from the Elastic Beanstalk environment", cap="The update, shipped with one upload."),
    ],
    broke=[
        ("Port 80 was already taken &mdash; by me",
         "The first run of my custom image failed because the stock nginx container from earlier was still bound to port 80. <code>docker stop</code> on the old container ID freed it. Small, but it's the difference between understanding container lifecycle and rebooting until things work."),
    ],
    source="The Dockerfile and the page it serves live here: <a href=\"https://github.com/kingswanzy2020/eb-docker-webapp\">kingswanzy2020/eb-docker-webapp</a>.",
    clone="git clone https://github.com/kingswanzy2020/eb-docker-webapp.git\ndocker build -t my-web-app . &amp;&amp; docker run -d -p 80:80 my-web-app",
    stack="Docker &middot; Dockerfile &middot; nginx &middot; port mapping &amp; container lifecycle &middot; AWS Elastic Beanstalk &middot; managed platform deployment",
),
# ======================================================================
dict(
    slug="iam-tag-based-access",
    card=dict(group="aws", eyebrow="AWS / Security", color="c-aws", status="Guided lab",
              title="Tag-based least privilege with IAM",
              desc="Developers control development-tagged EC2 and nothing else &mdash; tested as the user, then in the Policy Simulator."),
    title_tag="IAM Tag-Based Access",
    meta="Case study: an IAM policy that gives developers full control of development-tagged EC2 instances, read-only access elsewhere, and no ability to change tags, verified live and in the IAM Policy Simulator.",
    eyebrow="AWS / Security",
    h1="Tag-based least privilege for EC2 with IAM",
    standfirst="I wrote an IAM policy that lets developers do anything to EC2 instances tagged <code>development</code>, only look at everything else, and never create or delete tags &mdash; then signed in as that developer to try stopping both instances.",
    chip="Guided lab",
    status=lab_status("the JSON policy and two tagged instances recreate it."),
    spec=[("Scope", "EC2, tagged Env"), ("Policy", "3 statements, hand-written JSON"),
          ("Assigned to", "an IAM user group"), ("Tag tampering", "explicit Deny"),
          ("Verified", "as the user + Policy Simulator"), ("Sign-in", "account alias URL")],
    summary="Two EC2 instances got an <code>Env</code> tag: <code>production</code> and <code>development</code>. <code>NextWorkDevEnvironmentPolicy</code> has three statements: allow <code>ec2:*</code> where <code>ec2:ResourceTag/Env</code> is <code>development</code>; allow <code>ec2:Describe*</code> on everything; deny <code>ec2:CreateTags</code> and <code>ec2:DeleteTags</code>. The policy is attached to a user group, a developer user is in the group, and the account has an alias so that user signs in at a readable URL. I tested it twice: as the user in the console, and in the IAM Policy Simulator.",
    how=[
        ("Why tags instead of listing instance IDs?", "A tag makes the boundary a property of the resource. A new development instance is covered the moment it's tagged; nobody has to edit the policy."),
        ("Why deny tag changes outright?", "If a developer could edit tags, they could tag a production instance <code>development</code> and the first statement would hand them control of it. An explicit Deny on <code>CreateTags</code> and <code>DeleteTags</code> closes that, and an explicit Deny can't be overridden by any Allow."),
        ("Why attach to a group?", "So the policy describes a role, not a person. Onboarding a developer is adding them to the group."),
        ("Why was stopping production denied, exactly?", "Not by the Deny statement. The only Allow for <code>StopInstances</code> carries the development tag condition, so for a production instance no statement allows it &mdash; an implicit deny. The console's error said exactly that: no identity-based policy allows the action."),
    ],
    diagram=dict(
        h=560,
        aria="A developer user belongs to an IAM user group with a three-statement policy attached. Against the development-tagged instance, stop is allowed. Against the production-tagged instance, stop is implicitly denied. Creating or deleting tags is explicitly denied. The IAM Policy Simulator evaluates the same policy before it's relied on.",
        boxes=[dict(x=176, y=60, w=1052, h=470, k="aws", label="AWS ACCOUNT — IAM · EC2 · SIGN-IN VIA ACCOUNT ALIAS")],
        nodes=[
            dict(id="dev", x=16, y=250, w=136, k="neu", icon="user", slot="engineer", t="Developer", s="IAM user", tag="alias sign-in"),
            dict(id="grp", x=210, y=250, w=180, k="aws", icon="user", slot="iam", t="User group", s="developers", tag="one policy"),
            dict(id="pol", x=440, y=250, w=280, k="aws", icon="doc", slot="iam", t="NextWorkDevEnvironmentPolicy", s="3 statements", tag="JSON"),
            dict(id="devi", x=830, y=96, w=210, k="app", icon="server", slot="ec2", t="Dev instance", s="Env = development", tag="ec2:* allowed"),
            dict(id="prod", x=830, y=250, w=210, k="neu", icon="server", slot="ec2", t="Prod instance", s="Env = production", tag="Describe only"),
            dict(id="tags", x=830, y=404, w=210, k="neu", icon="x", slot="iam", t="Create / DeleteTags", s="any EC2 resource", tag="explicit Deny"),
            dict(id="sim", x=440, y=420, w=280, k="obs", icon="gate", slot="iam", t="Policy Simulator", s="StopInstances · DeleteTags", tag="before relying on it"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "grp"}, k="neu", mech="member of", what="The user gets permissions only through the group."),
            dict(**{"from": "pol", "to": "grp"}, k="aws", dash=True, mech="attached", what="One policy for every developer."),
            dict(**{"from": "pol", "to": "devi"}, k="app", ss="r", ts="l", so=-20, mx=750, mech="Allow ec2:*", what="Condition <code>ec2:ResourceTag/Env = development</code>. Stopping it succeeded."),
            dict(**{"from": "pol", "to": "prod"}, k="neu", ss="r", ts="l", so=0, mech="no matching Allow", what="Only <code>Describe*</code> applies; stop was refused as an implicit deny."),
            dict(**{"from": "pol", "to": "tags"}, k="neu", ss="r", ts="l", so=20, mx=770, mech="explicit Deny", what="No re-tagging an instance into development, whatever else is allowed."),
            dict(**{"from": "sim", "to": "pol"}, k="obs", dash=True, mech="simulate", what="Evaluates the policy without touching real resources; needs the tag in its context to match the condition."),
        ],
    ),
    figcaption="The policy as it evaluated. Arrows 3 to 5 are three different outcomes from one policy: an allow with a condition, an implicit deny, and an explicit deny. The second one is the one people usually call a deny statement, and it isn't.",
    legend=[("c-neu", "Actor &amp; refused targets", "the developer, prod, tag changes"), ("c-aws", "IAM", "group and policy"),
            ("c-app", "Allowed target", "the development instance"), ("c-obs", "Validation", "the Policy Simulator"),
            ("line:c-app", "Allowed", "tag condition met"), ("line:c-neu", "Refused", "implicit or explicit"),
            ("line:c-obs:dashed", "Simulation", "no real resources touched")],
    reach_title="What the developer could do",
    reach=[("Development", "anything EC2 allows on instances tagged <code>Env = development</code>."),
           ("Everything else in EC2", "<code>Describe*</code> only."),
           ("Never", "create or delete tags, or anything outside EC2 &mdash; most console panels showed Access Denied.")],
    ledger_intro_obs="the console as the developer",
    ledger=[
        ("measured", "Stopping production was refused; stopping development worked",
         "Signed in as the developer, I tried to stop the production instance and got an error saying the user isn't authorized to perform <code>ec2:StopInstances</code> because no identity-based policy allows it. Stopping the development instance went straight through.",
         "Attempted both stops in the EC2 console as the restricted user."),
        ("measured", "The simulator needed the tag in context to show the Allow",
         "With the resource left as <code>*</code>, the simulator returned <code>StopInstances</code> as implicitly denied (no matching statements) and <code>DeleteTags</code> as denied by one matching statement. Adding <code>ec2:ResourceTag/Env = development</code> to the simulation context turned <code>StopInstances</code> into <em>allowed</em>.",
         "Ran both actions in the IAM Policy Simulator, with and without the tag condition key in context."),
        ("observed", "Everything outside the policy defaulted to Access Denied",
         "Logged in as the developer, most dashboard panels showed Access Denied: anything the policy doesn't mention is denied by default.",
         "Browsed the console as the restricted user."),
        ("design", "A developer can't tag their way into production",
         "The explicit Deny on <code>CreateTags</code> and <code>DeleteTags</code> applies to every EC2 resource, and explicit Deny wins over any Allow. The simulator showed <code>DeleteTags</code> denied; I didn't try re-tagging the production instance as the user.",
         "Policy Simulator for <code>DeleteTags</code>; no live re-tag attempt."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(raw=IAM + "Screenshot from 2025-11-18 02-04-50.png", alt="NextWorkDevEnvironmentPolicy JSON with three statements: allow ec2:* on Env development, allow ec2:Describe*, deny CreateTags and DeleteTags", cap="The policy: three statements."),
        dict(raw=IAM + "Screenshot from 2025-11-18 11-44-30.png", alt="EC2 error: user is not authorized to perform ec2:StopInstances on the production instance because no identity-based policy allows it", cap="Stopping production: refused, with the reason."),
        dict(raw=IAM + "Screenshot from 2025-11-18 11-59-13.png", alt="EC2 console showing the development instance stopping successfully", cap="Stopping development: allowed."),
        dict(raw=IAM + "Screenshot from 2025-11-18 21-04-10.png", alt="IAM Policy Simulator: DeleteTags denied, StopInstances allowed once ec2:ResourceTag/Env is set to development", cap="The simulator with the tag in context."),
    ],
    broke=[
        ("I misread why the simulator said denied",
         "My first simulation of <code>StopInstances</code> came back denied, and I put it down to the Deny statement overriding the Allow. The simulator's own detail says something else: <em>implicitly denied, no matching statements</em>. With the resource set to <code>*</code> and no tag in the context, the Allow's condition can't match. Once I gave the simulation <code>ec2:ResourceTag/Env = development</code>, it showed allowed. The lesson stuck better than the policy did: read which kind of deny you got."),
    ],
    source="This was a guided lab with no standalone repo; the write-up and documentation live in my portfolio repo: <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/aws/iam-cloud-security\">Projects/aws/iam-cloud-security</a>. The follow-up on permission ceilings is the <a href=\"../iam-permissions-boundary/\">IAM permissions boundary</a> case study.",
    clone="aws iam simulate-principal-policy \\\n  --policy-source-arn arn:aws:iam::&lt;account&gt;:user/&lt;developer&gt; \\\n  --action-names ec2:StopInstances ec2:DeleteTags",
    stack="AWS IAM &middot; JSON policy authoring &middot; tag-based (ABAC-style) access &middot; condition keys &middot; users &amp; groups &middot; explicit vs implicit deny &middot; IAM Policy Simulator &middot; EC2 &middot; account aliases",
),
# ======================================================================
dict(
    slug="iam-permissions-boundary",
    card=dict(group="aws", eyebrow="AWS / Security", color="c-aws", status="Decommissioned",
              title="An IAM permissions boundary as a role ceiling",
              desc="The same widened policy, simulated before and after: CreatePolicyVersion goes from allowed to denied by the boundary. 8/8 predictions held."),
    title_tag="IAM Permissions Boundary",
    meta="Case study: a customer-managed policy attached as an IAM role's permissions boundary, proven with the policy simulator before and after, with every outcome predicted in advance.",
    eyebrow="AWS / Security",
    h1="An IAM permissions boundary as a ceiling on a role",
    standfirst="I attached a customer-managed policy to an IAM role as its permissions boundary and used the policy simulator to evaluate the same widened identity policy before and after: <code>iam:CreatePolicyVersion</code> went from allowed to denied by the boundary, without the widening ever being attached.",
    chip="Decommissioned",
    status="Both IAM resources were deleted at the end &mdash; the boundary removed first, then the policy and the role &mdash; and two <code>NoSuchEntity</code> reads confirmed they were gone. Nothing was ever attached to a principal that could act. The policy files and the full simulator output in the repo reproduce every result; IAM and the simulator cost nothing.",
    spec=[("Role", "BoundaryProofRole, inert"), ("Ceiling", "BoundaryProofCeiling, 7 actions"),
          ("Test", "simulate-principal-policy, twice"), ("Widening", "never attached, input only"),
          ("Predictions", "8/8, committed first"), ("Cost", "0.00 USD, ~90 minutes")],
    summary="Identity policies grow one reviewed change at a time, and one added statement &mdash; <code>iam:CreatePolicyVersion</code> &mdash; is enough to let a role rewrite the policy meant to restrict it. A permissions boundary sets a ceiling regardless of what gets attached later. I created an inert role, wrote <code>widened.json</code> as a proposed identity policy, and simulated it against the role with no boundary: <code>CreatePolicyVersion</code> against <code>BoundaryProofCeiling</code> came back <code>allowed</code>. Then I set <code>BoundaryProofCeiling</code> as the role's boundary and ran the identical simulation: <code>implicitDeny</code>, with <code>AllowedByPermissionsBoundary: false</code>.",
    how=[
        ("Why simulate instead of trying the actions?", "Firing real IAM mutations to see whether they're blocked changes the account you're trying to protect. <code>simulate-principal-policy --policy-source-arn &lt;role&gt; --policy-input-list file://widened.json</code> evaluates a proposed policy in the role's context, including its current boundary, and the widening never touches a live principal."),
        ("Why run the unbounded case at all?", "Without it, a later deny could just mean the action was never grantable, and the boundary would get credit it didn't earn. The role, policy, action and resource are identical in both runs; the boundary is the only thing that changes."),
        ("Why read <code>AllowedByPermissionsBoundary</code>, not just the decision?", "With the boundary attached, <code>CreatePolicyVersion</code> and <code>ListUsers</code> both return <code>implicitDeny</code>. Only the boundary flag (<code>false</code> versus <code>true</code>) shows the ceiling caused one and a missing grant caused the other."),
        ("Why is the role inert?", "Its trust policy names <code>ec2.amazonaws.com</code> with no instance profile and it has no attached policies, so it exists as a policy source and boundary target but nothing can assume it and it holds no permissions."),
    ],
    diagram=dict(
        h=560,
        aria="widened.json, a proposed identity policy, is simulated against BoundaryProofRole twice. Before: with no boundary, CreatePolicyVersion is allowed. Then put-role-permissions-boundary sets BoundaryProofCeiling as the role's boundary. After: CreatePolicyVersion is implicitly denied with AllowedByPermissionsBoundary false, GetRole stays allowed, five role mutations are explicitly denied, and ListUsers is implicitly denied. Predictions committed before the build are scored 8 of 8.",
        boxes=[dict(x=176, y=60, w=1052, h=470, k="aws", label="AWS ACCOUNT — IAM ONLY · NOTHING ATTACHED TO AN ACTIVE PRINCIPAL")],
        nodes=[
            dict(id="pred", x=16, y=420, w=136, k="neu", icon="doc", slot="doc", t="predictions", s="8 rows, CSV", tag="committed first"),
            dict(id="wid", x=16, y=200, w=136, k="ctl", icon="doc", slot="json", t="widened.json", s="proposed policy", tag="input only"),
            dict(id="role", x=210, y=200, w=200, k="aws", icon="key", slot="iam", t="BoundaryProofRole", s="trusts ec2 · no profile", tag="no policies"),
            dict(id="ceil", x=210, y=420, w=200, k="aws", icon="shield", slot="iam", t="BoundaryProofCeiling", s="7 reviewed IAM actions", tag="no CreatePolicyVersion"),
            dict(id="sim", x=470, y=200, w=210, k="obs", icon="gate", slot="iam", t="Policy simulator", s="simulate-principal-policy", tag="run twice"),
            dict(id="bef", x=760, y=96, w=220, k="neu", icon="x", slot="iam", t="Before: no boundary", s="CreatePolicyVersion", tag="allowed"),
            dict(id="aft", x=760, y=304, w=220, k="obs", icon="shield", slot="iam", t="After: ceiling attached", s="AllowedByPermissionsBoundary", tag="false → implicitDeny"),
            dict(id="score", x=1030, y=304, w=180, k="obs", icon="gate", slot="assert", t="Scored", s="expected vs simulated", tag="8 / 8"),
        ],
        edges=[
            dict(**{"from": "wid", "to": "role"}, k="ctl", mech="--policy-input-list", what="A proposed identity policy, string-encoded, never attached."),
            dict(**{"from": "role", "to": "sim"}, k="aws", mech="--policy-source-arn", what="The simulator evaluates in the role's context, including its boundary."),
            dict(**{"from": "sim", "to": "bef"}, k="neu", ss="r", ts="l", so=-20, mech="run 1", what="No boundary: the identity policy decides alone, and <code>CreatePolicyVersion</code> is <code>allowed</code>."),
            dict(**{"from": "ceil", "to": "role"}, k="aws", mech="put-role-permissions-boundary", what="Sets the ceiling; it grants nothing by itself."),
            dict(**{"from": "sim", "to": "aft"}, k="obs", ss="r", ts="l", so=20, mech="run 2", what="Same input. <code>GetRole</code> allowed; 5 mutations <code>explicitDeny</code>; <code>ListUsers</code> and <code>CreatePolicyVersion</code> <code>implicitDeny</code>."),
            dict(**{"from": "aft", "to": "score"}, k="obs", mech="compare", what="All eight decisions matched what was written down before the build."),
            dict(**{"from": "pred", "to": "score"}, k="neu", dash=True, pts=[(152, 464), (192, 464), (192, 516), (1120, 516), (1120, 396)], mech="git history", what="The predictions predate the role and policy in the repo's history."),
        ],
    ),
    figcaption="The proof as it ran. Arrows 3 and 5 are the same simulation; arrow 4 happens between them and is the only difference. Arrow 7 is why the 8/8 means something &mdash; the expected outcomes were committed before anything existed to test.",
    legend=[("c-neu", "Inputs &amp; the unbounded result", "predictions, the before run"), ("c-ctl", "The proposal", "widened.json"),
            ("c-aws", "IAM resources", "the role and the ceiling"), ("c-obs", "Evaluation", "simulator, after run, score"),
            ("line:c-aws", "Configuration", "boundary and policy source"), ("line:c-obs", "Bounded result", "and its scoring"),
            ("line:c-neu:dashed", "Committed first", "predictions in git")],
    reach_title="What existed, and when",
    reach=[("During", "one role nothing could assume, and one customer-managed policy used only as its boundary."),
           ("Never", "the widened policy attached to anything; it was simulator input only."),
           ("Now", "nothing. Both were deleted and confirmed with <code>NoSuchEntity</code>.")],
    ledger_intro_obs="the simulator output",
    ledger=[
        ("measured", "<code>CreatePolicyVersion</code> flipped from allowed to denied by the boundary",
         "Against <code>BoundaryProofCeiling</code> as the resource, the unbounded run returned <code>allowed</code>. After <code>put-role-permissions-boundary</code>, the identical run returned <code>implicitDeny</code> with <code>AllowedByPermissionsBoundary: false</code>. Nothing else changed between the runs.",
         "<code>simulate-principal-policy</code> before and after; full JSON output in <code>results/</code>."),
        ("measured", "The ceiling composes with Deny and grants nothing on its own",
         "With the boundary attached, <code>iam:GetRole</code> (in both) stayed allowed; the five role mutations, including <code>DeleteRolePermissionsBoundary</code>, were <code>explicitDeny</code> with the boundary flag <code>true</code>; and <code>iam:ListUsers</code>, inside the ceiling but granted by nothing, was <code>implicitDeny</code> with the flag <code>true</code>.",
         "Same bounded simulation, reading <code>EvalDecision</code> and <code>PermissionsBoundaryDecisionDetail</code> per action."),
        ("measured", "Eight predictions, eight matches",
         "All eight decisions went into <code>predictions.csv</code> and were committed before the role or policy existed, then scored against the simulator: 8/8.",
         "Compared the committed predictions with the simulator output."),
        ("observed", "Teardown left nothing behind",
         "The boundary came off first &mdash; IAM won't delete a policy still in use as one &mdash; then the policy and role were deleted, and <code>get-role</code> and <code>get-policy</code> both returned <code>NoSuchEntity</code>. That output lives in a screenshot, not the repo.",
         "Ran the two reads after deletion (screenshot below)."),
        ("design", "The role couldn't have been used during the test",
         "Its trust policy names EC2 with no instance profile, and it had no attached or inline policies. I didn't try to assume it.",
         "Reviewed <code>trust.json</code> and the role's attachments."),
    ],
    proof_note="From the simulator output and the account",
    shots=[
        dict(raw=BP + "Screenshot from 2026-09-14 12-15-41.png", alt="02-baseline.json showing EvalDecision allowed for iam:CreatePolicyVersion", cap="Before the boundary: <code>CreatePolicyVersion</code> allowed."),
        dict(raw=BP + "Screenshot from 2026-09-14 13-48-33.png", alt="readout.html showing 8/8 and the decision-rule table", cap="After: every case scored, limits stated."),
        dict(raw=BP + "Screenshot from 2026-09-14 14-05-20.png", alt="get-role and get-policy both failing with NoSuchEntity", cap="Teardown: both reads return <code>NoSuchEntity</code>."),
        dict(raw=BP + "Screenshot from 2026-09-12 21-04-08.png", alt="docs folder with build-plan, decisions, requirements, source-map, TASKS and topology", cap="Design files written before the build."),
    ],
    broke=[
        ("<code>--policy-input-list</code> wants strings, not objects",
         "Passing the widened policy as an ordinary JSON document failed. The CLI expects a list of policy <em>strings</em>, so <code>widened.json</code> became a one-element array holding the escaped document. That took longer than any other step."),
        ("The seal tag landed one commit early",
         "At close-out, <code>git tag -a v1.0.0</code> failed with <code>tag 'v1.0.0' already exists</code>: it had been created at the adjudication commit, before teardown. That contradicts the closing line of <code>results/check-manifest.md</code>. I left the tag where it landed and documented the discrepancy rather than moving it."),
        ("The teardown proof is a screenshot",
         "Every other check pasted its full output into <code>results/</code>. The two <code>NoSuchEntity</code> reads were only captured on screen, which makes them the weakest evidence in the project."),
    ],
    source="The <code>boundary.json</code> ceiling, the <code>trust.json</code> trust policy, the string-encoded <code>widened.json</code>, full simulator output under <code>results/</code>, and the requirements, decision records and topology under <code>docs/</code> live here: <a href=\"https://github.com/kingswanzy2020/iam-boundary-proof\">kingswanzy2020/iam-boundary-proof</a>. The published copy redacts the account ID to <code>111122223333</code>.",
    clone="git clone https://github.com/kingswanzy2020/iam-boundary-proof.git",
    stack="AWS IAM &middot; permissions boundaries &middot; IAM policy evaluation logic &middot; simulate-principal-policy &middot; explicit vs implicit vs boundary deny &middot; privilege-escalation analysis &middot; JSON policy authoring &middot; AWS CLI &middot; dependency-ordered teardown &middot; Architecture Decision Records",
),
# ======================================================================
dict(
    slug="s3-static-website",
    card=dict(group="aws", eyebrow="AWS", color="c-aws", status="Guided lab",
              title="A static website on S3, access model and all",
              desc="A 403 worked through properly, and a bucket policy that stops even me from deleting the index page."),
    title_tag="Static Website on S3",
    meta="Case study: a static website served directly from an Amazon S3 bucket, with Block Public Access, object ACLs and a bucket policy configured deliberately.",
    eyebrow="AWS",
    h1="A static website on S3, with the access model done deliberately",
    standfirst="I served a website straight from an S3 bucket in Seoul, worked through the <code>403 Forbidden</code> that every first attempt hits, and added a bucket policy that refuses to delete the site's <code>index.html</code> &mdash; even for me.",
    chip="Guided lab",
    status=lab_status("the site files in the repo, a bucket and one policy recreate it."),
    spec=[("Bucket", "nextwork-website-project-fap"), ("Region", "ap-northeast-2 (Seoul)"),
          ("Serving", "S3 static website endpoint"), ("Public read", "object ACLs"),
          ("Guardrail", "Deny delete on index.html"), ("Time", "about 1.5 hours")],
    summary="I created the bucket in Seoul, the region closest to me, uploaded <code>index.html</code> and a folder of assets, and turned on static website hosting with <code>index.html</code> as the index document. That produced a bucket endpoint URL &mdash; which returned <code>403 Forbidden</code>, because objects are private by default. I disabled Block Public Access, enabled ACLs and made the objects public, and the site loaded. Then I added a bucket policy denying deletion of <code>index.html</code> and tried to delete it myself.",
    how=[
        ("Why did the endpoint return 403 at first?", "Enabling website hosting doesn't make anything public. Every object was still private, and Block Public Access was on as the first layer. Turning that off only stops blocking &mdash; something still has to grant read access, which here was a public-read ACL on the objects."),
        ("ACLs or a bucket policy?", "ACLs are per object: good for granting read on specific files. A bucket policy is one JSON document for the whole bucket, saying who can do what to which objects. I used ACLs for the public read and a bucket policy for the guardrail."),
        ("Why a policy that blocks the owner?", "An explicit Deny applies to every principal, including the account that owns the bucket. A deny on deleting <code>index.html</code> turns an easy mistake &mdash; deleting the page that is the site &mdash; into one that has to be undone on purpose first."),
    ],
    diagram=dict(
        h=460,
        aria="A visitor requests the S3 static website endpoint, which serves index.html and its assets from the bucket. Block Public Access was turned off and the objects made public with ACLs. A bucket policy denies deleting index.html, which refused my own delete attempt.",
        boxes=[dict(x=176, y=60, w=1052, h=370, k="aws", label="AWS — S3 · ap-northeast-2 (SEOUL)")],
        nodes=[
            dict(id="vis", x=16, y=110, w=136, k="neu", icon="browser", slot="browser", t="Visitor", s="bucket endpoint", tag="HTTP GET"),
            dict(id="ep", x=210, y=110, w=200, k="aws", icon="globe", slot="s3", t="Website endpoint", s="index document set", tag="static hosting on"),
            dict(id="bkt", x=470, y=110, w=230, k="aws", icon="disk", slot="s3", t="S3 bucket", s="nextwork-website-project-fap", tag="Seoul"),
            dict(id="obj", x=760, y=110, w=230, k="app", icon="doc", slot="html", t="index.html + assets", s="58.8 KB page + folder", tag="public-read ACL"),
            dict(id="bpa", x=470, y=290, w=230, k="aws", icon="shield", slot="s3", t="Block Public Access", s="first layer", tag="turned off"),
            dict(id="pol", x=760, y=290, w=230, k="aws", icon="lock", slot="s3", t="Bucket policy", s="Deny s3:DeleteObject", tag="index.html, everyone"),
            dict(id="me", x=1040, y=290, w=170, k="neu", icon="user", slot="engineer", t="Me, as owner", s="delete index.html", tag="refused"),
        ],
        edges=[
            dict(**{"from": "vis", "to": "ep"}, k="req", mech="HTTP", what="The bucket endpoint URL S3 generated when hosting was enabled."),
            dict(**{"from": "ep", "to": "bkt"}, k="req", mech="index document", what="Maps <code>/</code> to <code>index.html</code>."),
            dict(**{"from": "bkt", "to": "obj"}, k="req", mech="GetObject", what="Allowed once the objects carried a public-read ACL; <code>403</code> before."),
            dict(**{"from": "bpa", "to": "bkt"}, k="aws", dash=True, mech="account guard", what="On by default; it had to be off before any public grant counted."),
            dict(**{"from": "pol", "to": "obj"}, k="aws", dash=True, mech="explicit Deny", what="No principal may delete <code>index.html</code>."),
            dict(**{"from": "me", "to": "pol"}, k="neu", mech="DeleteObject", what="My own delete failed: <em>Failed to delete, Access denied</em>."),
        ],
    ),
    figcaption="The access model as configured. Arrows 4 and 5 are the two layers that confuse everyone: one that blocks public access account-wide, one that grants or denies inside the bucket. Arrow 6 is me checking the second one actually applies to me.",
    legend=[("c-neu", "People", "a visitor, me"), ("c-aws", "S3 configuration", "endpoint, bucket, guards"), ("c-app", "Content", "the site files"),
            ("line:c-app", "Request path", "visitor to object"), ("line:c-aws:dashed", "Access control", "block, grant, deny"),
            ("line:c-neu", "Delete attempt", "refused")],
    reach=[("Public", "the bucket website endpoint, plain HTTP, read-only."),
           ("Protected", "<code>index.html</code>, from deletion by anyone."),
           ("Not used", "CloudFront or HTTPS &mdash; the <a href=\"../three-tier-serverless/\">three-tier build</a> adds both.")],
    ledger_intro_obs="the bucket and its endpoint",
    ledger=[
        ("measured", "The endpoint went from 403 to the live site",
         "The first visit to the bucket endpoint returned <code>403 Forbidden</code> (<code>AccessDenied</code>). After turning off Block Public Access, enabling ACLs and making the objects public, the same URL served the site.",
         "Loaded the endpoint URL before and after each change."),
        ("measured", "The policy stopped me deleting <code>index.html</code>",
         "I tried to delete <code>index.html</code> from the console as the bucket owner. S3 reported <em>Failed to delete: 1 object</em>, with <em>Access denied</em> as the error.",
         "Attempted the delete in the console after attaching the policy."),
        ("design", "Only reads are public",
         "The ACLs grant public read; nothing grants public write. I didn't try writing anonymously to confirm it's refused.",
         "Reviewed the object ACLs. Not tested."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(pdf="legendary-aws-host-a-website-on-s3/i-008.png", name="hosting.jpg", alt="S3 static website hosting enabled with index.html as the index document", cap="Static hosting on, <code>index.html</code> as the index document."),
        dict(pdf="legendary-aws-host-a-website-on-s3/i-010.png", name="forbidden.jpg", alt="403 Forbidden AccessDenied returned by the bucket website endpoint", cap="The first visit: <code>403 Forbidden</code>."),
        dict(pdf="legendary-aws-host-a-website-on-s3/i-012.png", name="site-live.jpg", alt="The NextWork landing page served from the S3 website endpoint", cap="The site, once the objects were public."),
        dict(pdf="legendary-aws-host-a-website-on-s3/i-014.png", name="delete-denied.jpg", alt="S3 Delete objects status: failed to delete index.html with Access denied", cap="My own delete, refused by the bucket policy."),
    ],
    broke=[
        ("<code>403 Forbidden</code> on a bucket I'd just made a website",
         "Website hosting and public access are separate switches. Hosting was on; every object was still private, and Block Public Access was still on above them. I turned off the block, enabled ACLs and granted public read per object &mdash; deliberately, one layer at a time, instead of opening the whole bucket."),
    ],
    source="This was a guided lab, so there's no standalone repo; the site files are in my portfolio repo under <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/aws/s3-static-website\">Projects/aws/s3-static-website</a>.",
    clone="aws s3 mb s3://YOUR_BUCKET --region ap-northeast-2\naws s3 website s3://YOUR_BUCKET --index-document index.html",
    stack="Amazon S3 &middot; static website hosting &middot; Block Public Access &middot; object ACLs &middot; bucket policies &middot; explicit deny",
),
# ======================================================================
dict(
    slug="aurora-web-app",
    card=dict(group="aws", eyebrow="AWS / Databases", color="c-aws", status="Guided lab",
              title="A PHP app on EC2 writing to Amazon Aurora",
              desc="An Aurora MySQL cluster wired to an EC2 web host, every write checked again from the MySQL CLI."),
    title_tag="Web App on Amazon Aurora",
    meta="Case study: an Aurora MySQL cluster provisioned alongside an EC2 web host, and an Apache/PHP app that writes to it, with every write verified independently through the MySQL CLI.",
    eyebrow="AWS / Databases",
    h1="A PHP web app on EC2 writing to Amazon Aurora",
    standfirst="I provisioned an Aurora MySQL cluster together with the EC2 instance that talks to it, put an Apache and PHP app on the instance that writes form input to the database, and checked every write a second time from the MySQL command line.",
    chip="Guided lab",
    status=lab_status("the cluster settings and the PHP page rebuild it. This page covers both parts of the lab: the database and its host, then the app."),
    spec=[("Database", "Aurora MySQL 3.10 (MySQL 8.0)"), ("Template", "Dev/Test"),
          ("Host", "EC2 t3.micro, Amazon Linux 2023"), ("Stack", "Apache · PHP · php-mysqli"),
          ("Networking", "RDS \"connect to EC2\" security groups"), ("Verified", "MySQL CLI (mariadb105)")],
    summary="I started creating an Aurora cluster, stopped halfway to launch the EC2 instance it would serve &mdash; with a new key pair, a public IP and its own security group &mdash; and then finished the cluster with <em>Connect to an EC2 compute resource</em> pointed at that instance. On the instance I installed Apache, PHP, <code>php-mysqli</code> and the <code>mariadb105</code> client, put the connection details in <code>dbinfo.inc</code>, and wrote a sample PHP page that inserts a name and address and lists every row. Then I logged into the database with the MySQL CLI and checked the tables and rows directly.",
    how=[
        ("Why stop halfway through creating the database?", "The cluster's connectivity settings want a compute resource to connect to. Launching the instance first meant I could pick it, and RDS added a security group to each side with an inbound rule letting that instance &mdash; and only that instance &mdash; reach the database."),
        ("Why Aurora rather than MySQL on the instance?", "Running MySQL on the VM means owning patching, replication, failover and backups. Aurora keeps MySQL compatibility and hands those to AWS; a cluster has a writer and can add readers that spread <code>SELECT</code> load. This build used the Dev/Test template, so I'm describing the topology Aurora offers, not a replica I load-tested."),
        ("Why check the data with the CLI when the page already shows it?", "The page displaying a row only proves the page and the database agree with each other. Logging in with the MySQL client and running <code>SHOW DATABASES</code>, <code>USE sample</code> and <code>SHOW TABLES</code> checks the data where it actually lives."),
        ("Why <code>dbinfo.inc</code>?", "It keeps the endpoint, user and password out of the page code. It doesn't make them secret &mdash; it's still a plaintext file on the instance. Secrets Manager would be the next step; this lab stops at separation."),
    ],
    diagram=dict(
        h=520,
        aria="A browser posts a form to Apache and PHP on an EC2 instance. PHP reads connection details from dbinfo.inc and inserts the row into the Aurora MySQL cluster through php-mysqli. Security groups created by RDS's connect-to-EC2 option allow only that instance to reach the database. I connect over SSH with the key pair and query the same database with the MySQL CLI.",
        boxes=[dict(x=176, y=60, w=1052, h=430, k="aws", label="AWS ACCOUNT — EC2 · AURORA (RDS) · SECURITY GROUPS"),
               dict(x=196, y=90, w=520, h=380, k="app", dash="3 4", sw=1.1, fs=10, label="EC2 WEB HOST — t3.micro · AMAZON LINUX 2023")],
        nodes=[
            dict(id="bro", x=16, y=130, w=136, k="neu", icon="browser", slot="browser", t="Browser", s="sample page", tag="form POST"),
            dict(id="eng", x=16, y=330, w=136, k="neu", icon="user", slot="engineer", t="Me", s="key pair, chmod 400", tag="SSH"),
            dict(id="php", x=226, y=130, w=210, k="app", icon="code", slot="php", t="Apache + PHP", s="php-mysqli", tag="inserts + lists rows"),
            dict(id="inc", x=486, y=130, w=200, k="neu", icon="doc", slot="doc", t="dbinfo.inc", s="endpoint · user · db", tag="outside page code"),
            dict(id="cli", x=226, y=330, w=210, k="neu", icon="terminal", slot="mysql", t="MySQL CLI", s="mariadb105 client", tag="independent check"),
            dict(id="db", x=800, y=130, w=230, k="app", icon="db", slot="aurora", t="Aurora MySQL", s="3.10 · Dev/Test", tag="database sample"),
            dict(id="sg", x=800, y=330, w=230, k="aws", icon="shield", slot="vpc", t="Security groups", s="added by connect-to-EC2", tag="this instance only"),
        ],
        edges=[
            dict(**{"from": "bro", "to": "php"}, k="req", mech="HTTP POST", what="Name and address from the form."),
            dict(**{"from": "inc", "to": "php"}, k="neu", dash=True, mech="include", what="Connection details, kept out of the page source."),
            dict(**{"from": "php", "to": "db"}, k="data", ss="t", ts="t", my=112, mech="mysqli INSERT", what="Writes the row, then reads every row back for the page."),
            dict(**{"from": "eng", "to": "cli"}, k="neu", mech="SSH", what="<code>ssh -i</code> with the key locked to owner-read-only."),
            dict(**{"from": "cli", "to": "db"}, k="data", pts=[(436, 374), (758, 374), (758, 186), (796, 186)], mech="SQL", what="<code>SHOW DATABASES</code>, <code>USE sample</code>, <code>SHOW TABLES</code>, then the rows."),
            dict(**{"from": "sg", "to": "db"}, k="aws", dash=True, ss="r", ts="r", mx=1080, mech="inbound rule", what="Allows the database port from the instance's security group, nothing else."),
        ],
    ),
    figcaption="Both halves of the lab. Arrow 3 is the app's view of the data; arrow 5 is mine, through a different client. When they agree, the write really happened.",
    legend=[("c-neu", "People, config &amp; tools", "browser, me, dbinfo.inc, the CLI"), ("c-app", "App &amp; database", "PHP and Aurora"),
            ("c-aws", "Network control", "the security groups"),
            ("line:c-app", "Request", "browser to PHP"), ("line:dg-line", "SQL", "app and CLI to Aurora"),
            ("line:c-aws:dashed", "Access rule", "only this instance")],
    reach=[("Public", "the EC2 instance over HTTP, and SSH with the key pair."),
           ("Private", "the Aurora cluster, reachable only from the instance's security group."),
           ("Caveat", "the database password sits in <code>dbinfo.inc</code> on the instance, in plaintext.")],
    ledger_intro_obs="the page and the database",
    ledger=[
        ("measured", "Rows written by the page showed up in the database",
         "I added entries through the form; the page listed them with IDs 1 to 3. Logged in with the MySQL CLI, the <code>sample</code> database was there with an <code>EMPLOYEES</code> table holding the same rows.",
         "Submitted the form, then <code>SHOW DATABASES</code>, <code>USE sample</code>, <code>SHOW TABLES</code> and a query in the CLI."),
        ("observed", "SSH only worked once the key was owner-read-only",
         "<code>ssh -i</code> with the new key pair connected after I removed all permissions for group and others on the key file.",
         "Connected from my terminal to the instance's public address."),
        ("observed", "RDS wired the two security groups itself",
         "Choosing <em>Connect to an EC2 compute resource</em> and picking the instance made RDS add a security group to the instance and one to the database, with an inbound rule allowing the instance.",
         "Read the connectivity settings during database creation."),
        ("design", "Nothing else can reach the database",
         "The database's inbound rule names the instance's security group. I didn't try connecting from anywhere else.",
         "Reviewed the security group rules. Not adversarially tested."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(pdf="legendary-aws-databases-aurora/i-006.png", name="aurora-engine.jpg", alt="RDS create database: full configuration, Aurora (MySQL Compatible), Aurora MySQL 3.10.3 compatible with MySQL 8.0.42, Dev/Test template", cap="Aurora MySQL 3.10, Dev/Test template."),
        dict(pdf="legendary-aws-databases-aurora/i-010.png", name="connect-ec2.jpg", alt="RDS connectivity: Connect to an EC2 compute resource, with the web server instance selected", cap="<em>Connect to an EC2 compute resource</em>, pointed at the web host."),
        dict(pdf="legendary-aws-databases-webapp/i-001.png", name="sample-page.jpg", alt="Sample PHP page with name and address fields and a table of three stored rows", cap="The PHP page listing rows it wrote."),
        dict(pdf="legendary-aws-databases-webapp/i-011.png", name="mysql-cli.jpg", alt="MySQL CLI: SHOW DATABASES listing sample, USE sample, SHOW TABLES listing EMPLOYEES", cap="The same data from the MySQL CLI."),
    ],
    broke=[
        ("The database wanted a server that didn't exist yet",
         "Halfway through creating the cluster, the connectivity step needed an EC2 instance to connect to. I stopped, launched the instance with its own key pair and security group, and came back. In hindsight it's the right order anyway: the database exists to serve something."),
    ],
    source="This was a guided lab with no standalone repo; the write-ups for <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/aws/aurora-database-ec2\">the cluster</a> and <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/aws/aurora-web-app\">the app</a> live in my portfolio repo.",
    clone="sudo dnf install -y httpd php php-mysqli mariadb105\nmysql -h &lt;cluster-endpoint&gt; -u admin -p\nSHOW DATABASES; USE sample; SHOW TABLES;",
    stack="Amazon Aurora (MySQL) &middot; RDS cluster topology &middot; EC2 &middot; SSH key pairs &middot; security groups &middot; Apache &middot; PHP + mysqli &middot; MariaDB client &middot; SQL verification",
),
]
