def lab_status(rebuild):
    return ("I built this in my own AWS account as a guided NextWork lab. I'm not pointing you at a live endpoint &mdash; "
            "the screenshots below were captured during the build, and " + rebuild + " Everything below is in the past tense for that reason.")


SL = "aws/serverless-lead-capture/Images/"

PAGES = [
# ======================================================================
dict(
    slug="terraform-s3",
    card=dict(group="iac", eyebrow="Infrastructure as Code", color="c-aws", status="Guided lab",
              title="Terraform fundamentals: a locked-down S3 bucket",
              desc="init, plan, apply &mdash; a private bucket, an ownership rule and an uploaded object, all from one main.tf."),
    title_tag="S3 Buckets with Terraform",
    meta="Case study: an S3 bucket, its public-access block, an ownership control and an uploaded object, declared in Terraform and created with init, plan and apply.",
    eyebrow="Infrastructure as Code",
    h1="Terraform fundamentals: a locked-down S3 bucket from code",
    standfirst="I declared an S3 bucket, its public-access block, an ownership rule and an uploaded object in one <code>main.tf</code>, and created every one of them with <code>terraform init</code>, <code>plan</code> and <code>apply</code> instead of the console.",
    chip="Guided lab",
    status=lab_status("<code>terraform apply</code> against the same <code>main.tf</code> recreates all of it."),
    spec=[("Tool", "Terraform, hashicorp/aws 6.34.0"), ("Region", "ap-northeast-2 (Seoul)"),
          ("Resources", "bucket, access block, ownership, object"), ("Public access", "blocked at creation"),
          ("Ownership", "BucketOwnerPreferred"), ("Auth", "AWS CLI access keys")],
    summary="<code>main.tf</code> started with three blocks: the AWS provider in <code>ap-northeast-2</code>, an <code>aws_s3_bucket</code>, and an <code>aws_s3_bucket_public_access_block</code> with all four switches on. <code>terraform init</code> downloaded the AWS provider and wrote the lock file, <code>plan</code> showed exactly what would be created, and <code>apply</code> created it. Then I extended it from the registry docs: an <code>aws_s3_bucket_ownership_controls</code> block so objects belong to the bucket owner whoever uploads them, and an <code>aws_s3_object</code> that uploads an image. Each change was another plan and apply.",
    how=[
        ("Why <code>init</code>, then <code>plan</code>, then <code>apply</code>?", "<code>init</code> downloads the provider plugin, sets up where state is kept, and writes <code>.terraform.lock.hcl</code> so the next run picks the same provider version &mdash; nothing else works until it has run. <code>plan</code> is the review: it says what will be created, changed or destroyed before anything happens. <code>apply</code> then does exactly that."),
        ("Why block public access in the same file as the bucket?", "So the bucket is private from the moment it exists, not patched afterwards. The access block references the bucket by <code>aws_s3_bucket.my_bucket.id</code>, which is also how Terraform knows to create the bucket first."),
        ("Why add an ownership rule?", "Without it, an object uploaded by another account can stay owned by that account even inside my bucket. <code>BucketOwnerPreferred</code> makes the bucket owner the object owner, so permissions on the bucket actually cover what's in it."),
    ],
    diagram=dict(
        h=560,
        aria="An engineer writes main.tf. The Terraform CLI reads it, downloads the hashicorp/aws provider from the registry during init and writes local state. Apply creates an S3 bucket in ap-northeast-2; the public access block, the ownership controls and the uploaded object each reference the bucket by ID.",
        boxes=[dict(x=666, y=60, w=562, h=470, k="aws", label="AWS — S3 · ap-northeast-2 (SEOUL)")],
        nodes=[
            dict(id="eng", x=16, y=110, w=136, k="neu", icon="user", slot="engineer", t="Engineer", s="AWS CLI keys", tag="writes HCL"),
            dict(id="tfc", x=192, y=110, w=160, k="ctl", icon="code", slot="terraform", t="main.tf", s="provider + 4 resources", tag="HCL"),
            dict(id="tf", x=400, y=110, w=200, k="ctl", icon="terminal", slot="terraform", t="Terraform CLI", s="init · plan · apply", tag="reviewed plan"),
            dict(id="state", x=192, y=290, w=160, k="obs", icon="doc", slot="terraform", t="State", s="terraform.tfstate", tag="+ lock file"),
            dict(id="reg", x=440, y=290, w=180, k="neu", icon="box", slot="terraform", t="Terraform Registry", s="hashicorp/aws", tag="v6.34.0"),
            dict(id="bkt", x=700, y=110, w=220, k="aws", icon="disk", slot="s3", t="S3 bucket", s="nextwork-unique-bucket-fap-…", tag="aws_s3_bucket"),
            dict(id="pab", x=980, y=110, w=226, k="aws", icon="shield", slot="s3", t="Public access block", s="all four set to true", tag="private from creation"),
            dict(id="own", x=980, y=280, w=226, k="aws", icon="key", slot="s3", t="Ownership controls", s="BucketOwnerPreferred", tag="registry-doc extension"),
            dict(id="obj", x=700, y=430, w=220, k="app", icon="doc", slot="s3", t="S3 object", s="key image.png", tag="aws_s3_object"),
        ],
        edges=[
            dict(**{"from": "eng", "to": "tfc"}, k="ctl", mech="write", what="Provider, bucket, access block; later the ownership rule and the object."),
            dict(**{"from": "tfc", "to": "tf"}, k="ctl", mech="read config", what="Terraform builds its plan from the file."),
            dict(**{"from": "tf", "to": "reg"}, k="neu", ss="b", ts="t", so=35, to_off=-20, mech="terraform init", what="Downloads the AWS provider and pins it in <code>.terraform.lock.hcl</code>."),
            dict(**{"from": "tf", "to": "state"}, k="obs", dash=True, ss="b", ts="r", so=-70, mech="state write", what="Records what exists so the next plan is a diff, not a guess."),
            dict(**{"from": "tf", "to": "bkt"}, k="aws", mech="terraform apply", what="Creates exactly what the reviewed plan showed, starting with the bucket."),
            dict(**{"from": "pab", "to": "bkt"}, k="aws", dash=True, mech="bucket ID ref", what="<code>aws_s3_bucket.my_bucket.id</code> &mdash; the reference is also the dependency order."),
            dict(**{"from": "own", "to": "bkt"}, k="aws", dash=True, ss="l", ts="b", to_off=50, mech="bucket ID ref", what="Applied on a second plan and apply."),
            dict(**{"from": "obj", "to": "bkt"}, k="app", dash=True, ss="t", ts="b", so=-50, to_off=-50, mech="bucket ID ref", what="Uploads <code>image.png</code> from a local path; checked by downloading it back."),
        ],
    ),
    figcaption="The configuration as it ran. Arrows 6 to 8 point the other way from what you might expect: each resource names the bucket, and that reference is how Terraform knew to create the bucket first.",
    legend=[("c-neu", "Engineer &amp; registry", "me, the provider source"), ("c-ctl", "Code &amp; CLI", "main.tf, Terraform"),
            ("c-obs", "State", "what Terraform remembers"), ("c-aws", "AWS resources", "the bucket and its settings"), ("c-app", "Content", "the uploaded object"),
            ("line:c-ctl", "Workflow", "write, read, plan"), ("line:c-aws", "Apply", "create in AWS"),
            ("line:c-aws:dashed", "Reference", "resource to bucket")],
    reach=[("Public", "nothing; all four public-access switches were on from creation."),
           ("Private", "the bucket and <code>image.png</code>, readable by my account."),
           ("Local", "state and the lock file, on my machine &mdash; fine for one person, which is what the GitOps pipeline later replaced with S3 and DynamoDB.")],
    ledger_intro_obs="the AWS console",
    ledger=[
        ("measured", "The uploaded object came back identical",
         "After adding the <code>aws_s3_object</code> block and applying again, I found the object in the S3 console, downloaded it, and compared it with the local file.",
         "Downloaded <code>image.png</code> from the bucket and compared it with the source."),
        ("observed", "One apply created a private bucket in Seoul",
         "<code>terraform init</code> installed <code>hashicorp/aws</code> v6.34.0 and created the lock file; after <code>apply</code>, the S3 console listed <code>nextwork-unique-bucket-fap-5638489349</code> in Asia Pacific (Seoul).",
         "Read the <code>init</code> output and the S3 bucket list."),
        ("design", "Objects belong to the bucket owner whoever uploads them &mdash; untested",
         "The ownership control applied cleanly on the second apply. I only ever uploaded from my own account, so I haven't seen it take ownership of an object someone else wrote.",
         "Reviewed the applied configuration. No cross-account upload was tried."),
        ("design", "Nothing about this bucket was clicked into existence",
         "Every setting is in <code>main.tf</code>, so the whole thing recreates from one apply. I didn't destroy and recreate it to prove the round trip.",
         "Reviewed <code>main.tf</code> against the console settings. No destroy/recreate test."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(pdf="legendary-aws-devops-terraform1/i-011.png", name="main-tf.jpg", alt="main.tf with the AWS provider in ap-northeast-2, an S3 bucket, a public access block with all four settings true, and ownership controls BucketOwnerPreferred", cap="<code>main.tf</code> with the ownership rule added."),
        dict(pdf="legendary-aws-devops-terraform1/i-014.png", name="terraform-init.jpg", alt="terraform init output installing hashicorp/aws v6.34.0 and creating .terraform.lock.hcl", cap="<code>terraform init</code>: provider installed, lock file written."),
        dict(pdf="legendary-aws-devops-terraform1/i-017.png", name="bucket.jpg", alt="S3 console listing the bucket in Asia Pacific (Seoul) ap-northeast-2", cap="The bucket, created by <code>apply</code>."),
        dict(pdf="legendary-aws-devops-terraform1/i-020.png", name="s3-object.jpg", alt="aws_s3_object resource uploading image.png into the bucket by reference to the bucket ID", cap="The object block, referencing the bucket by ID."),
    ],
    broke=[
        ("Reading the provider docs was the actual work",
         "Nothing failed loudly here. The slow part was finding the right resource and arguments in the Terraform registry for the ownership rule &mdash; the config is short because the documentation reading was long."),
    ],
    source="The Terraform configuration, its variables and the committed provider lock file live here: <a href=\"https://github.com/kingswanzy2020/nextwork-terraform-s3\">kingswanzy2020/nextwork-terraform-s3</a>. The same lifecycle at scale is the <a href=\"../terraform-gitops/\">Terraform GitOps pipeline</a>.",
    clone="git clone https://github.com/kingswanzy2020/nextwork-terraform-s3.git\nterraform init &amp;&amp; terraform plan &amp;&amp; terraform apply",
    stack="Terraform &middot; HCL &middot; provider configuration &middot; state &amp; lock files &middot; Amazon S3 &middot; public access blocks &middot; ownership controls &middot; AWS CLI",
),
# ======================================================================
dict(
    slug="serverless-lead-capture",
    card=dict(group="aws", eyebrow="AWS / Serverless", color="c-aws", status="Decommissioned",
              title="Serverless lead capture at a real domain",
              desc="S3, CloudFront and ACM in front; API Gateway, Lambda, SES and DynamoDB behind &mdash; no servers, run at kahmedt.com."),
    title_tag="Serverless Lead Capture",
    meta="Case study: an eBook lead-capture site at a custom domain, served by S3 and CloudFront over HTTPS, with API Gateway, Lambda, SES and DynamoDB handling each submission.",
    eyebrow="AWS / Serverless",
    h1="A serverless lead-capture site on a real domain",
    standfirst="I built an eBook download site for a small business at <code>kahmedt.com</code>: a static site on S3 behind CloudFront over HTTPS, and a form that calls API Gateway and a Lambda function, which emails the owner through SES and stores the lead in DynamoDB.",
    chip="Decommissioned",
    status="This ran in production at <code>kahmedt.com</code>, then I decommissioned it when the project wrapped up. The screenshots document the live system. The site files and the Lambda handler are in the repo; everything below is in the past tense because the infrastructure is gone, not because it never served anyone.",
    spec=[("Front door", "Route 53 &rarr; CloudFront &rarr; S3"), ("TLS", "ACM certificate, us-east-1"),
          ("API", "API Gateway REST, POST"), ("Compute", "Lambda, Node.js, SDK v3"),
          ("Data", "DynamoDB ContactMessages"), ("Notify", "SES to the owner")],
    summary="A visitor resolved <code>kahmedt.com</code> through Route 53 to CloudFront, which served the static site from S3 over HTTPS with a free ACM certificate. Clicking <em>Download eBook</em> sent an AJAX POST to <code>/epicreads_resource</code> on API Gateway, which invoked the <code>epicreads_contactus</code> Lambda. The function emailed the business owner through SES with the lead's name, email, a UUID and an ISO&nbsp;8601 timestamp, stored the same item in the <code>ContactMessages</code> table, and logged the run to CloudWatch. Expected load was 10&ndash;15 downloads a day, which is why there's no server anywhere in it.",
    how=[
        ("Why serverless for this?", "The workload was a handful of form submissions a day. An always-on server would cost money while idle and need patching. Lambda and on-demand DynamoDB are billed per request, so at this scale the backend cost is close to zero and there's nothing to patch."),
        ("Why CloudFront in front of S3 instead of S3 website hosting?", "Two reasons. Route 53 can alias straight to an S3 website endpoint only when the bucket name matches the domain, and mine didn't. And CloudFront is what gives the domain HTTPS: the ACM certificate attaches to the distribution, which also caches the site at edge locations."),
        ("Why does the certificate live in <code>us-east-1</code>?", "CloudFront only accepts ACM certificates issued in <code>us-east-1</code>, whatever region everything else is in. My first certificate was in the wrong region and CloudFront wouldn't take it."),
        ("Why an inline policy on the Lambda role?", "The function needs exactly two things: <code>ses:SendEmail</code> and <code>dynamodb:PutItem</code>. An inline policy scoped to those is deleted with the role, so nothing outlives the function."),
    ],
    diagram=dict(
        h=720,
        aria="A visitor resolves kahmedt.com through Route 53 to CloudFront, which uses an ACM certificate and serves the static site from S3. The form sends an AJAX POST to API Gateway, which invokes the Lambda function. Lambda sends an email through SES to the business owner, writes the lead to DynamoDB, and logs to CloudWatch.",
        boxes=[dict(x=176, y=60, w=1052, h=630, k="aws", label="AWS ACCOUNT — ROUTE 53 · CLOUDFRONT · ACM · S3 · API GATEWAY · LAMBDA · SES · DYNAMODB")],
        nodes=[
            dict(id="vis", x=16, y=110, w=136, k="neu", icon="browser", slot="browser", t="Visitor", s="kahmedt.com", tag="HTTPS"),
            dict(id="r53", x=200, y=110, w=160, k="aws", icon="globe", slot="route53", t="Route 53", s="hosted zone", tag="alias record"),
            dict(id="cf", x=404, y=110, w=180, k="aws", icon="cloud", slot="cloudfront", t="CloudFront", s="edge cache · HTTPS only", tag="distribution"),
            dict(id="s3", x=640, y=110, w=180, k="aws", icon="disk", slot="s3", t="S3 static site", s="HTML · CSS · JS", tag="origin"),
            dict(id="acm", x=404, y=280, w=180, k="aws", icon="lock", slot="acm", t="ACM certificate", s="issued in us-east-1", tag="for CloudFront"),
            dict(id="api", x=200, y=440, w=176, k="aws", icon="lb", slot="api-gateway", t="API Gateway", s="/epicreads_resource", tag="POST · CORS"),
            dict(id="fn", x=430, y=440, w=200, k="app", icon="bolt", slot="lambda", t="Lambda", s="epicreads_contactus", tag="Node.js · SDK v3"),
            dict(id="ses", x=700, y=360, w=170, k="aws", icon="mail", slot="ses", t="Amazon SES", s="verified identities", tag="SendEmail"),
            dict(id="own", x=960, y=360, w=176, k="neu", icon="user", slot="engineer", t="Business owner", s="instant email", tag="name · email · UUID"),
            dict(id="ddb", x=700, y=520, w=170, k="aws", icon="db", slot="dynamodb", t="DynamoDB", s="ContactMessages", tag="PutItem · on-demand"),
            dict(id="cw", x=960, y=520, w=176, k="obs", icon="trend", slot="cloudwatch", t="CloudWatch", s="Lambda + API logs", tag="every invocation"),
        ],
        edges=[
            dict(**{"from": "vis", "to": "r53"}, k="req", mech="DNS", what="Resolves the custom domain; the registrar's NS records point at the hosted zone."),
            dict(**{"from": "r53", "to": "cf"}, k="req", mech="alias record", what="Points the apex at the distribution."),
            dict(**{"from": "cf", "to": "s3"}, k="req", mech="origin fetch", what="Serves and caches the site; viewers get HTTPS only."),
            dict(**{"from": "acm", "to": "cf"}, k="aws", dash=True, mech="certificate", what="The TLS certificate, which had to be issued in <code>us-east-1</code>."),
            dict(**{"from": "vis", "to": "api"}, k="req", ss="b", ts="l", mech="AJAX POST", what="The form submits name and email from the browser; CORS enabled on the resource."),
            dict(**{"from": "api", "to": "fn"}, k="req", mech="Lambda integration", what="Invokes the function with the form body."),
            dict(**{"from": "fn", "to": "ses"}, k="app", mech="ses:SendEmail", what="Emails the owner the lead's details, a UUID and a timestamp."),
            dict(**{"from": "ses", "to": "own"}, k="app", mech="email", what="Arrives within moments of the click."),
            dict(**{"from": "fn", "to": "ddb"}, k="data", mech="dynamodb:PutItem", what="Stores <code>id</code> (UUID partition key), <code>name</code>, <code>email</code>, <code>timestamp</code>."),
            dict(**{"from": "fn", "to": "cw"}, k="obs", dash=True, ss="b", ts="b", my=650, mech="logs", what="Every invocation logged; API Gateway monitored too."),
        ],
    ),
    figcaption="The system as it ran in production. Arrows 1 to 4 are the static half &mdash; the part of the build where most of the debugging happened. Arrows 5 to 10 are one form submission: one POST, one function, one email and one row.",
    legend=[("c-neu", "People", "visitor, business owner"), ("c-aws", "AWS-managed", "DNS, CDN, TLS, storage, API, email, data"),
            ("c-app", "The function", "the only code that runs"), ("c-obs", "Observability", "CloudWatch"),
            ("line:c-app", "Request path", "browser to backend"), ("line:dg-line", "Data write", "the lead"),
            ("line:c-aws:dashed", "Configuration", "the certificate"), ("line:c-obs:dashed", "Logs", "per invocation")],
    reach=[("Public", "the CloudFront distribution at <code>kahmedt.com</code> and the API Gateway endpoint, both HTTPS."),
           ("Private", "the Lambda function, the DynamoDB table and SES, reachable only through the API and the function's role."),
           ("Now", "nothing. The distribution, API, function and table were all decommissioned.")],
    ledger_intro_obs="the live system",
    ledger=[
        ("measured", "One click produced an email and a stored lead",
         "I submitted the download form on the live site. The owner's inbox got an email with the full name, email address, a UUID and an ISO&nbsp;8601 timestamp, and the same item appeared in <code>ContactMessages</code>. The first version of the email had fewer fields; the metadata came with the DynamoDB phase.",
         "Submitted the form, then checked the inbox and the table."),
        ("observed", "The site served at the custom domain over HTTPS",
         "<code>kahmedt.com</code> loaded through CloudFront with a valid certificate, once the certificate was in the right region and the registrar pointed at Route 53.",
         "Loaded the domain in a browser and checked the certificate (screenshot below)."),
        ("observed", "Every invocation showed up in CloudWatch",
         "CloudWatch had the Lambda function's runs and the API Gateway metrics, which is where the CORS and permission failures below were diagnosed.",
         "Read the function's log group and metrics."),
        ("design", "The function can do two things and nothing else",
         "The execution role's inline policy allows <code>dynamodb:PutItem</code> and <code>ses:SendEmail</code>. I didn't try to make the function call anything else to watch it fail.",
         "Reviewed the inline policy. Not adversarially tested."),
        ("design", "Idle cost is close to zero",
         "Lambda is billed per invocation and the table is on-demand, so with 10&ndash;15 submissions a day there's no standing compute cost. That's the pricing model, not a bill I'm quoting.",
         "Reasoned from the services' pricing models; no cost report kept."),
    ],
    proof_note="Captured from the live system",
    shots=[
        dict(raw=SL + "Screenshot from 2025-11-12 10-16-21.png", alt="The eBook site at the custom domain kahmedt.com served over HTTPS", cap="The site at <code>kahmedt.com</code>, over HTTPS."),
        dict(raw=SL + "Screenshot from 2025-11-12 22-37-29.png", alt="The eBook download form with name and email fields and a Download Ebook button", cap="The form: name, email, <em>Download Ebook</em>."),
        dict(raw=SL + "Screenshot04.jpeg", alt="Email received by the business owner via SES with full name, email, UUID and timestamp", cap="The owner's email, with UUID and timestamp."),
        dict(raw=SL + "Screenshot from 2025-11-12 12-46-04.png", alt="CloudWatch monitoring for the Lambda function and API Gateway", cap="CloudWatch on the function and the API."),
    ],
    broke=[
        ("CloudFront rejected my certificate",
         "I requested the ACM certificate in my working region. CloudFront only uses certificates from <code>us-east-1</code>, so it simply wasn't offered. Re-issuing it in <code>us-east-1</code> fixed it."),
        ("The domain didn't resolve to anything I'd built",
         "The Route 53 hosted zone had records, but the registrar was still using its own nameservers. Copying all four NS records from the hosted zone to the registrar is what made Route 53 authoritative."),
        ("CORS errors on submit",
         "The form's AJAX call from the CloudFront domain was blocked by the browser because API Gateway wasn't returning CORS headers. I enabled CORS on the resource and had the Lambda return <code>Access-Control-Allow-Origin</code> as well."),
        ("Lambda couldn't write to DynamoDB",
         "The function ran, sent the email, and failed on the write: its role had no DynamoDB permission. An inline <code>dynamodb:PutItem</code> policy on the execution role fixed it, scoped to exactly that action."),
    ],
    broke_note="Four failures worth keeping",
    source="Unlike the other projects, this one's code lives in my portfolio repo rather than a standalone one: the site in <code>Ebook/</code> and the Lambda handler in <code>Extra/</code>, at <a href=\"https://github.com/kingswanzy2020/Projects/tree/main/aws/serverless-lead-capture\">Projects/aws/serverless-lead-capture</a>.",
    clone="git clone https://github.com/kingswanzy2020/Projects.git\ncd \"Projects/aws/serverless-lead-capture\"\naws s3 sync Ebook/ s3://YOUR_BUCKET_NAME",
    stack="Amazon S3 &middot; CloudFront &middot; Route 53 &middot; AWS Certificate Manager &middot; API Gateway (REST) &middot; AWS Lambda (Node.js, SDK v3) &middot; Amazon SES &middot; DynamoDB &middot; IAM inline policies &middot; CloudWatch &middot; CORS",
),
# ======================================================================
dict(
    slug="three-tier-serverless",
    card=dict(group="aws", eyebrow="AWS / Serverless", color="c-aws", status="Guided lab",
              title="A three-tier web architecture, serverless",
              desc="CloudFront and a private bucket, API Gateway and Lambda, DynamoDB &mdash; each tier built and tested on its own."),
    title_tag="Three-Tier Serverless Architecture",
    meta="Case study: a three-tier web architecture with no servers: a CloudFront-delivered frontend from a private S3 bucket, an API Gateway and Lambda logic tier, and a DynamoDB data tier.",
    eyebrow="AWS / Serverless",
    h1="A three-tier web architecture with no servers in any tier",
    standfirst="I built the classic three-tier pattern as three serverless modules &mdash; a frontend delivered by CloudFront from a private bucket, an API Gateway and Lambda logic tier, and a DynamoDB data tier &mdash; and locked each one down to what the tier next to it needs.",
    chip="Guided lab",
    status=lab_status("the static site, the Lambda handler and the exported API definition in the repo rebuild the three tiers."),
    spec=[("Presentation", "CloudFront + private S3, OAC"), ("Logic", "API Gateway REST + Lambda"),
          ("Data", "DynamoDB UserData, key userId"), ("Function", "RetrieveUserData, SDK v3"),
          ("Permissions", "inline dynamodb:GetItem"), ("Build time", "about 5.5 hours, 3 modules")],
    summary="The presentation tier is <code>index.html</code>, <code>style.css</code> and <code>script.js</code> in a private S3 bucket, served only through a CloudFront distribution with Origin Access Control. The logic tier is a REST API in API Gateway, deployed to a <code>prod</code> stage, in front of a Lambda function that reads <code>userId</code> from <code>queryStringParameters</code> and returns <code>200</code> with the user or <code>404</code> with an error. The data tier is a DynamoDB table keyed on <code>userId</code>. The three were built as separate modules and each was tested on its own.",
    how=[
        ("Why Origin Access Control instead of a public bucket?", "With OAC, CloudFront signs its requests to S3 and the bucket policy allows only that distribution. The bucket stays private, visitors can't skip the CDN, and nobody can pull objects straight from S3. Setting OAC on the distribution isn't enough on its own &mdash; the bucket policy has to say the same thing, which is the first error I hit."),
        ("Why API Gateway in front of Lambda?", "Lambda runs code; it doesn't do API management. API Gateway receives the request, routes the resource and method to the function, and carries the response back. Deploying to a stage gives a stable invoke URL and a snapshot the documentation can be published against."),
        ("Why a hand-written inline policy instead of a managed one?", "The function only ever calls <code>dynamodb:GetItem</code> on one table. <code>AmazonDynamoDBFullAccess</code> would work and break least privilege; <code>AmazonDynamoDBReadOnlyAccess</code> was closer. The inline policy allowing just <code>GetItem</code> on <code>table/UserData</code> is exact."),
    ],
    diagram=dict(
        h=560,
        aria="A browser loads the site from CloudFront, which reads index.html, style.css and script.js from a private S3 bucket through Origin Access Control. API requests go to API Gateway's prod stage, which invokes the RetrieveUserData Lambda function. The function, under an execution role with an inline GetItem policy, reads the UserData table in DynamoDB by userId.",
        boxes=[dict(x=176, y=60, w=1052, h=150, k="aws", dash="3 4", label="PRESENTATION TIER"),
               dict(x=176, y=250, w=1052, h=130, k="aws", dash="3 4", label="LOGIC TIER"),
               dict(x=176, y=420, w=1052, h=120, k="aws", dash="3 4", label="DATA TIER")],
        nodes=[
            dict(id="usr", x=16, y=96, w=136, k="neu", icon="browser", slot="browser", t="Browser", s="User Information", tag="HTTPS"),
            dict(id="cf", x=220, y=96, w=190, k="aws", icon="cloud", slot="cloudfront", t="CloudFront", s="default root index.html", tag="Origin Access Control"),
            dict(id="s3", x=500, y=96, w=246, k="aws", icon="disk", slot="s3", t="S3 bucket (private)", s="index.html · style.css · script.js", tag="policy: CloudFront only"),
            dict(id="api", x=220, y=276, w=190, k="aws", icon="lb", slot="api-gateway", t="API Gateway", s="REST · prod stage", tag="GET + docs"),
            dict(id="fn", x=500, y=276, w=210, k="app", icon="bolt", slot="lambda", t="Lambda", s="RetrieveUserData", tag="200 or 404"),
            dict(id="role", x=800, y=276, w=230, k="aws", icon="key", slot="iam", t="Execution role", s="inline: dynamodb:GetItem", tag="table/UserData only"),
            dict(id="ddb", x=500, y=446, w=210, k="aws", icon="db", slot="dynamodb", t="DynamoDB", s="UserData", tag="partition key userId"),
        ],
        edges=[
            dict(**{"from": "usr", "to": "cf"}, k="req", mech="HTTPS", what="Page loads come from the nearest edge location."),
            dict(**{"from": "cf", "to": "s3"}, k="req", mech="OAC-signed GET", what="The only principal the bucket policy lets read objects."),
            dict(**{"from": "usr", "to": "api"}, k="req", dash=True, ss="b", ts="l", mech="GET ?userId=", what="The API call the page is built for; I tested this tier on its own with the invoke URL."),
            dict(**{"from": "api", "to": "fn"}, k="req", mech="Lambda integration", what="Passes the event; the function reads <code>queryStringParameters.userId</code>."),
            dict(**{"from": "fn", "to": "ddb"}, k="data", mech="GetItem", what="Looks the user up by partition key; <code>200</code> with the item or <code>404</code> with a message."),
            dict(**{"from": "role", "to": "fn"}, k="aws", dash=True, mech="assumed by", what="Grants exactly <code>GetItem</code> on the one table, plus CloudWatch logs."),
        ],
    ),
    figcaption="The three tiers as built. Arrow 3 is dashed because I tested each tier separately &mdash; the page, the API through its invoke URL, and the function with test events &mdash; rather than recording a click on the page all the way to the table.",
    legend=[("c-neu", "Client", "the browser"), ("c-aws", "AWS-managed", "CDN, storage, API, data, IAM"),
            ("c-app", "The function", "the only code in the logic tier"),
            ("line:c-app", "Request path", "tier to tier"), ("line:dg-line", "Data read", "GetItem"),
            ("line:c-aws:dashed", "Permission", "the execution role")],
    reach=[("Public", "the CloudFront distribution and the API's <code>prod</code> invoke URL."),
           ("Private", "the S3 bucket (CloudFront only), the function, and the table."),
           ("Permissions", "one inline policy: <code>dynamodb:GetItem</code> on <code>UserData</code>.")],
    ledger_intro_obs="the console and test results",
    ledger=[
        ("measured", "The function \"succeeded\" while DynamoDB refused it &mdash; until the role allowed it",
         "My first test event with a <code>userId</code> reported <em>Executing function: succeeded</em>, but the response body was an AccessDenied error: the code ran fine and DynamoDB blocked it. After giving the role read access, the same test returned the item &mdash; <code>email</code>, <code>name</code> and <code>userId</code>.",
         "Ran the same JSON test event in the Lambda console before and after the permission change."),
        ("measured", "Narrowing to an inline <code>GetItem</code> policy kept it working",
         "I replaced the managed policy with an inline one allowing only <code>dynamodb:GetItem</code> on <code>table/UserData</code> and re-ran the test event. Still succeeded, with the item returned.",
         "Re-ran the test event after swapping the policy."),
        ("measured", "CloudFront returned AccessDenied until the bucket policy matched OAC",
         "With OAC set on the distribution, the site still returned <code>AccessDenied</code>. Adding the policy the OAC setup generates &mdash; <code>s3:GetObject</code> for <code>cloudfront.amazonaws.com</code>, conditioned on my distribution's ARN &mdash; made the site load.",
         "Loaded the distribution's domain before and after the bucket policy change."),
        ("observed", "CloudFront loaded faster than the S3 website endpoint",
         "As an extension I also served the site straight from S3 website hosting and compared load times in the browser; CloudFront was faster, which matches it serving from an edge location near me. I didn't record numbers, so this is an observation, not a benchmark.",
         "Compared page loads for both URLs in the browser's network panel."),
        ("design", "Visitors can't bypass CloudFront to reach the files",
         "The bucket policy's only grant is to CloudFront for this distribution. I didn't try fetching an object URL directly to confirm the denial once the S3-hosting experiment was cleaned up.",
         "Reviewed the bucket policy. Not adversarially tested."),
    ],
    proof_note="Captured during the build",
    shots=[
        dict(pdf="legendary-aws-networks-cloudfront/i-011.png", name="cloudfront-denied.jpg", alt="CloudFront domain returning an XML AccessDenied error", cap="CloudFront's first answer: <code>AccessDenied</code>."),
        dict(pdf="legendary-aws-networks-cloudfront/i-013.png", name="oac-policy.jpg", alt="S3 bucket policy allowing s3:GetObject for the CloudFront service principal, conditioned on the distribution ARN", cap="The bucket policy that matches OAC."),
        dict(pdf="legendary-aws-compute-lambda/i-015.png", name="lambda-test.jpg", alt="Lambda test result: Executing function succeeded, returning email, name and userId", cap="The function returning the user once permitted."),
        dict(pdf="legendary-aws-compute-lambda/i-018.png", name="inline-policy.jpg", alt="Inline IAM policy allowing only dynamodb:GetItem on the UserData table", cap="The inline policy: one action, one table."),
    ],
    broke=[
        ("OAC on the distribution, AccessDenied from the bucket",
         "I'd set the distribution's origin access to OAC and expected that to be the whole job. It isn't: the bucket is private by default, and its policy has to grant CloudFront access too. The OAC setup generates that policy; I hadn't applied it."),
        ("A successful run with a failure inside it",
         "Lambda's green \"succeeded\" only means the code didn't throw. The response was DynamoDB's AccessDenied, because the execution role had nothing but CloudWatch logging. Reading the error log is what told me which permission &mdash; <code>dynamodb:GetItem</code> &mdash; it actually needed."),
        ("Turning off Block Public Access didn't make the bucket public",
         "For the S3-hosting comparison I disabled Block Public Access and still got errors. That switch only stops blocking; it doesn't grant anything. A bucket policy statement allowing <code>s3:GetObject</code> to everyone is what opened it."),
    ],
    source="The static frontend, the DynamoDB Lambda handler and the exported API Gateway definition live here: <a href=\"https://github.com/kingswanzy2020/three-tier-web-architecture\">kingswanzy2020/three-tier-web-architecture</a>. The production sequel to this pattern is the <a href=\"../serverless-lead-capture/\">serverless lead-capture site</a>.",
    clone="git clone https://github.com/kingswanzy2020/three-tier-web-architecture.git",
    stack="CloudFront &middot; Origin Access Control &middot; Amazon S3 &middot; API Gateway (REST, stages, documentation) &middot; AWS Lambda &middot; DynamoDB &middot; IAM execution roles &middot; inline policies &middot; least privilege",
),
]
