NW = "https://learn.nextwork.org/thoughtful_white_zany_vampire/uploads/"
R1 = "ai-devops/rag-api-fastapi/Screenshots/"
R2 = "ai-devops/rag-api-docker/Screenshots/"
R3 = "ai-devops/rag-api-kubernetes/Screenshots/"
NG = "networking/nginx-traffic-gateway/Screenshots/"

PAGES = [
# ======================================================================
dict(
    slug="ai-incident-response",
    card=dict(group="ai", eyebrow="AI &times; SRE", color="c-obs", status="Local cluster",
              title="AI log analysis and incident response",
              desc="Fluent Bit ships errors to a local LLM; each new error signature becomes one GitHub issue with a root cause and a kubectl fix."),
    title_tag="AI Log Analysis & Incident Response",
    meta="Case study: Kubernetes error logs collected by Fluent Bit, diagnosed by a local LLM through Ollama, deduplicated and cached in Redis, and turned into GitHub issues with a proposed kubectl fix.",
    eyebrow="AI &times; SRE",
    h1="AI log analysis that opens one incident per error, not one per log line",
    standfirst="I built a pipeline where Fluent Bit ships only ERROR and CRITICAL logs out of a Kubernetes cluster, a local LLM diagnoses them, and each new error signature becomes a single GitHub issue with a root cause and a proposed <code>kubectl</code> fix &mdash; cached, deduplicated and rate-limited so an error storm can't flood the model or the tracker.",
    chip="Local cluster",
    status="This ran on my own machine: a local Kubernetes cluster for the crashing app and Fluent Bit, with the FastAPI service and Ollama on the host. No cloud API was involved and nothing was public. The repo rebuilds it; everything below describes those runs.",
    spec=[("Collection", "Fluent Bit DaemonSet, Helm"), ("Filter", "ERROR / CRITICAL at the edge"),
          ("Middleware", "FastAPI on the host"), ("Model", "Ollama, qwen3:1.7b, local"),
          ("Cache &amp; dedupe", "Redis, keyed by error signature"), ("Output", "GitHub Issues (+ optional Slack)")],
    summary="A deliberately crash-prone app in the cluster writes structured log lines with a <code>level</code>, a message and a timestamp. Fluent Bit runs as a DaemonSet, keeps only lines whose level matches ERROR or CRITICAL, and POSTs them to a FastAPI service on the host. The service checks Redis for a diagnosis of the same error signature; on a miss, and only within the rate limit, it asks <code>qwen3:1.7b</code> through Ollama for a structured answer &mdash; <code>error_category</code>, <code>root_cause</code>, <code>severity</code>, <code>kubectl_fix</code> &mdash; caches it, and opens a GitHub issue for signatures it hasn't seen. A Slack alert fires too if a webhook is configured.",
    how=[
        ("Why filter in Fluent Bit and not in the service?", "Most log lines aren't errors. Dropping them at the DaemonSet means they never cross the network and the model never sees noise. The service filters again, case-insensitively, as a second line."),
        ("Why cache by error signature?", "During an incident the same error repeats hundreds of times. Without a cache, every repeat is another inference call that ties up the model when it's needed most. With the signature as the Redis key, a repeat is answered from cache in milliseconds."),
        ("Why deduplicate separately from caching?", "A cached diagnosis stops repeat model calls; deduplication stops repeat tickets. An error signature that already has an issue is logged and skipped, so one recurring failure is one issue, not a page of them."),
        ("Why a rate limit on the model?", "Each inference takes seconds. A burst of <em>unique</em> errors would queue unbounded calls and exhaust the machine. A token bucket caps how fast the model is asked, whatever arrives."),
    ],
    diagram=dict(
        h=560,
        aria="A crash-prone app in a Kubernetes cluster writes logs; a Fluent Bit DaemonSet filters ERROR and CRITICAL lines and sends them to a FastAPI service on the host. The service checks Redis for a cached diagnosis by error signature, calls the local Ollama model on a miss within a rate limit, opens a GitHub issue for new signatures, and optionally posts to Slack.",
        boxes=[dict(x=16, y=60, w=380, h=470, k="ctl", label="LOCAL KUBERNETES CLUSTER"),
               dict(x=430, y=60, w=560, h=470, k="neu", label="MY MACHINE — HOST")],
        nodes=[
            dict(id="app", x=40, y=110, w=200, k="app", icon="pod", slot="workload", t="Crashy app", s="level · message · time", tag="real errors"),
            dict(id="fb", x=40, y=300, w=200, k="obs", icon="filter", slot="fluent-bit", t="Fluent Bit", s="DaemonSet · grep filter", tag="ERROR / CRITICAL"),
            dict(id="api", x=470, y=300, w=200, k="ctl", icon="code", slot="fastapi", t="FastAPI service", s="filter · cache · ticket", tag="token bucket"),
            dict(id="redis", x=470, y=110, w=200, k="obs", icon="cache", slot="redis", t="Redis", s="signature → diagnosis", tag="cache + dedupe"),
            dict(id="llm", x=750, y=110, w=210, k="neu", icon="ai", slot="ollama", t="Ollama", s="qwen3:1.7b, local", tag="structured JSON"),
            dict(id="gh", x=1030, y=300, w=180, k="ctl", icon="git", slot="github", t="GitHub Issue", s="root cause + kubectl fix", tag="new signatures only"),
            dict(id="slack", x=750, y=430, w=210, k="neu", icon="chat", slot="slack", t="Slack", s="if webhook is set", tag="optional"),
        ],
        edges=[
            dict(**{"from": "app", "to": "fb"}, k="obs", mech="container logs", what="Structured lines; the <code>level</code> field is what the grep filter matches."),
            dict(**{"from": "fb", "to": "api"}, k="obs", mech="HTTP POST", what="To <code>host.docker.internal:8000</code>, the address that actually reached the host."),
            dict(**{"from": "api", "to": "redis"}, k="data", mech="get / set", what="Cache check by signature; a hit skips the model."),
            dict(**{"from": "api", "to": "llm"}, k="ctl", ss="r", ts="b", so=-20, mech="rate-limited call", what="On a miss: category, root cause, severity and a proposed <code>kubectl</code> fix."),
            dict(**{"from": "api", "to": "gh"}, k="ctl", so=20, to_off=20, mech="REST API", what="Opens an issue for a signature with none; a repeat is logged and skipped."),
            dict(**{"from": "api", "to": "slack"}, k="neu", dash=True, ss="b", ts="l", mech="webhook", what="Only when the webhook variable is present; otherwise skipped quietly."),
        ],
    ),
    figcaption="The pipeline as it ran. Arrow 3 is the reason arrow 4 isn't called hundreds of times during an incident, and the dedupe on arrow 5 is the reason the issue tracker doesn't fill up either.",
    legend=[("c-app", "Error source", "the crash-prone app"), ("c-obs", "Collection &amp; memory", "Fluent Bit, Redis"),
            ("c-ctl", "Logic &amp; output", "FastAPI, GitHub"), ("c-neu", "Model &amp; optional alerting", "Ollama, Slack"),
            ("line:c-obs", "Log path", "cluster to host"), ("line:c-ctl", "Diagnosis &amp; ticket", "model and GitHub"),
            ("line:dg-line", "Cache", "signature lookups"), ("line:c-neu:dashed", "Optional", "Slack")],
    reach=[("Public", "nothing; the only outbound call was GitHub's API to open issues."),
           ("Host", "FastAPI and Ollama; the model ran locally, so no log left the machine for inference."),
           ("Token", "a GitHub token with read/write on the one issues repository.")],
    ledger_intro_obs="the running pipeline",
    ledger=[
        ("measured", "One real error became one issue, and the repeats didn't",
         "With the crashing app emitting errors, the service received them from Fluent Bit, created a GitHub issue with the signature, root cause and proposed fix, and cached the diagnosis in Redis. Further errors with the same signature were recognised and skipped issue creation.",
         "Ran the end-to-end integration test and watched the service log, Redis and the issues repository."),
        ("observed", "A pod could reach the service on the host",
         "A throwaway curl pod in the cluster got a JSON response from <code>host.docker.internal:8000/health</code>, which is why that's the address Fluent Bit uses.",
         "<code>kubectl run</code> a curl pod against the health endpoint."),
        ("design", "A burst of unique errors can't exhaust the machine",
         "A token bucket caps how often the model is called. I didn't generate a deliberate storm of unique errors to watch requests queue.",
         "Reviewed the rate limiter. Not load-tested."),
        ("design", "The model's answer is a suggestion, not a remediation",
         "The <code>kubectl_fix</code> lands in an issue for a person to read. Nothing in the pipeline runs it.",
         "By construction: the service only writes issues and Slack messages."),
    ],
    proof_note="From the end-to-end run",
    shots=[
        dict(url=NW + "4e7446a3-e3d2-4d8e-b420-e5e19a81011c_svbvwixt", alt="End to end: a Kubernetes error flowing through the service to a diagnosis and a GitHub issue", cap="End to end: error &rarr; diagnosis &rarr; issue."),
        dict(url=NW + "4e7446a3-e3d2-4d8e-b420-e5e19a81011c_mygwznjn", alt="An automatically created GitHub issue with root cause, severity and a proposed kubectl fix", cap="The issue the pipeline opened, with its proposed fix."),
    ],
    broke=[
        ("Fluent Bit could see the logs but not the service",
         "The service listened on my host; Fluent Bit ran in a pod. Finding an address a pod could actually reach took trial and error. <code>host.docker.internal:8000</code> worked, because the server was bound to all interfaces rather than localhost &mdash; and I proved it with a curl pod before trusting Fluent Bit to use it."),
        ("The first diagnosis was slow for a reason unrelated to the error",
         "Ollama loads the model into memory on first use, which takes 10&ndash;30 seconds. Without a warm-up at startup, the first real error of a session waited on that load. The service now warms the model before it needs it."),
    ],
    source="The FastAPI service, its token-bucket rate limiter and Redis dedupe, the crash-looping test workload and the Fluent Bit values live here: <a href=\"https://github.com/kingswanzy2020/autonomous-sre\">kingswanzy2020/autonomous-sre</a>.",
    clone="git clone https://github.com/kingswanzy2020/autonomous-sre.git",
    stack="Kubernetes &middot; Fluent Bit (DaemonSet, Helm) &middot; FastAPI &middot; Ollama (qwen3:1.7b) &middot; Redis caching &middot; signature dedupe &middot; token-bucket rate limiting &middot; GitHub REST API &middot; Slack webhooks &middot; incident response",
),
# ======================================================================
dict(
    slug="ai-security-scanner",
    card=dict(group="ai", eyebrow="AI &times; Security", color="c-obs", status="Local script",
              title="An AI security scanner for Python",
              desc="Source in, severity-rated findings out &mdash; each with why it's vulnerable, the impact, and a secure rewrite."),
    title_tag="AI Security Scanner for Python",
    meta="Case study: a command-line scanner that sends Python source to the Gemini API with a structured security prompt and prints colour-coded, severity-rated findings with secure fixes.",
    eyebrow="AI &times; Security",
    h1="An AI security scanner for Python, with severity you can see",
    standfirst="I built a command-line scanner that sends Python source to Gemini with a structured security prompt and prints each finding &mdash; vulnerability type, why, impact and a secure fix &mdash; colour-coded by severity, so the critical one is the first thing you read.",
    chip="Local script, not a service",
    status="This is a script you run against a file, not a hosted tool. <code>python scanner.py</code> with a Gemini key in <code>.env</code> reproduces everything below.",
    spec=[("Runtime", "Python CLI, scanner.py"), ("Model", "Gemini API"),
          ("Key", ".env, never in code"), ("Output", "4 fields per finding"),
          ("Severity", "colorama, CRITICAL in red"), ("Classes tested", "SQLi · secrets · weak hashing")],
    summary="<code>scanner.py</code> reads a Python file, sends it to Gemini with a prompt that requires four fields for every finding &mdash; the vulnerability type, why it's vulnerable, its impact, and a secure code fix &mdash; and a severity rating. An <code>add_colors_to_output</code> function then colours the response by severity with <code>colorama</code>. I ran it against deliberately vulnerable samples covering three classes that professional SAST tools look for: SQL injection, hardcoded credentials, and weak MD5 hashing.",
    how=[
        ("Why a structured prompt?", "\"Find security issues\" gets a vague essay. Requiring the same four fields per finding makes every answer actionable &mdash; you know what's wrong, why it matters, and what to write instead &mdash; and makes the output predictable enough to colour by severity."),
        ("Why colour by severity?", "When a file has several findings, the order you read them in matters. CRITICAL in red is the first thing your eye lands on."),
        ("Why <code>.env</code> for the key?", "A security scanner with a hardcoded API key would flag itself. The key is loaded from <code>.env</code>, which stays out of the repository."),
    ],
    diagram=dict(
        h=440,
        aria="A developer runs scanner.py against a Python file. The script loads the Gemini API key from .env, sends the source with a structured security prompt to the Gemini API, and prints the findings colour-coded by severity in the terminal.",
        boxes=[dict(x=16, y=60, w=900, h=350, k="neu", label="MY MACHINE — VIRTUALENV")],
        nodes=[
            dict(id="dev", x=40, y=110, w=150, k="neu", icon="user", slot="engineer", t="Developer", s="before a push", tag="python scanner.py"),
            dict(id="src", x=330, y=270, w=190, k="neu", icon="doc", slot="python", t="Target code", s="vulnerable samples", tag="SQLi · secrets · MD5"),
            dict(id="env", x=40, y=270, w=150, k="aws", icon="key", slot="secrets", t=".env", s="GEMINI API key", tag="not committed"),
            dict(id="sc", x=240, y=110, w=190, k="app", icon="code", slot="python", t="scanner.py", s="structured prompt", tag="4 fields + severity"),
            dict(id="out", x=480, y=110, w=200, k="obs", icon="terminal", slot="terminal", t="Terminal output", s="add_colors_to_output", tag="CRITICAL in red"),
            dict(id="gem", x=980, y=110, w=200, k="neu", icon="ai", slot="ai", t="Gemini API", s="analysis", tag="per file"),
        ],
        edges=[
            dict(**{"from": "dev", "to": "sc"}, k="ctl", mech="run", what="Point the scanner at a Python file."),
            dict(**{"from": "src", "to": "sc"}, k="data", ss="t", ts="b", so=-50, to_off=40, mech="read", what="The whole file goes into the prompt."),
            dict(**{"from": "env", "to": "sc"}, k="aws", dash=True, ss="r", ts="b", to_off=-40, mech="load key", what="Read from <code>.env</code> at startup."),
            dict(**{"from": "sc", "to": "gem"}, k="app", pts=[(430, 144), (460, 144), (460, 80), (1080, 80), (1080, 106)], mech="HTTPS API", what="Source plus the structured security prompt."),
            dict(**{"from": "gem", "to": "out"}, k="obs", ss="l", ts="r", mech="findings", what="Type, why, impact, secure fix and severity per finding; coloured before printing."),
        ],
    ),
    figcaption="The scanner as it ran. Arrow 4 is the only call that leaves the machine, and it carries the code under review &mdash; worth knowing before pointing it at anything private.",
    legend=[("c-neu", "Local &amp; external", "developer, files, Gemini"), ("c-app", "The script", "scanner.py"),
            ("c-aws", "Secret", "the API key"), ("c-obs", "Output", "coloured findings"),
            ("line:c-app", "Model call", "source + prompt"), ("line:c-obs", "Findings", "back to the terminal"),
            ("line:dg-line", "Input", "the file under review")],
    reach_title="What it touches",
    reach=[("Reads", "the target file and <code>.env</code>."),
           ("Sends", "the file's source to the Gemini API &mdash; the code leaves the machine."),
           ("Writes", "nothing; the findings go to the terminal.")],
    ledger_intro_obs="the scanner's output",
    ledger=[
        ("measured", "All three seeded vulnerability classes were found, with fixes",
         "Against the vulnerable samples, the scanner reported the SQL injection (the username concatenated into the query, fixed with a parameterised query), the hardcoded password, and the weak MD5 hashing, each with an impact and a secure rewrite.",
         "Ran <code>python scanner.py</code> against each sample and read the findings."),
        ("observed", "Severity came out colour-coded",
         "With <code>colorama</code> in place, the SQL injection printed as <code>SEVERITY: CRITICAL</code> in red, ahead of its description and fix.",
         "Read the terminal output after adding the colouring function."),
        ("observed", "The connection worked before any scanning",
         "A test call returned \"Hello, security scanner!\", which confirmed the key from <code>.env</code> was being sent and accepted.",
         "Ran the connectivity check in <code>scanner.py</code>."),
        ("design", "Findings are a model's opinion, not a proof",
         "An LLM can miss a vulnerability or invent one. I tested three known classes on purpose-built samples; I didn't measure false positives or false negatives on real code.",
         "No precision or recall measurement was done."),
    ],
    proof_note="From the scanner's output",
    shots=[
        dict(pdf="legendary-ai-security-audit/i-004.png", name="hello.jpg", alt="python scanner.py printing Hello, security scanner! after a FutureWarning that google.generativeai support has ended", cap="First contact &mdash; and a deprecation warning."),
        dict(pdf="legendary-ai-security-audit/i-001.png", name="hardcoded.jpg", alt="Scanner output flagging the hardcoded password admin123 as a critical security issue", cap="The hardcoded password, explained."),
        dict(pdf="legendary-ai-security-audit/i-008.png", name="sqli.jpg", alt="Scanner output for SQL injection: vulnerability type, why it is vulnerable, impact and a parameterised-query fix", cap="SQL injection, with the parameterised fix."),
        dict(pdf="legendary-ai-security-audit/i-010.png", name="critical.jpg", alt="Colour-coded scanner output with SEVERITY: CRITICAL in red for the SQL injection", cap="Severity, colour-coded."),
    ],
    broke=[
        ("The SDK was deprecated under me",
         "Every run printed a <code>FutureWarning</code>: support for <code>google.generativeai</code> has ended and it won't get updates or fixes; switch to <code>google.genai</code>. The scanner worked, but on a package with no future. The later <a href=\"../ai-pr-review/\">PR reviewer</a> uses <code>google-genai</code>; this script hasn't been moved yet."),
    ],
    source="The scanner and the vulnerable samples it runs against live here: <a href=\"https://github.com/kingswanzy2020/security-scanner\">kingswanzy2020/security-scanner</a>.",
    clone="git clone https://github.com/kingswanzy2020/security-scanner.git\necho \"GEMINI_API_KEY=...\" &gt; .env\npython scanner.py",
    stack="Python &middot; Gemini API &middot; prompt design for structured output &middot; SQL injection &middot; secrets hygiene (.env) &middot; weak cryptography &middot; colorama &middot; CLI UX",
),
# ======================================================================
dict(
    slug="rag-api",
    card=dict(group="ai", eyebrow="AI &times; DevOps", color="c-app", status="Local cluster",
              title="A RAG API from laptop to Kubernetes",
              desc="FastAPI, Chroma and a local model; then a Docker image on Docker Hub; then a Minikube Deployment I killed to watch it come back."),
    title_tag="RAG API to Kubernetes",
    meta="Case study: a retrieval-augmented generation API built with FastAPI, Chroma and Ollama, containerised and published to Docker Hub, then deployed to Minikube with a Deployment and a NodePort Service.",
    eyebrow="AI &times; DevOps",
    h1="A RAG API, from a laptop to a container to Kubernetes",
    standfirst="I built a retrieval-augmented API with FastAPI, Chroma and a local model, packaged it as a Docker image on Docker Hub, then ran it on Minikube behind a NodePort Service &mdash; and deleted the pod to watch Kubernetes replace it while the Service kept routing.",
    chip="Local cluster",
    status="All three stages ran on my machine &mdash; a virtualenv, Docker, then a single-node Minikube cluster &mdash; with Ollama on the host. The image is public on Docker Hub as <code>ahmed3015/rag-api</code>, and the repo has the app, Dockerfile and manifests. Everything below describes those runs.",
    spec=[("API", "FastAPI + Uvicorn, /query and /add"), ("Retrieval", "Chroma, embeddings via embed.py"),
          ("Model", "Ollama, tinyllama, on the host"), ("Image", "python:3.11-slim &rarr; Docker Hub"),
          ("Cluster", "Minikube, 1 node"), ("Exposure", "NodePort Service, label selector")],
    summary="Stage one was the API: <code>embed.py</code> turns the knowledge base into vectors in Chroma; <code>/query</code> searches them for context, combines it with the question, and asks tinyllama for an answer; <code>/add</code> embeds new content at runtime. Stage two froze the runtime into an image: a Dockerfile on <code>python:3.11-slim</code> that installs the packages, runs the embedding at build time and starts Uvicorn on <code>0.0.0.0:8000</code>, pushed to Docker Hub and pulled back. Stage three ran that image on Minikube: a Deployment for one replica, a NodePort Service selecting <code>app: rag-api</code>, and Ollama on the host reached through <code>OLLAMA_HOST</code>.",
    how=[
        ("Why retrieval at all?", "A bare model answers confidently about anything. Asked \"What is Kubernetes?\", plain tinyllama told me it's a crispy wafer snack with cream and cheese, introduced in Israel in the 1970s. With retrieval, the same model answers from the knowledge base: a container orchestration platform. That before-and-after is the whole argument for RAG."),
        ("Why bind Uvicorn to <code>0.0.0.0</code> in the container?", "Inside a container, <code>127.0.0.1</code> is the container's own loopback. Binding to all interfaces is what lets a published port, or a Kubernetes Service, reach the API at all."),
        ("Why <code>eval $(minikube docker-env)</code>?", "Minikube runs its own Docker daemon, separate from the one on my host. Pointing my Docker CLI at Minikube's daemon puts the image where the cluster can see it; with <code>imagePullPolicy: Never</code>, the Deployment uses that local image instead of trying a registry."),
        ("Why a Service instead of the pod's IP?", "Pods are replaceable and come back with new IPs. The Service matches pods by label, so when the pod was deleted and replaced, traffic went to the new one without anything being reconfigured."),
    ],
    diagram=dict(
        h=600,
        aria="A Dockerfile builds the rag-api image, which is pushed to Docker Hub and loaded into Minikube's Docker daemon. On Minikube, a Deployment keeps one rag-api pod running; a NodePort Service routes curl requests to it by label. The pod holds the FastAPI app and the Chroma vector store and calls Ollama on the host for generation.",
        boxes=[dict(x=16, y=60, w=380, h=510, k="neu", label="MY MACHINE — BUILD"),
               dict(x=430, y=60, w=500, h=510, k="app", label="MINIKUBE — SINGLE NODE"),
               dict(x=964, y=60, w=264, h=510, k="neu", label="HOST")],
        nodes=[
            dict(id="df", x=40, y=110, w=200, k="ctl", icon="code", slot="docker", t="Dockerfile", s="python:3.11-slim", tag="embed at build"),
            dict(id="img", x=40, y=290, w=200, k="ctl", icon="box", slot="docker", t="rag-api image", s="FastAPI + Chroma db/", tag="1.36 GB"),
            dict(id="hub", x=40, y=460, w=200, k="neu", icon="box", slot="docker-hub", t="Docker Hub", s="ahmed3015/rag-api", tag="push → pull"),
            dict(id="svc", x=470, y=110, w=200, k="app", icon="lb", slot="kubernetes", t="NodePort Service", s="8000 → 32764", tag="selector app: rag-api"),
            dict(id="dep", x=470, y=460, w=200, k="ctl", icon="cycle", slot="kubernetes", t="Deployment", s="replicas: 1", tag="imagePullPolicy: Never"),
            dict(id="pod", x=710, y=290, w=200, k="app", icon="pod", slot="workload", t="rag-api pod", s="/query · /add", tag="Chroma inside"),
            dict(id="cli", x=990, y=110, w=200, k="neu", icon="terminal", slot="terminal", t="curl", s="minikube service --url", tag="client"),
            dict(id="oll", x=990, y=290, w=200, k="neu", icon="ai", slot="ollama", t="Ollama", s="tinyllama", tag="all interfaces"),
        ],
        edges=[
            dict(**{"from": "df", "to": "img"}, k="ctl", mech="docker build", what="Installs the packages, embeds the knowledge base, starts Uvicorn on <code>0.0.0.0:8000</code>."),
            dict(**{"from": "img", "to": "hub"}, k="ctl", mech="push / pull", what="Published, then pulled back down to prove anyone can run it with one command."),
            dict(**{"from": "img", "to": "pod"}, k="ctl", ss="r", ts="l", mech="minikube docker-env", what="Built into Minikube's own daemon so the cluster can see the image."),
            dict(**{"from": "cli", "to": "svc"}, k="req", ss="l", ts="r", mech="POST /query", what="Through the URL <code>minikube service --url</code> prints, since the NodePort lives on the Minikube node."),
            dict(**{"from": "svc", "to": "pod"}, k="req", ss="b", ts="t", mech="label selector", what="Routes to whichever pod carries <code>app: rag-api</code> &mdash; including a replacement."),
            dict(**{"from": "dep", "to": "pod"}, k="ctl", ss="r", ts="b", mech="reconcile", what="Holds one replica; a deleted pod is recreated."),
            dict(**{"from": "pod", "to": "oll"}, k="data", mech="OLLAMA_HOST", what="Generation runs on the host; the pod reaches it over the node's network."),
        ],
    ),
    figcaption="The last stage, with the earlier two on the left. Arrow 5 is why deleting the pod didn't matter to the client: the Service follows the label, not the pod. Arrow 7 is the one that failed first &mdash; a pod can't reach a host process that only listens on localhost.",
    legend=[("c-neu", "Outside the cluster", "Docker Hub, the client, Ollama"), ("c-ctl", "Build &amp; control", "Dockerfile, image, Deployment"),
            ("c-app", "Serving path", "Service and pod"),
            ("line:c-ctl", "Build &amp; reconcile", "image to pod"), ("line:c-app", "Request", "client to pod"),
            ("line:dg-line", "Generation", "pod to model")],
    reach=[("Public", "the image on Docker Hub; nothing served publicly."),
           ("Local", "the NodePort, reached through <code>minikube service --url</code>."),
           ("Host", "Ollama, listening on all interfaces so the Minikube node could reach it.")],
    ledger_intro_obs="the cluster and the API's answers",
    ledger=[
        ("measured", "Retrieval turned a hallucination into a correct answer",
         "<code>ollama run tinyllama</code> answered \"What is Kubernetes?\" with a story about a snack food. The same question through <code>/query</code>, grounded in the knowledge base, came back as a container orchestration platform for deploying and scaling containerised applications.",
         "Asked the bare model and the API the same question."),
        ("measured", "Deleting the pod didn't take the API down for long",
         "I deleted the pod and watched <code>kubectl get pods --watch</code>: the old pod went <code>Terminating</code> to <code>Completed</code> while a new one went <code>Pending</code>, <code>ContainerCreating</code> and <code>Running</code> within about a second. A <code>/query</code> through the Service afterwards answered normally.",
         "<code>kubectl delete pod</code> with a watch running, then a curl through the Service URL."),
        ("measured", "<code>/add</code> extended the knowledge base at runtime",
         "Posting a sentence about Docker to <code>/add</code> returned <code>{\"status\": \"success\", \"message\": \"Content added to knowledge base\"}</code> with an ID &mdash; no file edits, no re-running <code>embed.py</code>.",
         "Called <code>/add</code> from Swagger UI and read the response."),
        ("observed", "The image round-tripped through Docker Hub",
         "After pushing, <code>docker pull ahmed3015/rag-api</code> downloaded every layer and the pulled image served the same answers.",
         "Pushed, pulled, ran, and queried."),
        ("design", "The container behaves the same on any Docker host",
         "Python, the packages and the embedded knowledge base are all in the image. I only ran it on my own machine and Minikube, so portability beyond those is what the image guarantees, not something I tested elsewhere.",
         "Reviewed the Dockerfile. Not run on a second machine."),
    ],
    proof_note="From all three stages",
    shots=[
        dict(raw=R1 + "Screenshot from 2026-01-09 12-01-09.png", alt="ollama run tinyllama answering What is Kubernetes with a made-up snack food description", cap="The bare model, asked about Kubernetes."),
        dict(raw=R1 + "Screenshot from 2026-01-10 03-25-43.png", alt="curl POST to /query returning a grounded answer: Kubernetes is a container orchestration platform", cap="The same question through RAG."),
        dict(raw=R1 + "Screenshot from 2026-01-10 04-27-54.png", alt="Swagger UI POST /add returning status success and content added to knowledge base", cap="<code>/add</code>: knowledge added at runtime."),
        dict(raw=R2 + "Screenshot from 2026-01-10 21-19-34.png", alt="docker pull ahmed3015/rag-api downloading all layers from Docker Hub", cap="Pulled back from Docker Hub."),
        dict(raw=R3 + "Screenshot from 2026-01-13 04-57-36.png", alt="Swagger UI against the NodePort returning 500 Internal Server Error", cap="In the cluster, first try: <code>500</code> &mdash; the pod couldn't reach Ollama."),
        dict(raw=R3 + "Screenshot from 2026-01-14 22-33-46.png", alt="kubectl get pods --watch showing the old pod terminating and a new pod going from Pending to Running", cap="Self-healing: the replacement pod coming up."),
    ],
    broke=[
        ("The containerised API wasn't where my browser was looking",
         "The container ran fine, and my first browser attempt at <code>localhost:8000</code> got <em>Unable to connect</em>. The problem was the URL and port mapping between host and container, not the app &mdash; once the published port and the URL agreed, the same <code>/query</code> answered."),
        ("<code>500 Internal Server Error</code> from inside the cluster",
         "The API pod started and every query failed: it couldn't reach Ollama on my host. Ollama was listening on <code>127.0.0.1</code> only, which nothing outside the host's loopback can reach, and setting <code>OLLAMA_HOST</code> in my shell didn't change the systemd service that actually runs it. Making the service listen on all interfaces, and pointing the pod's <code>OLLAMA_HOST</code> at the host, fixed it. This took most of the four hours."),
    ],
    source="The FastAPI service, the embedding scripts, the knowledge base, the Dockerfile and the Kubernetes manifests live here: <a href=\"https://github.com/kingswanzy2020/nextwork-rag-api\">kingswanzy2020/nextwork-rag-api</a>. The same repo carries the <a href=\"../rag-semantic-ci/\">semantic-test CI workflow</a>.",
    clone="git clone https://github.com/kingswanzy2020/nextwork-rag-api.git\neval $(minikube docker-env) &amp;&amp; docker build -t rag-app .\nkubectl apply -f deployment.yaml -f service.yaml\nminikube service rag-app-service --url",
    stack="FastAPI &middot; Uvicorn &middot; RAG &middot; Chroma &middot; Ollama (tinyllama) &middot; Docker &middot; Docker Hub &middot; Kubernetes Deployments &amp; Services &middot; Minikube &middot; NodePort &middot; label selectors &middot; cluster-to-host networking",
),
# ======================================================================
dict(
    slug="grafana-mcp",
    card=dict(group="obs", eyebrow="Observability / AI", color="c-obs", status="Local stack",
              title="Grafana dashboards built through MCP",
              desc="Six panels over PostgreSQL, described in plain language to an agent that drives Grafana's API."),
    title_tag="Grafana Dashboards via MCP",
    meta="Case study: an e-commerce analytics dashboard over PostgreSQL, built and updated in natural language through an AI agent that drives Grafana's API via the Model Context Protocol.",
    eyebrow="Observability / AI",
    h1="Grafana dashboards built and updated through MCP",
    standfirst="I connected an AI agent in Cursor to Grafana and PostgreSQL through MCP servers, then built a six-panel e-commerce dashboard by describing it &mdash; and changed the data underneath to watch the panels re-rank live.",
    chip="Local stack",
    status="Grafana and PostgreSQL ran in Docker on my machine, driven from Cursor. Nothing was hosted. The schema and seed data in the repo reproduce the database; everything below describes that local session.",
    spec=[("Dashboards", "Grafana, 6 panels"), ("Data", "PostgreSQL, database demo"),
          ("Agent", "Cursor"), ("Bridge", "Grafana + Postgres MCP servers"),
          ("Auth", "Grafana service-account token"), ("Pattern", "raw vs pre-aggregated tables")],
    summary="Cursor's <code>mcp.json</code> defines a Grafana MCP server (stdio transport, the Grafana URL and a service-account token) alongside Docker and PostgreSQL servers, which gives the agent hands on each tool. I added PostgreSQL as a Grafana data source at <code>host.docker.internal:5432</code>, then asked for a dashboard: four KPI tiles &mdash; total revenue, order count, average order value, customers &mdash; bars for orders by status and revenue by region, and a monthly revenue trend. A second dashboard put a panel over the raw customer table next to panels over a pre-aggregated table, and I changed the data to watch them update.",
    how=[
        ("Why MCP instead of clicking through Grafana?", "Without it, a dashboard means logging in, writing SQL per panel and fiddling with visualisation settings &mdash; enough friction that dashboards don't get built. The MCP server turns a described panel into Grafana API calls, authenticated with a service-account token rather than my login."),
        ("Why pre-aggregated tables?", "A panel over the raw table re-scans every customer row on every refresh, which gets slower as data grows. Panels over a materialised, dbt-style aggregate read a handful of pre-computed rows. Putting both side by side made the trade-off visible."),
        ("Why <code>host.docker.internal</code>?", "Grafana runs in a container; PostgreSQL was published on the host. That name resolves to the host from inside the container."),
    ],
    diagram=dict(
        h=500,
        aria="I describe dashboards to the agent in Cursor, which calls the Grafana MCP server over stdio. The MCP server uses a service-account token to call Grafana's API and create panels. Grafana queries PostgreSQL through a data source. The agent also updates data through a PostgreSQL MCP server, and the panels refresh.",
        boxes=[dict(x=176, y=60, w=1052, h=410, k="neu", label="MY MACHINE — CURSOR · DOCKER")],
        nodes=[
            dict(id="me", x=16, y=200, w=136, k="neu", icon="user", slot="engineer", t="Me", s="plain language", tag="prompts"),
            dict(id="cur", x=210, y=200, w=180, k="ctl", icon="chat", slot="ai", t="Cursor agent", s="mcp.json", tag="3 MCP servers"),
            dict(id="gmcp", x=450, y=100, w=200, k="ctl", icon="ctl", slot="mcp", t="Grafana MCP", s="stdio · service token", tag="50 tools"),
            dict(id="pmcp", x=450, y=330, w=200, k="ctl", icon="ctl", slot="mcp", t="Postgres MCP", s="queries + updates", tag="9 tools"),
            dict(id="graf", x=720, y=100, w=200, k="obs", icon="bars", slot="grafana", t="Grafana", s="E-Commerce Analytics", tag="6 panels"),
            dict(id="pg", x=720, y=330, w=200, k="app", icon="db", slot="postgresql", t="PostgreSQL", s="demo · raw + aggregated", tag="host.docker.internal"),
            dict(id="dash2", x=990, y=100, w=200, k="obs", icon="trend", slot="grafana", t="Pipeline monitor", s="raw vs aggregated", tag="live refresh"),
        ],
        edges=[
            dict(**{"from": "me", "to": "cur"}, k="neu", mech="prompt", what="\"Build a revenue dashboard\", in words."),
            dict(**{"from": "cur", "to": "gmcp"}, k="ctl", ss="r", ts="l", mech="MCP over stdio", what="The agent picks Grafana tools to create panels and queries."),
            dict(**{"from": "gmcp", "to": "graf"}, k="ctl", mech="Grafana API", what="Creates and updates dashboards with a service-account token."),
            dict(**{"from": "graf", "to": "pg"}, k="data", mech="SQL data source", what="Every panel query; tested with <em>Database Connection OK</em>."),
            dict(**{"from": "cur", "to": "pmcp"}, k="ctl", ss="r", ts="l", mech="MCP over stdio", what="Used to change the raw and aggregated data during the live test."),
            dict(**{"from": "pmcp", "to": "pg"}, k="data", mech="UPDATE", what="Shifted customer counts so the top country changed."),
            dict(**{"from": "graf", "to": "dash2"}, k="obs", mech="second dashboard", what="One panel scans raw rows; two read the pre-aggregated table."),
        ],
    ),
    figcaption="The session as it ran. Arrows 2 and 3 replace the part of dashboard-building people skip; arrow 6 is how I tested the result &mdash; by changing the data and watching the panels follow.",
    legend=[("c-neu", "Me", "plain-language prompts"), ("c-ctl", "Agent &amp; MCP servers", "Cursor and its tools"),
            ("c-obs", "Dashboards", "Grafana"), ("c-app", "Data", "PostgreSQL"),
            ("line:c-ctl", "Tool calls", "agent to API"), ("line:dg-line", "SQL", "queries and updates"),
            ("line:c-obs", "Dashboards", "panels from data")],
    reach=[("Public", "nothing; Grafana and PostgreSQL were local containers."),
           ("Agent access", "a Grafana service-account token and a PostgreSQL connection, through MCP."),
           ("Data", "seeded e-commerce demo data, no real customers.")],
    ledger_intro_obs="the dashboards",
    ledger=[
        ("measured", "Changing the data re-ranked the panels live",
         "Through the agent I updated the raw and aggregated tables. On refresh, the raw-data panel showed Egypt's count up, the top-country panel switched from Korea to Egypt, and total customers stayed at 2K &mdash; each panel following the table it reads.",
         "Updated the data through the Postgres MCP server and refreshed the pipeline dashboard."),
        ("observed", "A six-panel dashboard from a description",
         "The E-Commerce Analytics dashboard came out with total revenue $5.09M, 10,000 orders, $509 average order value and 2,000 customers, plus orders by status, revenue by region, and a monthly revenue trend.",
         "Read the dashboard in Grafana."),
        ("observed", "All three MCP servers connected",
         "After a full restart, Cursor listed the Docker, Grafana and PostgreSQL servers with green indicators &mdash; 4, 50 and 9 tools &mdash; and the Grafana data source test reported <em>Database Connection OK</em>.",
         "Checked Cursor's installed MCP servers and Grafana's data source test."),
        ("design", "Aggregated panels stay fast as data grows &mdash; not timed",
         "The raw panel scans every row per refresh; the aggregated panels read pre-computed rows. On 2,000 customers both felt instant, so I'm stating the scaling property, not a measured difference.",
         "Reviewed the panel queries. No timing captured."),
    ],
    proof_note="From the local session",
    shots=[
        dict(pdf="legendary-mcp-data-engineer4/i-004.png", name="mcp-servers.jpg", alt="Cursor installed MCP servers: docker 4 tools, grafana 50 tools, postgres 9 tools, all enabled", cap="The MCP servers Cursor could use."),
        dict(pdf="legendary-mcp-data-engineer4/i-001.png", name="dashboard.jpg", alt="Grafana E-Commerce Analytics dashboard: $5.09M revenue, 10000 orders, $509 AOV, 2000 customers, orders by status and revenue by region", cap="The six-panel dashboard, built from a description."),
        dict(pdf="legendary-mcp-data-engineer4/i-012.png", name="revenue-trend.jpg", alt="Grafana monthly revenue trend time series", cap="The monthly revenue trend."),
        dict(pdf="legendary-mcp-data-engineer4/i-014.png", name="pipeline-monitor.jpg", alt="Grafana Data Pipeline Monitor: raw customer data by region, top country Egypt, total customers 2K", cap="After the data change: Egypt on top."),
    ],
    broke=[
        ("Wiring the MCP servers was the hard part",
         "The dashboard was quick once the agent could reach Grafana. Getting there &mdash; the stdio transport, the URL, a service-account token, and a full Cursor restart before the servers showed green &mdash; took most of the ninety minutes."),
    ],
    source="The PostgreSQL schema and seed data the dashboards query live here: <a href=\"https://github.com/kingswanzy2020/mcp-data-series\">kingswanzy2020/mcp-data-series</a>.",
    clone="git clone https://github.com/kingswanzy2020/mcp-data-series.git",
    stack="Grafana &middot; Model Context Protocol (MCP) &middot; Cursor &middot; PostgreSQL &middot; Docker &middot; stat, bar and time-series panels &middot; materialised aggregation &middot; service-account tokens",
),
# ======================================================================
dict(
    slug="nginx-gateway",
    card=dict(group="net", eyebrow="Networking", color="c-ctl", status="Local lab",
              title="An NGINX traffic gateway you can watch work",
              desc="One process as gateway and two backends; balancing, a cache MISS&rarr;HIT and a deliberate 502, all in one access log."),
    title_tag="NGINX Traffic Gateway",
    meta="Case study: one unprivileged NGINX process acting as gateway and two upstream backends, with round-robin balancing, caching and a deliberate 502 all observable in a single access log.",
    eyebrow="Networking",
    h1="An NGINX traffic gateway where balancing and caching show up in the log",
    standfirst="I ran one NGINX process as a public gateway and both of its own upstream backends, so round-robin balancing, a cache MISS-to-HIT transition and a deliberate 502 all show up in a single access log &mdash; with no containers, no root and no port below 1024.",
    chip="Local lab, not a service",
    status="This is a lab that runs from a cloned directory with <code>nginx -p \"$PWD\"</code>, not something deployed. The commands under Source reproduce every log line below on any machine with NGINX installed.",
    spec=[("Server", "nginx/1.31.5, one process"), ("Roles", "gateway :8080, backends :8081 :8082"),
          ("Balancing", "upstream pool, round robin"), ("Cache", "proxy_cache on /app/"),
          ("Failure", "deliberate 502 via :8999"), ("Privilege", "none &mdash; prefix-relative config")],
    summary="A request to <code>:8080/</code> is served from the gateway's own document root. A request to <code>/app/</code> goes through <code>proxy_pass</code>: the cache is consulted first, and on a MISS the request goes to <code>backend_pool</code>, which alternates between backend-a on <code>:8081</code> and backend-b on <code>:8082</code> &mdash; sibling <code>server</code> blocks in the same config, each stamping its own <code>X-Backend</code> header. A third path points at <code>:8999</code>, where nothing listens. A custom log format prints <code>upstream=</code> and <code>cache=</code> on every line, so all of it can be read in one place.",
    how=[
        ("Why put <code>upstream=</code> and <code>cache=</code> in the log?", "Stock NGINX logs show neither, which is why the interaction between balancing and caching is normally invisible. Once a response is cached, <code>upstream=</code> goes empty and the alternating backends <em>stop</em> alternating. With both fields on every line, that reads as the cache working instead of the pool breaking."),
        ("Why override <code>Cache-Control</code>, and only on <code>/app/</code>?", "Both backends send <code>Cache-Control: no-store</code>, and NGINX honours it by caching nothing &mdash; <code>cache=MISS</code> forever, with no warning. <code>proxy_ignore_headers Cache-Control</code> scoped to <code>/app/</code> lets the cache be exercised there while leaving the gateway's own responses honest."),
        ("Why the backends in the same file?", "In production they'd be separate hosts. Collapsing them into one config trades realism for legibility: the whole request path, both ends of it, is one file read top to bottom."),
        ("Why break it on purpose?", "A 502 looks the same in the browser whether the upstream is down, unreachable or never existed. Pointing a path at a port with no listener gives a failure whose cause I already know, so I can learn what the error log says about it."),
    ],
    diagram=dict(
        h=560,
        aria="A client sends requests to the NGINX gateway on port 8080. Requests for / are served from the gateway's own document root. Requests for /app/ check the proxy cache; a HIT returns immediately, a MISS goes to the upstream pool, which alternates between backend-a on 8081 and backend-b on 8082. Requests for /broken/ go to port 8999, where nothing listens, producing a 502 recorded in the error log. Every request is written to an access log with upstream and cache fields.",
        boxes=[dict(x=176, y=60, w=1052, h=470, k="ctl", label="ONE NGINX PROCESS — nginx -p \"$PWD\" -c conf/nginx.conf · NO ROOT")],
        nodes=[
            dict(id="cli", x=16, y=200, w=136, k="neu", icon="terminal", slot="browser", t="curl / browser", s="localhost", tag=":8080"),
            dict(id="gw", x=210, y=200, w=190, k="ctl", icon="lb", slot="nginx", t="Gateway", s="0.0.0.0:8080", tag="3 locations"),
            dict(id="root", x=210, y=380, w=190, k="app", icon="doc", slot="html", t="Gateway page", s="location /", tag="from disk"),
            dict(id="cache", x=460, y=200, w=190, k="obs", icon="cache", slot="nginx", t="proxy_cache", s="location /app/", tag="HIT or MISS"),
            dict(id="pool", x=710, y=200, w=190, k="ctl", icon="cycle", slot="nginx", t="backend_pool", s="upstream, round robin", tag="on MISS only"),
            dict(id="a", x=990, y=110, w=200, k="app", icon="server", slot="nginx", t="backend-a", s="127.0.0.1:8081", tag="X-Backend: A"),
            dict(id="b", x=990, y=290, w=200, k="app", icon="server", slot="nginx", t="backend-b", s="127.0.0.1:8082", tag="X-Backend: B"),
            dict(id="dead", x=710, y=410, w=190, k="neu", icon="x", slot="nginx", t=":8999", s="location /broken/", tag="nothing listening"),
            dict(id="log", x=460, y=410, w=190, k="obs", icon="doc", slot="nginx", t="Logs", s="access: upstream= cache=", tag="error: refused"),
        ],
        edges=[
            dict(**{"from": "cli", "to": "gw"}, k="req", mech="HTTP :8080", what="Every request enters here."),
            dict(**{"from": "gw", "to": "root"}, k="req", mech="location /", what="The gateway's own page, straight off disk."),
            dict(**{"from": "gw", "to": "cache"}, k="req", mech="location /app/", what="Checks the cache first; a HIT returns with <code>upstream=</code> empty."),
            dict(**{"from": "cache", "to": "pool"}, k="req", mech="MISS", what="Only a miss reaches the upstream pool."),
            dict(**{"from": "pool", "to": "a"}, k="req", ss="r", ts="l", mech="round robin", what="Alternates with backend-b under equal weighting."),
            dict(**{"from": "pool", "to": "b"}, k="req", ss="r", ts="l", mech="round robin", what="Answers with <code>Cache-Control: no-store</code>, like backend-a."),
            dict(**{"from": "gw", "to": "dead"}, k="neu", pts=[(400, 270), (430, 270), (430, 380), (805, 380), (805, 406)], mech="location /broken/", what="Connection refused; the client gets <code>502 Bad Gateway</code>."),
            dict(**{"from": "dead", "to": "log"}, k="obs", dash=True, mech="error log", what="Records the real cause: connect() to <code>:8999</code> refused."),
        ],
    ),
    figcaption="The topology, all in one config. Arrow 4 is where balancing and caching meet: on a HIT it never happens, which is exactly why the alternation in arrows 5 and 6 disappears from the log once the cache warms up.",
    legend=[("c-neu", "Client &amp; the dead upstream", "curl, :8999"), ("c-ctl", "Gateway &amp; pool", "routing decisions"),
            ("c-obs", "Cache &amp; logs", "where behaviour becomes visible"), ("c-app", "Content", "the page and both backends"),
            ("line:c-app", "Request path", "served or proxied"), ("line:c-neu", "Deliberate failure", "the 502"),
            ("line:c-obs:dashed", "Logging", "the cause, recorded")],
    reach=[("Listening", "<code>0.0.0.0:8080</code> for the gateway; backends on <code>127.0.0.1</code> only."),
           ("Privilege", "none: no <code>sudo</code>, no ports below 1024, no container runtime."),
           ("Deliberately absent", "anything on <code>:8999</code>.")],
    ledger_intro_obs="the access and error logs",
    ledger=[
        ("measured", "The 502 traced to the cause I planted",
         "Requests to <code>/broken/</code> returned <code>502 Bad Gateway</code> from nginx/1.31.5 while the gateway itself stayed healthy on <code>:8080</code>. Hitting <code>127.0.0.1:8999</code> directly in a browser failed to connect, and the error log recorded the refused connection &mdash; no <code>listen 8999</code> anywhere in the config.",
         "Requested <code>/broken/</code>, browsed <code>:8999</code> directly, and read the error log."),
        ("measured", "The cache went MISS to HIT once <code>Cache-Control</code> was overridden",
         "Before the override, every <code>/app/</code> request logged <code>cache=MISS</code>. With <code>proxy_ignore_headers Cache-Control</code> on <code>/app/</code>, the log showed the MISS, then <code>cache=HIT</code> with <code>upstream=</code> empty from that line on.",
         "Repeated <code>curl localhost:8080/app/</code> before and after the change, reading the access log."),
        ("observed", "The pool alternated strictly between the two backends",
         "Consecutive <code>/app/</code> requests on a cold cache logged <code>upstream=</code> alternating <code>8081</code>, <code>8082</code>, <code>8081</code>&hellip; under NGINX's default equal weighting.",
         "Read <code>upstream=</code> across consecutive access-log lines."),
        ("design", "Config errors never reach a running listener",
         "I ran <code>nginx -t</code> before every start and reload, so a syntax error fails at validation instead of on a live reload. That's a habit I kept, not a failure I induced to prove it.",
         "Validated with <code>nginx -t -p \"$PWD\"</code> before each start and reload."),
    ],
    proof_note="From the logs and the browser",
    shots=[
        dict(raw=NG + "Screenshot from 2026-09-04 05-11-05.png", alt="Access log showing upstream alternating between 8081 and 8082, then cache=MISS, then cache=HIT with upstream empty", cap="Round-robin and caching in one log."),
        dict(raw=NG + "Screenshot from 2026-09-04 00-24-47.png", alt="NGINX Traffic Gateway landing page served on localhost:8080", cap="The gateway serving its own page on <code>:8080</code>."),
        dict(raw=NG + "Screenshot from 2026-09-04 02-09-34.png", alt="502 Bad Gateway from nginx/1.31.5 at localhost:8080", cap="The deliberate 502 at the gateway."),
        dict(raw=NG + "Screenshot from 2026-09-04 02-23-20.png", alt="Firefox unable to connect directly to 127.0.0.1:8999", cap="The upstream that was never listening."),
    ],
    broke=[
        ("<code>cache=MISS</code> on every request, forever",
         "The cache was configured correctly and doing nothing: both backends answer <code>Cache-Control: no-store</code>, and NGINX honours that by not storing the response. Neither log said why. <code>proxy_ignore_headers Cache-Control</code> on <code>/app/</code> fixed it, and HITs appeared immediately."),
        ("Load balancing \"stopped working\" the moment caching started",
         "Once responses came from cache, <code>upstream=</code> went empty and the 8081/8082 alternation vanished. That reads exactly like a broken pool. It's the cache doing its job &mdash; a HIT never touches a backend, so there's no upstream to log. Recognising that as expected behaviour was the real lesson of the build."),
        ("A 502 that had nothing to do with the gateway",
         "The browser said <em>Bad Gateway</em> while the gateway was perfectly healthy. Only the error log said where it failed: connection refused on <code>:8999</code>. The browser tells you <em>that</em> it failed; the error log tells you <em>where</em>."),
    ],
    source="The complete lab &mdash; <code>nginx.conf</code>, both backend document roots, the cache and log directories, and the run instructions &mdash; lives here: <a href=\"https://github.com/kingswanzy2020/nginx-http-lab\">kingswanzy2020/nginx-http-lab</a>.",
    clone="git clone https://github.com/kingswanzy2020/nginx-http-lab.git\ncd nginx-http-lab\nnginx -t -p \"$PWD\" -c conf/nginx.conf   # validate first, always\nnginx    -p \"$PWD\" -c conf/nginx.conf   # start\ncurl http://localhost:8080/app/",
    stack="NGINX &middot; reverse proxy &middot; proxy_pass &middot; upstream pools &middot; round-robin balancing &middot; proxy_cache &middot; Cache-Control semantics &middot; proxy_ignore_headers &middot; custom log formats &middot; $upstream_cache_status &middot; 502 diagnosis &middot; nginx -t",
),
]
